// template-angular/src/app/features-modules/freelancer/payment/invoices/invoices.component.ts
import { Component, OnInit, ViewChild, OnDestroy } from '@angular/core';

import { Subject } from "rxjs";
import { ShareDataService } from 'src/app/core/data/share-data.service';

@Component({
  selector: 'app-invoices',
  templateUrl: './invoices.component.html',
  styleUrls: ['./invoices.component.scss']
})
export class InvoicesComponent implements OnInit, OnDestroy {

  public dtTrigger: Subject<any> = new Subject();
  public lstInvoice!: any[];
  public url: any = "freelancer";
  constructor(private dataService: ShareDataService) { }

  ngOnInit(): void {
    this.loadInvoice();

  }
    // Get payment List  Api Call
    loadInvoice() {
      this.lstInvoice = this.dataService.invoice
    }

  ngOnDestroy(): void {
    // Do not forget to unsubscribe the event
    this.dtTrigger.unsubscribe();
  }

}

<!-- Breadcrumb -->
<div class="bread-crumb-bar">
    <div class="container">
        <div class="row align-items-center inner-banner">
            <div class="col-md-12 col-12 text-center">
                <div class="breadcrumb-list">
                    <nav aria-label="breadcrumb" class="page-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a [routerLink]="'/home'"><img src="assets/img/home-icon.svg" alt="Post Author"> Home</a></li>
                            <li class="breadcrumb-item" aria-current="page">Freelancer</li>
                            <li class="breadcrumb-item" aria-current="page">Payments</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Breadcrumb -->
<!-- Page Content -->
<div class="content content-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-3 col-md-4 theiaStickySidebar">
                <div class="settings-widget">
                    <div class="settings-header d-sm-flex flex-row flex-wrap text-center text-sm-start align-items-center">
                        <a [routerLink] = "'/freelancer/user-details'"><img alt="profile image" src="assets/img/user/avatar-1.jpg" class="avatar-lg rounded-circle"></a>
                        <div class="ms-sm-3 ms-md-0 ms-lg-3 mt-2 mt-sm-0 mt-md-2 mt-lg-0">
                            <p class="mb-2">Welcome,</p>
                            <h3 class="mb-0"><a [routerLink] = "'/freelancer/user-details'">John Danie S.</a></h3>
                            <p class="mb-0">@johndaniee</p>
                        </div>
                    </div>
                    <div class="settings-menu">
                        <ul>
                            <li class="nav-item">
                                <a [routerLink] = "'/freelancer/dashboards'" class="nav-link ">
                                    <i class="material-icons">verified_user</i> Dashboard
                                </a>
                            </li>
                            <li class="nav-item">
                                <a [routerLink] = "'/freelancer/freelancer-projects/projects-proposals'" class="nav-link ">
                                    <i class="material-icons">business_center</i> Projects
                                </a>
                            </li>
                            <li class="nav-item">
                                <a [routerLink] = "'/freelancer/freelancer-favourite/favourite'" class="nav-link ">
                                    <i class="material-icons">local_play</i> Favourites
                                </a>
                            </li>
                            <li class="nav-item">
                                <a [routerLink] = "'/freelancer/reviews'" class="nav-link ">
                                    <i class="material-icons">record_voice_over</i> Reviews
                                </a>
                            </li>
                            <li class="nav-item">
                                <a [routerLink] = "'/freelancer/portfolio'" class="nav-link ">
                                    <i class="material-icons">pie_chart</i> Portfolio
                                </a>
                            </li>
                            <li class="nav-item">
                                <a [routerLink] = "'/freelancer/message'" class="nav-link">
                                    <i class="material-icons">chat</i> Messages
                                </a>
                            </li>
                            <li class="nav-item">
                                <a [routerLink] = "'/freelancer/membership'" class="nav-link ">
                                    <i class="material-icons">person_add</i> Membership
                                </a>
                            </li>
                            <li class="nav-item">
                                <a [routerLink] = "'/freelancer/verify-identitys'" class="nav-link ">
                                    <i class="material-icons">person_pin</i> Verify Identity
                                </a>
                            </li>
                            <li class="nav-item">
                                <a [routerLink] = "'/freelancer/freelancer-payments/withdraw-money'" class="nav-link active">
                                    <i class="material-icons">wifi_tethering</i> Payments
                                </a>
                            </li>
                            <li class="nav-item">
                                <a [routerLink] = "'/freelancer/profile-settings'" class="nav-link">
                                    <i class="material-icons">settings</i>  Settings
                                </a>
                            </li>
                            <li class="nav-item">
                                <a [routerLink] = "'/home'" class="nav-link">
                                    <i class="material-icons">power_settings_new</i> Logout
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>					
            </div>	
            <div class="col-xl-9 col-md-8">
                <nav class="user-tabs mb-4">
                    <ul class="nav nav-tabs nav-tabs-bottom nav-justified">
                        <li class="nav-item">
                            <a class="nav-link " [routerLink] = "'/freelancer/freelancer-payments/withdraw-money'">Withdraw Funds</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" [routerLink] = "'/freelancer/freelancer-payments/invoices'"> Invoices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " [routerLink] = "'/freelancer/freelancer-payments/history'"> Transaction History</a>
                        </li>
                    </ul>
                </nav>	
                <div class="transaction-table card">
                    <div class="card-header">
                        <div class="row justify-content-between align-items-center">
                            <div class="col">
                                <h5 class="card-title">All Invoices</h5>
                            </div>
                            <div class="col-auto d-flex align-items-center flex-wrap transaction-shortby">
                                    <div class="export-item sort-show sort-by"><i class="fas fa-download"></i> Export</div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive table-box">
                            <table class="table" >
                                <thead>
                                    <tr class="thead-pink">
                                        <th>Invoice Number</th>
                                        <th>Client Name</th>
                                        <th>Created Date</th>
                                        <th>Amount</th>
                                        <th>Due Date</th>
                                        <th>Status</th>
                                        <th>Paid On</th>
                                    </tr>
                                </thead>
                                <tbody class="table table-hover table-center">

                                    <tr *ngFor="let invoice of lstInvoice;let i = index">
                                        <td><a [routerLink] = "'/view-invoice'" class="invoice-id">{{invoice.invoices}}</a></td>
                                        <td>{{invoice.client}}</td>
                                        <td>{{invoice.lastvisit}}</td>
                                        <td>${{invoice.amount}}</td>
                                        <td>{{invoice.duedate}}</td>
                                        <td *ngIf = "invoice.availability === 'Paid'">
                                            <span class="badge bg-success-light">{{invoice.availability}}</span>
                                        </td>
                                        <td  *ngIf = "invoice.availability === 'Partially Paid'">
                                            <span class="badge bg-warning-light">{{invoice.availability}}</span>
                                        </td>
                                        <td *ngIf = "invoice.availability === 'Overdue'">
                                            <span class="badge bg-danger-light">{{invoice.availability}}</span>
                                        </td>
                                        <td>{{invoice?.paidon | date : 'dd MMM yyyy, h.mm a'}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>												
            </div>						
        </div>
    </div>
</div>	

<!-- /Page Content -->

// template-react/src/frontend/components/pages/invoices/invoices.jsx
import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import StickyBox from "react-sticky-box";
import { Sidebar } from '../../forfreelancer/sidebar';
// Select2 CSS
import '../../../assets/plugins/select2/css/select2.min.css';
import { home_icon } from "../../imagepath";

const Invoices = () => {
   
      useEffect(() => {
        document.body.className = 'dashboard-page';
        return () => { document.body.className = ''; }
      });
        return (
            <>
            {/* Breadcrumb */}
      <div className="bread-crumb-bar">
        <div className="container">
          <div className="row align-items-center inner-banner">
            <div className="col-md-12 col-12 text-center">
              <div className="breadcrumb-list">
                <nav aria-label="breadcrumb" className="page-breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item"><Link to="#"><img src={home_icon} alt="Post Author" /> Home</Link></li>
                    <li className="breadcrumb-item" aria-current="page">FREELANCER
</li>
                    <li className="breadcrumb-item" aria-current="page">PAYMENTS</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Breadcrumb */}
            {/* Page Content */}
            <div className="content content-page">
              <div className="container-fluid">
                <div className="row">
                  <div className="col-xl-3 col-md-4 theiaStickySidebar">
                    <StickyBox offsetTop={20} offsetBottom={20}>
                        <Sidebar/>
                    </StickyBox>
                    
                  </div>
                  <div className="col-xl-9 col-md-8">
                    <nav className="user-tabs mb-4">
                      <ul className="nav nav-tabs nav-tabs-bottom nav-justified">
                        <li className="nav-item">
                          <Link className="nav-link" to="/freelancer-withdraw-money">
                            Withdraw Funds
                          </Link>
                        </li>
                        <li className="nav-item">
                          <Link className="nav-link active" to="/freelancer-invoices">
                            {" "}
                            Invoices
                          </Link>
                        </li>
                        <li className="nav-item">
                          <Link
                            className="nav-link"
                            to="/freelancer-transaction-history"
                          >
                            {" "}
                            Transaction History
                          </Link>
                        </li>
                      </ul>
                    </nav>
                    <div className="transaction-table card">
                      <div className="card-header">
                        <div className="row justify-content-between align-items-center">
                          <div className="col">
                            <h5 className="card-title">All Invoices</h5>
                          </div>
                          <div className="col-auto d-flex align-items-center flex-wrap transaction-shortby">
                            <div className="sort-by sort-show">
                              <span className="sort-title">Show</span>
                              <span className="sortby-fliter">
                                <select className="select">
                                  <option>5</option>
                                  <option className="sorting">4</option>
                                  <option className="sorting">3</option>
                                  <option className="sorting">6</option>
                                  <option className="sorting">3</option>
                                </select>
                              </span>
                            </div>
                            <div className="export-item sort-show sort-by">
                              <i className="fas fa-download" /> Export
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="card-body">
                        <div className="table-responsive table-box">
                          <table className="table">
                            <thead>
                              <tr className="thead-pink">
                                <th>Invoice Number</th>
                                <th>Client Name</th>
                                <th>Created Date</th>
                                <th>Amount</th>
                                <th>Due Date</th>
                                <th>Status</th>
                                <th>Paid On</th>
                              </tr>
                            </thead>
                            <tbody className="table table-hover table-center">
                              <tr>
                                <td>
                                  <Link to="/view-invoice" className="invoice-id">
                                    INV-5622
                                  </Link>
                                </td>
                                <td>Amaze Tech</td>
                                <td>16 Sep 2021</td>
                                <td>$150</td>
                                <td>22 Oct 2021</td>
                                <td>
                                  <span className="badge bg-success-light">Paid</span>
                                </td>
                                <td>22 Oct 2021, 10:45pm</td>
                              </tr>
                              <tr>
                                <td>
                                  <Link to="/view-invoice" className="invoice-id">
                                    INV-4545
                                  </Link>
                                </td>
                                <td>Park Inc</td>
                                <td>12 Sep 2021</td>
                                <td>$150</td>
                                <td>25 Oct 2021</td>
                                <td>
                                  <span className="badge bg-warning-light">
                                    Partially Paid
                                  </span>
                                </td>
                                <td>25 Oct 2021, 10:45pm</td>
                              </tr>
                              <tr>
                                <td>
                                  <Link to="/view-invoice" className="invoice-id">
                                    INV-2254
                                  </Link>
                                </td>
                                <td>Tech Zone </td>
                                <td>10 Sep 2021</td>
                                <td>$150</td>
                                <td>15 Oct 2021</td>
                                <td>
                                  <span className="badge bg-success-light">Paid</span>
                                </td>
                                <td>10 Oct 2021, 10:45pm</td>
                              </tr>
                              <tr>
                                <td>
                                  <Link to="/view-invoice" className="invoice-id">
                                    INV-1582
                                  </Link>
                                </td>
                                <td>Abc Software</td>
                                <td>13 Sep 2021</td>
                                <td>$150</td>
                                <td>28 Oct 2021</td>
                                <td>
                                  <span className="badge bg-danger-light">Overdue</span>
                                </td>
                                <td>13 Oct 2021, 10:45pm</td>
                              </tr>
                              <tr>
                                <td>
                                  <Link to="/view-invoice" className="invoice-id">
                                    INV-1526
                                  </Link>
                                </td>
                                <td>Host Technologies</td>
                                <td>12 Sep 2021</td>
                                <td>$150</td>
                                <td>29 Oct 2021</td>
                                <td>
                                  <span className="badge bg-warning-light">
                                    Partially Paid
                                  </span>
                                </td>
                                <td>29 Oct 2021, 10:45pm</td>
                              </tr>
                              <tr>
                                <td>
                                  <Link to="/view-invoice" className="invoice-id">
                                    INV-1200
                                  </Link>
                                </td>
                                <td>Alfred Tech </td>
                                <td>05 Sep 2021</td>
                                <td>$150</td>
                                <td>15 Oct 2021</td>
                                <td>
                                  <span className="badge bg-warning-light">
                                    Partially Paid
                                  </span>
                                </td>
                                <td>15 Oct 2021, 10:45pm</td>
                              </tr>
                              <tr>
                                <td>
                                  <Link to="/view-invoice" className="invoice-id">
                                    INV-1212
                                  </Link>
                                </td>
                                <td>Kind Softwares </td>
                                <td>02 Sep 2021</td>
                                <td>$150</td>
                                <td>22 Oct 2021</td>
                                <td>
                                  <span className="badge bg-success-light">Paid</span>
                                </td>
                                <td>22 Oct 2021, 10:45pm</td>
                              </tr>
                              <tr>
                                <td>
                                  <Link to="/view-invoice" className="invoice-id">
                                    INV-1456
                                  </Link>
                                </td>
                                <td>Tech Zone </td>
                                <td>10 Sep 2021</td>
                                <td>$150</td>
                                <td>15 Oct 2021</td>
                                <td>
                                  <span className="badge bg-danger-light">Overdue</span>
                                </td>
                                <td>10 Oct 2021, 10:45pm</td>
                              </tr>
                              <tr>
                                <td>
                                  <Link to="/view-invoice" className="invoice-id">
                                    INV-1236
                                  </Link>
                                </td>
                                <td>Abc Software</td>
                                <td>13 Sep 2021</td>
                                <td>$150</td>
                                <td>28 Oct 2021</td>
                                <td>
                                  <span className="badge bg-danger-light">Overdue</span>
                                </td>
                                <td>13 Oct 2021, 10:45pm</td>
                              </tr>
                              <tr>
                                <td>
                                  <Link to="/view-invoice" className="invoice-id">
                                    INV-1566
                                  </Link>
                                </td>
                                <td>Park Inc</td>
                                <td>12 Sep 2021</td>
                                <td>$150</td>
                                <td>25 Oct 2021</td>
                                <td>
                                  <span className="badge bg-success-light">Paid</span>
                                </td>
                                <td>25 Oct 2021, 10:45pm</td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Page Content */}
          </>
         )
    
}
export default Invoices;
