// template-vuejs/src/views/frontend/freelancer/favourites.vue
<template>
<div class="dashboard-page">
       <!-- Main Wrapper -->
        <div class="main-wrapper">
			<!-- Header -->
            <layout-freelancerprojectheader></layout-freelancerprojectheader>
			<!-- /Header -->

            <!-- Breadcrumb -->
            <div class="bread-crumb-bar">
				<div class="container">
					<div class="row align-items-center inner-banner">
						<div class="col-md-12 col-12 text-center">
							<div class="breadcrumb-list">
								<nav aria-label="breadcrumb" class="page-breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><router-link to="/index"><img src="../../../assets/img/home-icon.svg" alt="Post Author"> Home</router-link></li>
										<li class="breadcrumb-item" aria-current="page">Freelancer</li>
										<li class="breadcrumb-item" aria-current="page">Favourites</li>
									</ol>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Page Content -->
			<div class="content content-page">
				<div class="container-fluid">
					
					<div class="row">
						<layout-freelancerprojectsidebar></layout-freelancerprojectsidebar>	
						<div class="col-xl-9 col-md-8">
							<nav class="user-tabs mb-4">
								<ul class="nav nav-tabs nav-tabs-bottom nav-justified">
									<li class="nav-item">
										<router-link class="nav-link active" to="/freelancer-favourites">Bookmarked Projects</router-link>
									</li>
									<li class="nav-item">
										<router-link class="nav-link" to="/freelancer-invitations">Invitations</router-link>
									</li>
								</ul>
							</nav>
							<!-- project list -->
							<!-- project list -->
							<div class="my-projects-view favourite-group">
								<div class="row">
									<div class="col-lg-12">
										<div class="card">
											<div class="card-header d-flex">
												<h5 class="card-title">Bookmarked Projects</h5>
												<ul class="list-grid d-flex align-items-center">
													<li><router-link to="/freelancer-favourites"><i class="fas fa-list"></i></router-link></li>
													<li><router-link to="/freelancer-favourites" class="favour-active"><i class="fas fa-th-large"></i></router-link></li>
												</ul>
											</div>
											<div class="freelance-box book-mark bookmark-projects">
												<div class="row">
													<div class="col-md-12 col-lg-12 col-xl-12">
														<div class="relavance-result d-flex align-items-center">
															<h4>Found 455 Results</h4>
															<div class="relavance-rate d-flex justify-content-sm-end">
															   <div class="sort-by">
																  <label>Sort By: </label>
																  <select class="custom-select form-select">
																	 <option>Relevance</option>
																	 <option>Rating</option>
																	 <option>Popular</option>
																	 <option>Latest</option>
																	 <option>Free</option>
																  </select>
															   </div>
															</div>
														</div>
													</div>
													<!-- Project Content -->
													<div class="col-md-6 col-lg-12 col-xl-3">
													
														<div class="freelance-widget widget-author">
															<div class="freelance-content">
															<a data-bs-toggle="modal" href="#rating" class="favourite favourited"><i class="fas fa-star"></i></a>
															<div class="author-heading">
																<div class="profile-img">
																	<router-link to="/project-details">
																		<img src="../../../assets/img/company/img-1.png" alt="author">
																		<span class="project-verified"><i class="fas fa-check-circle"></i></span>
                                                                    </router-link>
																</div>
																<div class="profile-name">
																	<div class="author-location"><router-link to="/project-details">Amaze Tech </router-link></div>
																</div>
																<div class="freelance-info">
																	<h3><a href="javascript:void(0);">UI/UX Developer</a></h3>
																	<div class="freelance-location post-now mb-1"><i class="fas fa-clock"></i> Posted Just Now</div>
																	<div class="freelance-location"><i class="fas fa-map-marker-alt me-1"></i>Alabama, USA</div>
																</div>
																<div class="freelance-tags">
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design me-1">Web Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design">UI Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design ms-1">Node Js</span></a>
																</div>
																<div class="freelancers-price">$40-$500</div>
															</div>
															<div class="counter-stats">
																	<ul>
																		<li>
																			<h5>Expiry</h5>
																			<h3 class="counter-value">4 Days Left</h3>
																		</li>
																		<li>
																			<h5>Proposals</h5>
																			<h3 class="counter-value">15</h3>
																		</li>
																		<li>
																			<h5>Job Type</h5>
																			<h3 class="counter-value"><span class="jobtype">Full Time</span></h3>
																		</li>
																	</ul>
																</div>
															</div>
															<div class="cart-hover">
																<router-link to="/project-details" class="btn-cart" tabindex="-1">View Profile</router-link>
															</div>
														</div>
													</div>
													<div class="col-md-6 col-lg-12 col-xl-3">
													
														<div class="freelance-widget widget-author">
															<div class="freelance-content">
															<a data-bs-toggle="modal" href="#rating" class="favourite favourited"><i class="fas fa-star"></i></a>
															<div class="author-heading">
																<div class="profile-img">
																	<router-link to="/project-details">
																		<img src="../../../assets/img/company/img-2.png" alt="author">
																		<span class="project-verified"><i class="fas fa-check-circle"></i></span>
                                                                    </router-link>
																</div>
																<div class="profile-name">
																	<div class="author-location"><router-link to="/project-details">Park INC </router-link></div>
																</div>
																<div class="freelance-info">
																	<h3><a href="javascript:void(0);">PHP Developer</a></h3>
																	<div class="freelance-location post-now mb-1"><i class="fas fa-clock"></i> Posted 1 min ago</div>
																	<div class="freelance-location"><i class="fas fa-map-marker-alt me-1"></i>California, USA</div>
																</div>
																<div class="freelance-tags">
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design me-1">Web Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design">UI Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design ms-1">Node Js</span></a>
																</div>
																<div class="freelancers-price">$30-$300</div>
															</div>
															<div class="counter-stats">
																	<ul>
																		<li>
																			<h5>Expiry</h5>
																			<h3 class="counter-value">5 Days Left</h3>
																		</li>
																		<li>
																			<h5>Proposals</h5>
																			<h3 class="counter-value">15</h3>
																		</li>
																		<li>
																			<h5>Job Type</h5>
																			<h3 class="counter-value"><span class="jobtype">Full Time</span></h3>
																		</li>
																	</ul>
																</div>
															</div>
															<div class="cart-hover">
																<router-link to="/project-details" class="btn-cart" tabindex="-1">View Profile</router-link>
															</div>
														</div>
													</div>
													<div class="col-md-6 col-lg-12 col-xl-3">
													
														<div class="freelance-widget widget-author">
															<div class="freelance-content">
															<a data-bs-toggle="modal" href="#rating" class="favourite favourited"><i class="fas fa-star"></i></a>
															<div class="author-heading">
																<div class="profile-img">
																	<router-link to="/project-details">
																		<img src="../../../assets/img/company/img-3.png" alt="author">
																		<span class="project-verified"><i class="fas fa-check-circle"></i></span>
                                                                    </router-link>
																</div>
																<div class="profile-name">
																	<div class="author-location"><router-link to="/project-details">Tech Zone</router-link> </div>
																</div>
																<div class="freelance-info">
																	<h3><a href="javascript:void(0);">Graphic Designer</a></h3>
																	<div class="freelance-location post-now mb-1"><i class="fas fa-clock"></i> Posted 30 mins ago</div>
																	<div class="freelance-location"><i class="fas fa-map-marker-alt me-1"></i>New York, USA</div>
																</div>
																<div class="freelance-tags">
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design me-1">Web Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design">UI Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design ms-1">Node Js</span></a>
																</div>
																<div class="freelancers-price">$15-$500</div>
															</div>
															<div class="counter-stats">
																<ul>
																	<li>
																		<h5>Expiry</h5>
																		<h3 class="counter-value">4 Days Left</h3>
																	</li>
																	<li>
																		<h5>Proposals</h5>
																		<h3 class="counter-value">15</h3>
																	</li>
																	<li>
																		<h5>Job Type</h5>
																		<h3 class="counter-value"><span class="jobtype">Full Time</span></h3>
																	</li>
																</ul>
															</div>
															</div>
															<div class="cart-hover">
																<router-link to="/project-details" class="btn-cart" tabindex="-1">View Profile</router-link>
															</div>
														</div>
													</div>
													
													<div class="col-md-6 col-lg-12 col-xl-3">
														<div class="freelance-widget widget-author">
															<div class="freelance-content">
															<a data-bs-toggle="modal" href="#rating" class="favourite favourited"><i class="fas fa-star"></i></a>
															<div class="author-heading">
																<div class="profile-img">
																	<router-link to="/project-details">
																		<img src="../../../assets/img/company/img-4.png" alt="author">
																		<span class="project-verified"><i class="fas fa-check-circle"></i></span>
                                                                    </router-link>
																</div>
																<div class="profile-name">
																	<div class="author-location"><router-link to="/project-details">ABC Software</router-link> </div>
																</div>
																<div class="freelance-info">
																	<h3><a href="javascript:void(0);">iOS Developer</a></h3>
																	<div class="freelance-location post-now mb-1"><i class="fas fa-clock"></i> Posted 1 day ago</div>
																	<div class="freelance-location"><i class="fas fa-map-marker-alt me-1"></i>Florida, USA</div>
																</div>
																<div class="freelance-tags">
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design me-1">Web Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design">UI Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design ms-1">Node Js</span></a>
																</div>
																<div class="freelancers-price">$25-$250</div>
															</div>
															<div class="counter-stats">
																<ul>
																	<li>
																		<h5>Expiry</h5>
																		<h3 class="counter-value">1 Days Left</h3>
																	</li>
																	<li>
																		<h5>Proposals</h5>
																		<h3 class="counter-value">13</h3>
																	</li>
																	<li>
																		<h5>Job Type</h5>
																		<h3 class="counter-value"><span class="jobtype">Full Time</span></h3>
																	</li>
																</ul>
															</div>
															</div>
															<div class="cart-hover">
																<router-link to="/project-details" class="btn-cart" tabindex="-1">View Profile</router-link>
															</div>
														</div>
													</div>
													
													<div class="col-md-6 col-lg-12 col-xl-3">
														<div class="freelance-widget widget-author">
															<div class="freelance-content">
															<a data-bs-toggle="modal" href="#rating" class="favourite favourited"><i class="fas fa-star"></i></a>
															<div class="author-heading">
																<div class="profile-img">
																	<router-link to="/project-details">
																		<img src="../../../assets/img/company/img-5.png" alt="author">
																		<span class="project-verified"><i class="fas fa-check-circle"></i></span>
                                                                    </router-link>
																</div>
																<div class="profile-name">
																	<div class="author-location"><router-link to="/project-details">Host Technologies</router-link></div>
																</div>
																<div class="freelance-info">
																	<h3><a href="javascript:void(0);">SEO Developer</a></h3>
																	<div class="freelance-location post-now mb-1"><i class="fas fa-clock"></i> Posted 3 days ago</div>
																	<div class="freelance-location"><i class="fas fa-map-marker-alt me-1"></i>Texas, USA</div>
																</div>
																<div class="freelance-tags">
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design me-1">Web Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design">UI Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design ms-1">Node Js</span></a>
																</div>
																<div class="freelancers-price">$50-$700</div>
															</div>
															<div class="counter-stats">
																<ul>
																	<li>
																		<h5>Expiry</h5>
																		<h3 class="counter-value">6 Days Left</h3>
																	</li>
																	<li>
																		<h5>Proposals</h5>
																		<h3 class="counter-value">18</h3>
																	</li>
																	<li>
																		<h5>Job Type</h5>
																		<h3 class="counter-value"><span class="jobtype">Full Time</span></h3>
																	</li>
																</ul>
															</div>
															</div>
															<div class="cart-hover">
																<router-link to="/project-details" class="btn-cart" tabindex="-1">View Profile</router-link>
															</div>
														</div>
													</div>
													
													<div class="col-md-6 col-lg-12 col-xl-3">
														<div class="freelance-widget widget-author">
															<div class="freelance-content">
															<a data-bs-toggle="modal" href="#rating" class="favourite favourited"><i class="fas fa-star"></i></a>
															<div class="author-heading">
																<div class="profile-img">
																	<router-link to="/project-details">
																		<img src="../../../assets/img/company/img-6.png" alt="author">
																		<span class="project-verified"><i class="fas fa-check-circle"></i></span>
                                                                    </router-link>
																</div>
																<div class="profile-name">
																	<div class="author-location"><router-link to="/project-details">Alfred Tech</router-link> </div>
																</div>
																<div class="freelance-info">
																	<h3><a href="javascript:void(0);">SM Developer</a></h3>
																	<div class="freelance-location post-now mb-1"><i class="fas fa-clock"></i> Posted 1 week ago</div>
																	<div class="freelance-location"><i class="fas fa-map-marker-alt me-1"></i>Virginia, USA</div>
																</div>
																<div class="freelance-tags">
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design me-1">Web Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design">UI Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design ms-1">Node Js</span></a>
																</div>
																<div class="freelancers-price">$42-$100</div>
															</div>
															<div class="counter-stats">
																<ul>
																	<li>
																		<h5>Expiry</h5>
																		<h3 class="counter-value">2 Days Left</h3>
																	</li>
																	<li>
																		<h5>Proposals</h5>
																		<h3 class="counter-value">15</h3>
																	</li>
																	<li>
																		<h5>Job Type</h5>
																		<h3 class="counter-value"><span class="jobtype">Full Time</span></h3>
																	</li>
																</ul>
															</div>
															</div>
															<div class="cart-hover">
																<router-link to="/project-details" class="btn-cart" tabindex="-1">View Profile</router-link>
															</div>
														</div>
													</div>
													
													<div class="col-md-6 col-lg-12 col-xl-3">
														<div class="freelance-widget widget-author">
															<div class="freelance-content">
															<a data-bs-toggle="modal" href="#rating" class="favourite favourited"><i class="fas fa-star"></i></a>
															<div class="author-heading">
																<div class="profile-img">
																	<router-link to="/project-details">
																		<img src="../../../assets/img/company/img-7.png" alt="author">
																		<span class="project-verified"><i class="fas fa-check-circle"></i></span>
                                                                    </router-link>
																</div>
																<div class="profile-name">
																	<div class="author-location"><router-link to="/project-details">Kind Softwares</router-link> </div>
																</div>
																<div class="freelance-info">
																	<h3><a href="javascript:void(0);">Network Engineer</a></h3>
																	<div class="freelance-location post-now mb-1"><i class="fas fa-clock"></i> Posted 3 weeks ago</div>
																	<div class="freelance-location"><i class="fas fa-map-marker-alt me-1"></i>Delaware, USA</div>
																</div>
																<div class="freelance-tags">
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design me-1">Web Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design">UI Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design ms-1">Node Js</span></a>
																</div>
																<div class="freelancers-price">$12-$320</div>
															</div>
															<div class="counter-stats">
																<ul>
																	<li>
																		<h5>Expiry</h5>
																		<h3 class="counter-value">5 Days Left</h3>
																	</li>
																	<li>
																		<h5>Proposals</h5>
																		<h3 class="counter-value">24</h3>
																	</li>
																	<li>
																		<h5>Job Type</h5>
																		<h3 class="counter-value"><span class="jobtype">Full Time</span></h3>
																	</li>
																</ul>
															</div>
															</div>
															<div class="cart-hover">
																<router-link to="/project-details" class="btn-cart" tabindex="-1">View Profile</router-link>
															</div>
														</div>
													</div>
													
													<div class="col-md-6 col-lg-12 col-xl-3">
														<div class="freelance-widget widget-author">
															<div class="freelance-content">
															<a data-bs-toggle="modal" href="#rating" class="favourite favourited"><i class="fas fa-star"></i></a>
															<div class="author-heading">
																<div class="profile-img">
																	<router-link to="/project-details">
																		<img src="../../../assets/img/company/img-8.png" alt="author">
																		<span class="project-verified"><i class="fas fa-check-circle"></i></span>
                                                                    </router-link>
																</div>
																<div class="profile-name">
																	<div class="author-location"><router-link to="/project-details">Particles INC </router-link></div>
																</div>
																<div class="freelance-info">
																	<h3><a href="javascript:void(0);">Business Analyst</a></h3>
																	<div class="freelance-location post-now mb-1"><i class="fas fa-clock"></i> Posted 1 month ago</div>
																	<div class="freelance-location"><i class="fas fa-map-marker-alt me-1"></i>Kentucky, USA</div>
																</div>
																<div class="freelance-tags">
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design me-1">Web Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design">UI Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design ms-1">Node Js</span></a>
																</div>
																<div class="freelancers-price">$35-$520</div>
															</div>
															<div class="counter-stats">
																<ul>
																	<li>
																		<h5>Expiry</h5>
																		<h3 class="counter-value">4 Days Left</h3>
																	</li>
																	<li>
																		<h5>Proposals</h5>
																		<h3 class="counter-value">15</h3>
																	</li>
																	<li>
																		<h5>Job Type</h5>
																		<h3 class="counter-value"><span class="jobtype">Full Time</span></h3>
																	</li>
																</ul>
															</div>
															</div>
															<div class="cart-hover">
																<router-link to="/project-details" class="btn-cart" tabindex="-1">View Profile</router-link>
															</div>
														</div>
													</div>
													
													<div class="col-md-6 col-lg-12 col-xl-3">
														<div class="freelance-widget widget-author">
															<div class="freelance-content">
															<a data-bs-toggle="modal" href="#rating" class="favourite favourited"><i class="fas fa-star"></i></a>
															<div class="author-heading">
																<div class="profile-img">
																	<router-link to="/project-details">
																		<img src="../../../assets/img/company/img-9.png" alt="author">
																		<span class="project-verified"><i class="fas fa-check-circle"></i></span>
                                                                    </router-link>
																</div>
																<div class="profile-name">
																	<div class="author-location"><router-link to="/project-details">Soft Technologies</router-link> </div>
																</div>
																<div class="freelance-info">
																	<h3><router-link to="/project-details">IT Project Manager</router-link></h3>
																	<div class="freelance-location post-now mb-1"><i class="fas fa-clock"></i> Posted 2 months ago</div>
																	<div class="freelance-location"><i class="fas fa-map-marker-alt me-1"></i>Kansas, USA</div>
																</div>
																<div class="freelance-tags">
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design me-1">Web Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design">UI Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design ms-1">Node Js</span></a>
																</div>
																<div class="freelancers-price">$10-$300</div>
															</div>
															<div class="counter-stats">
																<ul>
																	<li>
																		<h5>Expiry</h5>
																		<h3 class="counter-value">1 Days Left</h3>
																	</li>
																	<li>
																		<h5>Proposals</h5>
																		<h3 class="counter-value">12</h3>
																	</li>
																	<li>
																		<h5>Job Type</h5>
																		<h3 class="counter-value"><span class="jobtype">Full Time</span></h3>
																	</li>
																</ul>
															</div>
															</div>
															<div class="cart-hover">
																<router-link to="/project-details" class="btn-cart" tabindex="-1">View Profile</router-link>
															</div>
														</div>
													</div>
													
													<div class="col-md-6 col-lg-12 col-xl-3">
														<div class="freelance-widget widget-author">
															<div class="freelance-content">
															<a data-bs-toggle="modal" href="#rating" class="favourite favourited"><i class="fas fa-star"></i></a>
															<div class="author-heading">
																<div class="profile-img">
																	<router-link to="/project-details">
																		<img src="../../../assets/img/company/img-10.png" alt="author">
																		<span class="project-verified"><i class="fas fa-check-circle"></i></span>
                                                                    </router-link>
																</div>
																<div class="profile-name">
																	<div class="author-location"><router-link to="/project-details">System Info </router-link></div>
																</div>
																<div class="freelance-info">
																	<h3><a href="javascript:void(0);">Software Architect</a></h3>
																	<div class="freelance-location post-now mb-1"><i class="fas fa-clock"></i> Posted 1 year ago</div>
																	<div class="freelance-location"><i class="fas fa-map-marker-alt me-1"></i>Minnesota, USA</div>
																</div>
																<div class="freelance-tags">
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design me-1">Web Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design">UI Design</span></a>
																	<a href="javascript:void(0);"><span class="badge badge-pill badge-design ms-1">Node Js</span></a>
																</div>
																<div class="freelancers-price">$22-$600</div>
															</div>
															<div class="counter-stats">
																<ul>
																	<li>
																		<h5>Expiry</h5>
																		<h3 class="counter-value">2 Days Left</h3>
																	</li>
																	<li>
																		<h5>Proposals</h5>
																		<h3 class="counter-value">10</h3>
																	</li>
																	<li>
																		<h5>Job Type</h5>
																		<h3 class="counter-value"><span class="jobtype">Full Time</span></h3>
																	</li>
																</ul>
															</div>
															</div>
															<div class="cart-hover">
																<router-link to="/project-details" class="btn-cart" tabindex="-1">View Profile</router-link>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							<!-- project list -->
							
						</div>
					</div>
				</div>
			</div>					
			<!-- /Page Content -->
           
            <!-- Footer -->
                <layout-footer />
            <!-- /Footer -->
        </div>
        <!-- /Main Wrapper -->
        <employeemodal></employeemodal>
        </div>
</template>
<script>
	export default {
		 mounted() {
		},
        computed: {
            currentPath() {
                return this.$route.name;
            }
    
        },  
        data() {
        return {
          activeClass: 'active',
        };
                //  isactive : true
      },
	}
	</script>

// template-react/src/frontend/components/foremployers/favourites/index.jsx
import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import StickyBox from "react-sticky-box";
import { Flags_us, Flags_de, Img_01, Img_02, Img_03, Img_04, Img_05, home_icon } from "../../imagepath";
import { Sidebar } from '../sidebar';

const Favourites = (props) => {
  useEffect(() => {
    document.body.className = 'dashboard-page';
    return () => { document.body.className = ''; }
  });
  return (
    <>
      {/* Breadcrumb */}
      <div className="bread-crumb-bar">
        <div className="container">
          <div className="row align-items-center inner-banner">
            <div className="col-md-12 col-12 text-center">
              <div className="breadcrumb-list">
                <nav aria-label="breadcrumb" className="page-breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item"><Link to="#"><img src={home_icon} alt="Post Author" /> Home</Link></li>
                    <li className="breadcrumb-item" aria-current="page">Employee</li>
                    <li className="breadcrumb-item" aria-current="page">Favourites</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Breadcrumb */}
      {/* Page Content */}
      <div className="content bookmark content-page">
        <div className="container-fluid">
          <div className="row">
            {/* sidebar */}
            <div className="col-xl-3 col-md-4 theiaStickySidebar">
              <StickyBox offsetTop={20} offsetBottom={20}>
                <Sidebar />
              </StickyBox>
            </div>
            {/* /sidebar */}
            <div className="col-xl-9 col-md-8">
              <nav className="user-tabs mb-4">
                <ul className="nav nav-tabs nav-tabs-bottom nav-justified">
                  <li className="nav-item">
                    <Link className="nav-link active" to="/favourites">
                      Bookmarked Freelancers
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/invited-freelancer">
                      Invited Freelancers
                    </Link>
                  </li>
                </ul>
              </nav>
              {/* project list */}
              <div className="my-projects-view">
                <div className="row">
                  <div className="col-lg-12">
                    <div className="card">
                      <div className="card-header">
                        <h5 className="card-title">Bookmarked Freelancers</h5>
                      </div>
                      <div className="card-body">
                        <div className="table-responsive table-box">
                          <table className="table table-hover table-center mb-0 datatable">
                            <thead className="thead-pink">
                              <tr>
                                <th>Freelancer Detail</th>
                                <th>Hourly Rate</th>
                                <th>Projects Completed</th>
                                <th>Location</th>
                                <th>Status</th>
                                <th />
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <td>
                                  <h2 className="table-avatar">
                                    <Link
                                      to="/freelancer-profile"
                                      className="avatar avatar-md tab-imgcircle me-2"
                                    >
                                      <img
                                        className="avatar-img rounded-circle"
                                        src={Img_02}
                                        alt="User Image"
                                      />
                                    </Link>
                                    <Link to="/freelancer-profile">
                                      <span className="profile-name">
                                        Andrew Glover
                                      </span>
                                      <span>Software Developer</span>
                                      <span className="rating mt-2">
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star" />
                                      </span>
                                    </Link>
                                  </h2>
                                </td>
                                <td>300 /Hr</td>
                                <td>40</td>
                                <td>
                                  <h2 className="table-avatar">
                                    <img
                                      src={Flags_de}
                                      className="me-2"
                                      alt=""
                                      height={16}
                                    />{" "}
                                    Germany
                                  </h2>
                                </td>
                                <td>
                                  <a href="" className="fav">
                                    <i className="fas fa-heart filled" />
                                  </a>
                                </td>
                                <td className="text-end">
                                  <div className="table-action">
                                    <a
                                      data-bs-toggle="modal"
                                      href="#bookmark"
                                      className="btn btn-primary btn-invite"
                                    >
                                      Invite Project
                                    </a>
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  <h2 className="table-avatar">
                                    <Link
                                      to="/freelancer-profile"
                                      className="avatar avatar-md tab-imgcircle me-2"
                                    >
                                      <img
                                        className="avatar-img rounded-circle"
                                        src={Img_03}
                                        alt="User Image"
                                      />
                                    </Link>
                                    <Link to="/freelancer-profile">
                                      <span className="profile-name">
                                        Mickey Bernier
                                      </span>{" "}
                                      <span>QA Engineer</span>
                                      <span className="rating mt-2">
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star" />
                                      </span>
                                    </Link>
                                  </h2>
                                </td>
                                <td>150 /Hr</td>
                                <td>20</td>
                                <td>
                                  <h2 className="table-avatar">
                                    <img
                                      src={Flags_us}
                                      className="me-2"
                                      alt=""
                                      height={16}
                                    />{" "}
                                    USA
                                  </h2>
                                </td>
                                <td>
                                  <a href="" className="fav">
                                    <i className="far fa-heart" />
                                  </a>
                                </td>
                                <td className="text-end">
                                  <div className="table-action">
                                    <a
                                      data-bs-toggle="modal"
                                      href="#bookmark"
                                      className="btn btn-primary btn-invite"
                                    >
                                      Invite Project
                                    </a>
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  <h2 className="table-avatar">
                                    <Link
                                      to="/freelancer-profile"
                                      className="avatar avatar-md tab-imgcircle me-2"
                                    >
                                      <img
                                        className="avatar-img rounded-circle"
                                        src={Img_04}
                                        alt="User Image"
                                      />
                                    </Link>
                                    <Link to="freelancer-profile">
                                      <span className="profile-name">
                                        Tony Ingle
                                      </span>{" "}
                                      <span>Business Analyst</span>
                                      <span className="rating mt-2">
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star" />
                                      </span>
                                    </Link>
                                  </h2>
                                </td>
                                <td>220 /Hr</td>
                                <td>35</td>
                                <td>
                                  <h2 className="table-avatar">
                                    <img
                                      src={Flags_de}
                                      className="me-2"
                                      alt=""
                                      height={16}
                                    />{" "}
                                    Germany
                                  </h2>
                                </td>
                                <td>
                                  <a href="" className="fav">
                                    <i className="fas fa-heart filled" />
                                  </a>
                                </td>
                                <td className="text-end">
                                  <div className="table-action">
                                    <a
                                      data-bs-toggle="modal"
                                      href="#bookmark"
                                      className="btn btn-primary btn-invite"
                                    >
                                      Invite Project
                                    </a>
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  <h2 className="table-avatar">
                                    <Link
                                      to="/freelancer-profile"
                                      className="avatar avatar-md tab-imgcircle me-2"
                                    >
                                      <img
                                        className="avatar-img rounded-circle"
                                        src={Img_05}
                                        alt="User Image"
                                      />
                                    </Link>
                                    <Link to="/freelancer-profile">
                                      <span className="profile-name">
                                        Timothy Smith
                                      </span>{" "}
                                      <span>PHP Developer</span>
                                      <span className="rating mt-2">
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star" />
                                      </span>
                                    </Link>
                                  </h2>
                                </td>
                                <td>420 /Hr</td>
                                <td>60</td>
                                <td>
                                  <h2 className="table-avatar">
                                    <img
                                      src={Flags_us}
                                      className="me-2"
                                      alt=""
                                      height={16}
                                    />{" "}
                                    USA
                                  </h2>
                                </td>
                                <td>
                                  <a href="" className="fav">
                                    <i className="far fa-heart" />
                                  </a>
                                </td>
                                <td className="text-end">
                                  <div className="table-action">
                                    <a
                                      data-bs-toggle="modal"
                                      href="#bookmark"
                                      className="btn btn-primary btn-invite"
                                    >
                                      Invite Project
                                    </a>
                                  </div>
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  <h2 className="table-avatar">
                                    <Link
                                      to="/freelancer-profile"
                                      className="avatar avatar-md tab-imgcircle me-2"
                                    >
                                      <img
                                        className="avatar-img rounded-circle"
                                        src={Img_01}
                                        alt="User Image"
                                      />
                                    </Link>
                                    <Link to="freelancer-profile">
                                      <span className="profile-name">
                                        David Peterson
                                      </span>{" "}
                                      <span>UI/UX Designer</span>
                                      <span className="rating mt-2">
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star filled" />
                                        <i className="fas fa-star" />
                                      </span>
                                    </Link>
                                  </h2>
                                </td>
                                <td>200 /Hr</td>
                                <td>25</td>
                                <td>
                                  <h2 className="table-avatar">
                                    <img
                                      src={Flags_de}
                                      className="me-2"
                                      alt=""
                                      height={16}
                                    />{" "}
                                    Germany
                                  </h2>
                                </td>
                                <td>
                                  <a href="" className="fav">
                                    <i className="far fa-heart" />
                                  </a>
                                </td>
                                <td className="text-end">
                                  <div className="table-action">
                                    <a
                                      data-bs-toggle="modal"
                                      href="#bookmark"
                                      className="btn btn-primary btn-invite"
                                    >
                                      Invite Project
                                    </a>
                                  </div>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {/* project list */}
            </div>
          </div>
        </div>
      </div>
      {/* /Page Content */}
      {/* The Modal */}
      <div className="modal fade" id="bookmark">
        <div className="modal-dialog modal-dialog-centered modal-md">
          <div className="modal-content">
            <div className="modal-header">
              <h4 className="modal-title">INVITE FREELANCER</h4>
              <span className="modal-close">
                <a href="#" data-bs-dismiss="modal" aria-label="Close">
                  <i className="far fa-times-circle orange-text" />
                </a>
              </span>
            </div>
            <div className="modal-body">
              <form>
                <div className="modal-info">
                  <div className="row">
                    <div className="col-md-12">
                      <div className="average-bids mb-4">
                        <p>
                          Contact <span className="text-highlight">John Doe </span>{" "}
                          about your Project
                        </p>
                      </div>
                      <div className="form-group">
                        <label>Invite title</label>
                        <input type="text" className="form-control" />
                      </div>
                    </div>
                    <div className="col-md-12">
                      <div className="form-group">
                        <label>Send a private message</label>
                        <textarea
                          className="form-control"
                          rows={5}
                          defaultValue={
                            "Hi  John Doe, I noticed your profile and would like to offer you my project. We can discuss any details over chat."
                          }
                        />
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="form-group">
                        <label>Hire for</label>
                        <div className="radio">
                          <label className="custom_radio me-2">
                            <input type="radio" defaultValue="fix" defaultChecked />
                            <span className="checkmark" /> Fixed Price
                          </label>
                          <label className="custom_radio">
                            <input type="radio" defaultValue="fix" />
                            <span className="checkmark" /> Hourly Rate
                          </label>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="form-group">
                        <label>Hire for</label>
                        <div className="radio">
                          <label className="custom_radio me-2">
                            <input
                              type="radio"
                              defaultValue="rate"
                              defaultChecked
                            />
                            <span className="checkmark" /> Fixed Price
                          </label>
                          <label className="custom_radio">
                            <input type="radio" defaultValue="rate" />
                            <span className="checkmark" /> Hourly Rate
                          </label>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="form-group">
                        <label>Budget</label>
                        <div className="form-row">
                          <div className="col-7">
                            <div className="input-group">
                              <div className="input-group-prepend bg-pink d-flex">
                                <span
                                  className="input-group-text"
                                  id="basic-addon1"
                                >
                                  $
                                </span>
                              </div>
                              <input
                                type="text"
                                className="form-control"
                                placeholder={20.0}
                              />
                            </div>
                          </div>
                          <div className="col-5">
                            <select className="form-control select">
                              <option value={0}>USD</option>
                              <option value={0}>USD</option>
                            </select>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="form-group">
                        <label>Budget</label>
                        <div className="form-row">
                          <div className="col-sm-7">
                            <div className="input-group form-inline mb-2">
                              <div className="input-group-prepend bg-pink d-flex">
                                <span className="input-group-text" id="basic-add">
                                  $
                                </span>
                              </div>
                              <input
                                type="text"
                                className="form-control me-1"
                                placeholder={20.0}
                              />
                              <label className="invited-freelancer-label">
                                / hr
                              </label>
                            </div>
                          </div>
                          <div className="col-sm-5">
                            <select className="form-control select form-select">
                              <option value={0}>USD</option>
                              <option value={0}>USD</option>
                            </select>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-12">
                      <div className="form-group">
                        <label>Project</label>
                        <select className="form-control select form-select">
                          <option value={0}>
                            3D Renders and Amazon Product Store images/Video
                          </option>
                          <option value={0}>
                            3D Renders and Amazon Product Store Video
                          </option>
                          <option value={0}>
                            3D Renders and Amazon Product Store images
                          </option>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="submit-section text-end">
                  <button type="submit" className="btn btn-primary submit-btn">
                    Send Invite
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      {/* /The Modal */}
    </>
  )

}
export default Favourites;
