// template-vuejs/src/views/frontend/freelancer/header.vue
<template>
    <header class="header header-bg">
        <nav class="navbar navbar-expand-lg header-nav">
            <div class="navbar-header">
                <a id="mobile_btn" href="javascript:void(0);">
                    <span class="bar-icon">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </a>
                <router-link to="/index" class="navbar-brand logo">
                    <img src="../../../assets/img/logo.png" class="img-fluid" alt="Logo">
                </router-link>
            </div>
            <div class="main-menu-wrapper">
                <div class="menu-header">
                    <router-link to="/index" class="menu-logo">
                        <img src="../../../assets/img/logo.png" class="img-fluid" alt="Logo">
                    </router-link>
                    <a id="menu_close" class="menu-close" href="javascript:void(0);">
                        <i class="fas fa-times"></i>
                    </a>
                </div>
                <ul class="main-nav">
                    <li class="has-submenu" :class="homeMenu ? 'active' : 'notactive'">
                        <a>Home <i class="fas fa-chevron-down"></i></a>
                        <ul class="submenu">
                            <li :class="currentPath == '/index' ? 'active' : 'notactive'"><router-link to="/index">Home</router-link></li>
                            <li :class="currentPath == 'index-two' ? 'active' : 'notactive'"><router-link to="/index-two">Home 2</router-link></li>
                            <li :class="currentPath == 'index-three' ? 'active' : 'notactive'"><router-link to="/index-three">Home 3</router-link></li>
                            <li :class="currentPath == 'index-four' ? 'active' : 'notactive'"><router-link to="/index-four">Home 4</router-link></li>
                            <li :class="currentPath == 'index-five' ? 'active' : 'notactive'"><router-link to="/index-five">Home 5</router-link></li>
                        </ul>
                    </li>
                    <li class="has-submenu" :class="patientsMenu ? 'active' : 'notactive'">
                        <a href="">For Employers<i class="fas fa-chevron-down"></i></a>
                        <ul class="submenu">
                            <li class="has-submenu" :class="currentPath == 'developer' ? 'active' : 'notactive'">
                                <a href="javascript:void(0);">Freelancer</a>
                                <ul class="submenu">
                                    <li :class="currentPath == 'developer' ? 'active' : 'notactive'"><router-link to="/developer">Freelancer</router-link></li>
                                    <li><router-link to="/developer-details">Freelancer Details</router-link></li>
                                </ul>
                            </li>
                            <li :class="currentPath == 'dashboard' ? 'active' : 'notactive'"><router-link to="/dashboard">Dashboard</router-link></li>	
                            <li :class="currentPath == 'company-profile' ? 'active' : 'notactive'"><router-link to="/company-profile">My Profile</router-link></li>	
                            <li :class="currentPath == 'company-details' ? 'active' : 'notactive'"><router-link to="/company-details">Company Details</router-link></li>	
                            <li :class="currentPath == 'manage-projects' || currentPath == 'cancelled-projects' || currentPath == 'completed-projects' ? 'active' : 'notactive'"><router-link to="/manage-projects">Projects</router-link></li>
                            <li :class="currentPath == 'favourites' || currentPath == 'favourites-list' ? 'active' : 'notactive'"><router-link to="/favourites">Favourites</router-link></li>
                            <li :class="currentPath == 'membership-plans' ? 'active' : 'notactive'"><router-link to="/membership-plans">Membership</router-link></li>
                            <li :class="currentPath == 'milestones' || currentPath == 'change-password' ? 'active' : 'notactive'"><router-link to="/milestones">Milestones</router-link></li>
                            <li :class="currentPath == 'chats' ? 'active' : 'notactive'"><router-link to="/chats">Chats</router-link></li>
                            <li :class="currentPath == 'review' ? 'active' : 'notactive'"><router-link to="/review">Review</router-link></li>			
                            <li :class="currentPath == 'deposit-funds' ? 'active' : 'notactive'"><router-link to="/deposit-funds">Payments</router-link></li>							
                            <li :class="currentPath == 'verify-identity' ? 'active' : 'notactive'"><router-link to="/verify-identity">Verify Identity</router-link></li>								
                            <li :class="currentPath == 'profile-settings' || currentPath == 'delete-account' ? 'active' : 'notactive'"><router-link to="/profile-settings"  :class="currentPath == 'profile-settings' || currentPath == 'delete-account' ? 'active' : 'notactive'">Settings</router-link></li>
                        </ul>
                    </li>
                    <li class="has-submenu" :class="freelancerMenu ? 'active' : 'notactive'">
                        <a href="">For Freelancer<i class="fas fa-chevron-down"></i></a>
                        <ul class="submenu">
                            <li class="has-submenu" :class="currentPath == 'project' || currentPath == 'project-details' ? 'active' : 'notactive'">
                                <a href="javascript:void(0);">Projects</a>
                                <ul class="submenu">
                                    <li :class="currentPath == 'project' ? 'active' : 'notactive'"><router-link to="/project">Projects</router-link></li>
                                    <li :class="currentPath == 'project-details' ? 'active' : 'notactive'"><router-link to="/project-details">Project Details</router-link></li>
                                </ul>
                            </li>
                            <li :class="currentPath == 'freelancer-dashboard' ? 'active' : 'notactive'"><router-link to="/freelancer-dashboard">Dashboard</router-link></li>
                            <li :class="currentPath == 'developer-profile' || currentPath == 'freelancer-profile' ? 'active' : 'notactive'"><router-link to="/developer-profile">My Profile</router-link></li>	
                            <li :class="currentPath == 'developer-details' ? 'active' : 'notactive'"><router-link to="/developer-details">Freelancer Details</router-link></li>
                            <li :class="currentPath == 'freelancer-invitations' || currentPath == 'freelancer-project-proposals' || currentPath == 'freelancer-cancelled-projects' || currentPath == 'freelancer-completed-projects' || currentPath == 'freelancer-ongoing-projects' ? 'active' : 'notactive'"><router-link to="/freelancer-project-proposals">Projects</router-link></li>
                            <li :class="currentPath == 'freelancer-favourites' ? 'active' : 'notactive'"><router-link to="/freelancer-favourites">Favourites</router-link></li>
                            <li :class="currentPath == 'freelancer-membership' ? 'active' : 'notactive'"><router-link to="/freelancer-membership">Membership</router-link></li>
                            <li :class="currentPath == 'freelancer-change-password' ? 'active' : 'notactive'"><router-link to="/freelancer-change-password">Change Password</router-link></li>
                            <li :class="currentPath == 'freelancer-chats' ? 'active' : 'notactive'"><router-link to="/freelancer-chats">Chats</router-link></li>
                            <li :class="currentPath == 'freelancer-review' ? 'active' : 'notactive'"><router-link to="/freelancer-review">Review</router-link></li>			
                            <li :class="currentPath == 'freelancer-withdraw-money' || currentPath == 'freelancer-portfolio' || currentPath == 'freelancer-transaction-history' ? 'active' : 'notactive'"><router-link to="/freelancer-withdraw-money">Payments</router-link></li>							
                            <li :class="currentPath == 'freelancer-verify-identity' ? 'active' : 'notactive'"><router-link to="/freelancer-verify-identity">Verify Identity</router-link></li>				
                            <li :class="currentPath == 'freelancer-profile-settings' || currentPath == 'freelancer-delete-account' ? 'active' : 'notactive'"><router-link to="/freelancer-profile-settings">Settings</router-link></li>				
                        </ul>
                    </li>
                    <li class="has-submenu" :class="pagesMenu ? 'active' : 'notactive'">
                        <a href="">Pages <i class="fas fa-chevron-down"></i></a>
                        <ul class="submenu">
                            <li :class="currentPath == 'about' ? 'active' : 'notactive'"><router-link to="/about">About us</router-link></li>
                            <li :class="currentPath == 'blank-page' ? 'active' : 'notactive'"><router-link to="/blank-page">Starter Page</router-link></li>
                            <li :class="currentPath == '404-page' ? 'active' : 'notactive'"><router-link to="/404-page">404 Page</router-link></li>
                            <li class="has-submenu" :class="currentPath == 'freelancer-invoices' || currentPath == 'view-invoice' ? 'active' : 'notactive'">
                                <a>Invoices</a>
                                <ul class="submenu">
                                    <li :class="currentPath == 'freelancer-invoices' ? 'active' : 'notactive'"><router-link to="/freelancer-invoices">Invoices</router-link></li>
                                    <li :class="currentPath == 'view-invoice' ? 'active' : 'notactive'"><router-link to="/view-invoice">Invoice View</router-link></li>
                                </ul>
                            </li>
                            <li :class="currentPath == 'login' ? 'active' : 'notactive'"><router-link to="/login">Login</router-link></li>
                            <li :class="currentPath == 'register' ? 'active' : 'notactive'"><router-link to="/register">Register</router-link></li>
                            <li :class="currentPath == 'onboard-screen' ? 'active' : 'notactive'"><router-link to="/onboard-screen">Onboard Screen</router-link></li>
                            <li :class="currentPath == 'forgot-password' ? 'active' : 'notactive'"><router-link to="/forgot-password">Forgot Password</router-link></li>
                            <li><router-link to="/change-password">Change Password</router-link></li>									
                        </ul>
                    </li>
                    <li class="has-submenu" :class="BlogMenu ? 'active' : 'notactive'">
                        <a href="">Blog <i class="fas fa-chevron-down"></i></a>
                        <ul class="submenu">
                            <li :class="currentPath == 'blog-list' ? 'active' : 'notactive'"><router-link to="/blog-list">Blog List</router-link></li>
                            <li :class="currentPath == 'blog-grid' ? 'active' : 'notactive'"><router-link to="/blog-grid">Blog Grid</router-link></li>
                            <li :class="currentPath == 'blog-details' ? 'active' : 'notactive'"><router-link to="/blog-details">Blog Details</router-link></li>
                        </ul>
                    </li>
                    <li>
                        <router-link to="/admin/login" target="_blank">Admin</router-link>
                    </li>
                </ul>
            </div>		 
            <ul class="nav header-navbar-rht">	
                <li class="nav-item dropdown account-item">
                    <a href="javascript:void(0);" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                        <span class="user-img">
                            <img src="../../../assets/img/user/avatar-1.jpg" alt="">
                        </span>
                        <span>George</span>
                    </a>
                    <div class="dropdown-menu emp">
                        <div class="drop-head">Account Details</div>	
                        <router-link class="dropdown-item" to="/freelancer-profile"><i class="material-icons">verified_user</i> View profile</router-link>
                        <div class="drop-head">Projects Settings</div>	
                        <router-link class="dropdown-item" to="/freelancer-project-proposals"><i class="material-icons">business_center</i> Projects</router-link>
                        <router-link class="dropdown-item" to="/freelancer-bookmarks"><i class="material-icons">local_play</i> Bookmarks</router-link>
                        <router-link class="dropdown-item" to="/freelancer-review"><i class="material-icons">pie_chart</i> Reviews</router-link>
                        <div class="drop-head">Financial Settings</div>
                        <a class="dropdown-item bal" href="javascript:void(0);">Balance <span class="amt">₹0.00 INR</span></a>
                        <router-link class="dropdown-item" to="/freelancer-withdraw-money"><i class="material-icons">wifi_tethering</i> Withdraw funds</router-link>
                        <div class="drop-head">Account Details</div>
                        <router-link class="dropdown-item" to="/freelancer-profile-settings"> <i class="material-icons">settings</i> Profile Settings</router-link>
                        <router-link class="dropdown-item" to="/"><i class="material-icons">power_settings_new</i> Logout</router-link>
                    </div>
                </li>
                <li><router-link to="/post-project" class="login-btn">Post a Project </router-link></li>
            </ul>
        </nav>
    </header>

</template>

<script>

export default {
    mounted() {
        $(window).on('scroll', function () {
		var scroll = $(window).scrollTop();
		if (scroll < 100) {
			$(".header").removeClass("sticky");
		} else {
			$(".header").addClass("sticky");
		}
	});
        // Search Bar
    
    $(document).ready(function() {
        $(".searchbar .fa-search").click(function() {
            $(".togglesearch").toggle();
            $(".top-search").focus();
        });
    });
        // Sticky Menu
    
    $(window).scroll(function(){
        var scroll = $(window).scrollTop();
            if (scroll > 70) {
                $(".min-header").addClass("sticky");
            }
            else{
                $(".min-header").removeClass("sticky");     
            }
    })

        $('.main-nav a').on('click', function(e) {
			if($(this).parent().hasClass('has-submenu')) {
				e.preventDefault();
			}
			if(!$(this).hasClass('submenu')) {
				$('ul', $(this).parents('ul:first')).slideUp(350);
				$('a', $(this).parents('ul:first')).removeClass('submenu');
				$(this).next('ul').slideDown(350);
				$(this).addClass('submenu');
			} else if($(this).hasClass('submenu')) {
				$(this).removeClass('submenu');
				$(this).next('ul').slideUp(350);
			}
		});

        $(document).on('click', '#mobile_btn', function() {
            $('main-wrapper').toggleClass('slide-nav');
            $('.sidebar-overlay').toggleClass('opened');
            $('html').addClass('menu-opened');
            return false;
	    });
	
        $(document).on('click', '.sidebar-overlay', function() {
            $('html').removeClass('menu-opened');
            $(this).removeClass('opened');
            $('main-wrapper').removeClass('slide-nav');
        });
        $('.main-nav > li .submenu li.sub-menu').on('click', function(e) {
			$('html').removeClass('menu-opened');
			$('.sidebar-overlay').removeClass('opened');
			$('main-wrapper').removeClass('slide-nav');
		});
		$('.main-nav li .home-nav').click(function(){
            $("html").removeClass('menu-opened');         
            $(".sidebar-overlay").removeClass('opened');
        }); 
        $(".categories_title").on("click", function() {
            $(this).toggleClass('active');
            $('.categories_menu_toggle').slideToggle('medium');
        });
        $(document).on('click', '#menu_close', function() {
            $('html').removeClass('menu-opened');
            $('.sidebar-overlay').removeClass('opened');
            $('main-wrapper').removeClass('slide-nav');
        });
    },
    computed: {
       currentPath() {
           return this.$route.name
       },
       homeMenu() {
           return this.$route.name == 'index' || this.$route.name == 'index-two' || this.$route.name == 'index-three' || this.$route.name == 'index-four' || this.$route.name == 'index-five';
       },
       patientsMenu() {
           return this.$route.name == 'favourites-list' ||this.$route.name == 'delete-account' || this.$route.name == 'completed-projects' || this.$route.name == 'change-password' || this.$route.name == 'cancelled-projects' || this.$route.name == 'developer' || this.$route.name == 'withdraw-money' || this.$route.name == 'view-project-detail' || this.$route.name == 'transaction-history' || this.$route.name == 'project-tasks' || this.$route.name == 'project-proposals'  || this.$route.name == 'project-payment' || this.$route.name == 'pending-projects' || this.$route.name == 'ongoing-projects' || this.$route.name == 'invited-freelancer' || this.$route.name == 'files' || this.$route.name == 'completed-projects' || this.$route.name == 'cancelled-projects' || this.$route.name == 'dashboard'  || this.$route.name == 'manage-projects'     || this.$route.name == 'favourites'     || this.$route.name == 'membership-plans'     || this.$route.name == 'milestones'    || this.$route.name == 'chats'    || this.$route.name == 'review'    || this.$route.name == 'deposit-funds'    || this.$route.name == 'verify-identity'    || this.$route.name == 'profile-settings';
       },
       freelancerMenu() {
           return this.$route.name == 'freelancer-invitations' || this.$route.name == 'freelancer-transaction-history' || this.$route.name == 'freelancer-profile' || this.$route.name == 'freelancer-portfolio' || this.$route.name == 'freelancer-ongoing-projects' || this.$route.name == 'freelancer-delete-account' || this.$route.name == 'freelancer-completed-projects' || this.$route.name == 'freelancer-cancelled-projects' || this.$route.name == 'developer-profile' || this.$route.name == 'developer-details' || this.$route.name == 'project' || this.$route.name == 'freelancer-cancelled-projects' || this.$route.name == 'project-details'   || this.$route.name == 'freelancer-dashboard'        || this.$route.name == 'freelancer-project-proposals'     || this.$route.name == 'freelancer-favourites'     || this.$route.name == 'freelancer-membership'     || this.$route.name == 'freelancer-change-password'     || this.$route.name == 'freelancer-chats'     || this.$route.name == 'freelancer-review'     || this.$route.name == 'freelancer-withdraw-money'     || this.$route.name == 'freelancer-verify-identity'    || this.$route.name == 'freelancer-profile-settings';
       },
       pagesMenu() {
           return this.$route.name == 'freelancer-invoices' || this.$route.name == 'about' || this.$route.name == 'blank-page'    || this.$route.name == '404-page'   || this.$route.name == 'user-account-details'        || this.$route.name == 'login'     || this.$route.name == 'register'     || this.$route.name == 'forgot-password';
       },
       BlogMenu() {
           return this.$route.name == 'blog-list' || this.$route.name == 'blog-grid'   || this.$route.name == 'blog-details';
       },
   },
}
</script>

// template-react/src/frontend/components/header/index.jsx
import React, { useEffect, useState,useRef } from "react";
import { Link } from "react-router-dom";
import { Logo,Img_04, avatar_1,} from '../imagepath';
import config from "config";


const Header = (props) => {
  
  const [isSideMenu, setSideMenu] = useState("");
  const [isSideMenu1, setSideMenu1] = useState("");
  const [isSideMenu2, setSideMenu2] = useState("");
  const [isSideMenu3, setSideMenu3] = useState("");

  const toggleSidebar = (value) => {
  setSideMenu(value)  
  }
  const toggleSidebar1 = (value) => {
  setSideMenu1(value)
  }
  const toggleSidebar2 = (value) => {
  setSideMenu2(value)
  }
  const toggleSidebar3 = (value) => {
  setSideMenu3(value)
  }
const onHandleMobileMenu = () => {
  var root = document.getElementsByTagName("html")[0];
  root.classList.add("menu-opened");
};

const onhandleCloseMenu = () => {
  var root = document.getElementsByTagName("html")[0];
  root.classList.remove("menu-opened");
};

  


    const pathname = props.location.pathname.split("/")[1];

    const exclusionArray = [
      "/onboardScreen",
      "/onboard-screen-employer"
    ];

    if (exclusionArray.indexOf(props.location.pathname) >= 0) {
      return "";
    }
    console.log(props.location,"location")

  //nav transparent

  const [click, setClick] =useState (false);
  const [button, setButton] =useState (true);
  const [navbar,setNavbar] =useState (false);

  const showButton =()=> {
    if (window.innerWidth <= 960) {
      setButton (false);
    }else {
      setButton(true);
    }
  };
  const Reload=()=>{
    window.location.reload(false);
}

  useEffect ( ()=>{
    showButton();
  }, []);
window.addEventListener('resize',showButton);

const changeBackground =()=> {
  if (window.scrollY >=95) {
    setNavbar (true);
  } else {
    setNavbar (false);
  }
}
window.addEventListener('scroll',changeBackground);
    return (
      <>
      
      {/* Header */}
      { (!props.location.pathname.includes("/index-two") && !props.location.pathname.includes("/index-three") && !props.location.pathname.includes("/index-four") && !props.location.pathname.includes("/index-five")) && 
      <header className={`header ${navbar? 'sticky': ''} header-bg`}> 
        <nav className="navbar navbar-expand-lg header-nav">
          <div className="navbar-header">
            <Link id="mobile_btn" to="#" onClick={() => onHandleMobileMenu()}>
              <span className="bar-icon">
                <span />
                <span />
                <span />
              </span>
            </Link>
            <Link to="/" className="navbar-brand logo">
              <img src={Logo} className="img-fluid" alt="Logo" />
            </Link>
          </div>
          <div className="main-menu-wrapper">
            <div className="menu-header">
              <Link to="/" className="menu-logo">
                <img src={Logo} className="img-fluid" alt="Logo" />
              </Link>
              <Link id="menu_close" className="menu-close" to="#"  onClick={() => onhandleCloseMenu()}>
                <i className="fas fa-times" />
              </Link>
            </div>
            <ul className="main-nav">
            <li className={`has-submenu ${pathname.includes("index") || pathname.includes("index-two") || pathname.includes("index-three") || pathname.includes("index-four")|| pathname.includes("index-five")  ? "active" : ""}`}>
            <Link to="#0" className={isSideMenu === "home" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu ==="home" ? "": "home")}  >Home <i className="fas fa-chevron-down" /></Link>
                  { isSideMenu === "home" ? 
								<ul className="submenu">
									<li className="active"><Link to="/">Home</Link></li>
									<li><Link to="/index-two">Home 2</Link></li>
									<li><Link to="/index-three">Home 3</Link></li>
									<li><Link to="/index-four">Home 4</Link></li>
									<li><Link to="/index-five">Home 5</Link></li>
								</ul>
                :""
              }
							</li>
        
              <li  className={`has-submenu ${pathname === "developer" || pathname === "company-profile" || pathname === "developer-details" || pathname ==="company-project" || pathname ==="company-gallery" || pathname ==="company-review" || pathname === "company-details" || pathname === "dashboard" ||
                          pathname === "manage-projects" || pathname === "favourites" || pathname === "invited-freelancer" || pathname === "membership-plans" || 
                          pathname === "milestones" || pathname === "chats" || pathname === "review" || pathname === "deposit-funds" ||
                          pathname === "withdraw-money"||pathname === "transaction-history" || pathname === "verify-identity" || 
                          pathname === "profile-settings"|| pathname === "tasks" || pathname === "files"||
                          pathname==="view-project-detail" ||pathname === "project-payment" ? "active" : ""}`}>
               <Link to="#" className={isSideMenu === "foremployers" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu ==="foremployers" ? "": "foremployers")} > For Employers<i className="fas fa-chevron-down" /></Link>              
                  { isSideMenu === "foremployers" ?    
               
                <ul className="submenu">
                  <li className={`has-submenu ${pathname === "developer" || pathname === "developer-details" ? "active" : ""}`}>
                    <Link to="#" onClick={()=> toggleSidebar1(isSideMenu1 ==="freelancer" ? "": "freelancer")}>Freelancer</Link>
                    { isSideMenu1 === "freelancer" ?   
                    <ul className="submenu">
                      <li className={pathname === "developer" ? "active" : ""}>
                        <Link to="/developer">Freelancer</Link>
                      </li>
                      <li className={pathname === "developer-details" ? "active" : ""}>
                        <Link to="/developer-details">Freelancer Details</Link>
                      </li>
                    </ul>
                   :""
                  }
                  </li>
                  <li className={pathname === "dashboard" ? "active" : ""}>
                    <Link to="/dashboard">Dashboard</Link>
                  </li>
                  <li className={pathname === "company-profile" ? "active" : ""}>
                      <Link to="/company-profile">My Profile</Link>
                    </li>
                    <li className={pathname === "company-details" ? "active" : ""}>
                      <Link to="/company-details">Company Details</Link>
                    </li>
                  <li className={pathname === "manage-projects" ? "active" : ""}>
                    <Link to="/manage-projects">Projects</Link>
                  </li>
                  <li className={pathname === "favourites" || pathname === "invited-freelancer" ? "active" : ""}>
                    <Link to="/favourites">Favourites</Link>
                  </li>
                  <li className={pathname === "membership-plans" ? "active" : ""}>
                    <Link to="/membership-plans">Membership</Link>
                  </li>
                  <li className={pathname==="view-project-detail" || pathname === "milestones" || pathname === "tasks" || pathname === "files"||
                  pathname === "project-payment" ? "active" : ""}>
                    <Link to="/milestones">Milestones</Link>
                  </li>
                  <li className={pathname === "chats" ? "active" : ""}>
                    <Link to="/chats">Chats</Link>
                  </li>
                  <li className={pathname === "review" ? "active" : ""}>
                    <Link to="/review">Review</Link>
                  </li>
                  <li className={pathname === "deposit-funds" ||pathname === "withdraw-money"||pathname === "transaction-history" ? "active" : ""}>
                    <Link to="/deposit-funds">Payments</Link>
                  </li>
                  <li className={pathname === "verify-identity" ? "active" : ""}>
                    <Link to="/verify-identity">Verify Identity</Link>
                  </li>
                  <li className={pathname === "profile-settings" ? "active" : ""}>
                    <Link to="/profile-settings">Settings</Link>
                  </li>
                </ul>
                  :""
                }
              </li>
              <li className={`has-submenu ${pathname === "project" || pathname === "developer-profile" || pathname === "project-details" || pathname === "freelancer-dashboard" || pathname === "freelancer-details" || pathname === "company-profile" ||
              pathname === "freelancer-project-proposals" || pathname === "freelancer-favourites"|| pathname === "freelancer-invitations" || pathname === "freelancer-membership" || 
              pathname === "freelancer-change-password" || pathname === "freelancer-chats" || pathname === "freelancer-review" || 
              pathname === "freelancer-completed-projects" || pathname === "freelancer-cancelled-projects" ||
              pathname === "freelancer-withdraw-money" || pathname === "freelancer-verify-identity" || pathname === "freelancer-ongoing-projects" ||
              pathname === "freelancer-profile-settings"|| pathname === "freelancer-transaction-history" || 
              pathname === "freelancer-project-proposals" || pathname === "freelancer-view-project-detail" || pathname === "freelancer-milestones"
                   || pathname === "freelancer-task" || pathname === "freelancer-files" || pathname === "freelancer-payment" ? "active" : ""}`}>
               
               <Link to="#" className={isSideMenu === "forfreelancer" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu ==="forfreelancer" ? "": "forfreelancer")} >  For Freelancer<i className="fas fa-chevron-down" /></Link>              
                  { isSideMenu === "forfreelancer" ?    
             
                <ul className="submenu">
                  <li className={`has-submenu ${pathname === "project" || pathname === "project-details" ? "active" : ""}`}>
                    <Link to="#" className={isSideMenu2 === "projects" ? "subdrop" : ""} onClick={()=> toggleSidebar2(isSideMenu2 ==="projects" ? "": "projects")}>Projects</Link>
                    { isSideMenu2 === "projects" ?    
             
                    <ul className="submenu">
                      <li className={pathname === "project" ? "active" : ""}>
                        <Link to="/project">Projects</Link>
                      </li>
                      <li className={pathname === "project-details" ? "active" : ""}>
                        <Link to="/project-details">Project Details</Link>
                      </li>
                    </ul>
                    :""}
                  </li>
                  <li className={pathname === "freelancer-dashboard" ? "active" : ""}>
                    <Link to="/freelancer-dashboard">Dashboard</Link>
                  </li>
                  <li className={pathname === "developer-profile" ? "active" : ""}>
                    <Link to="/developer-profile">My Profile</Link>
                  </li>
                  <li className={pathname === "freelancer-details" ? "active" : ""}>
                    <Link to="/freelancer-details">Freelancer Details</Link>
                  </li>
                  <li className={pathname === "freelancer-project-proposals" || pathname === "freelancer-ongoing-projects" ||
                  pathname === "freelancer-completed-projects" || pathname === "freelancer-cancelled-projects" ||
                  pathname === "freelancer-project-proposals" || pathname === "freelancer-view-project-detail" || pathname === "freelancer-milestones"
                  || pathname === "freelancer-task" || pathname === "freelancer-files" || pathname === "freelancer-payment" ? "active" : ""}>
                    <Link to="/freelancer-project-proposals">Projects</Link>
                  </li>
                  <li className={pathname === "freelancer-favourites" || pathname === "freelancer-invitations" ? "active" : ""}>
                    <Link to="/freelancer-favourites">Favourites</Link>
                  </li>
                  <li className={pathname === "freelancer-membership" ? "active" : ""}>
                    <Link to="/freelancer-membership">Membership</Link>
                  </li>
                  <li className={pathname === "freelancer-change-password" ? "active" : ""}>
                    <Link to="/freelancer-change-password">Change Password</Link>
                  </li>
                  <li className={pathname === "freelancer-chats" ? "active" : ""}>
                    <Link to="/freelancer-chats">Chats</Link>
                  </li>
                  <li className={pathname === "freelancer-review" ? "active" : ""}>
                    <Link to="/freelancer-review">Review</Link>
                  </li>
                  <li className={pathname === "freelancer-withdraw-money"|| pathname === "freelancer-transaction-history" ? "active" : ""}>
                    <Link to="/freelancer-withdraw-money">Payments</Link>
                  </li>
                  <li className={pathname === "freelancer-verify-identity" ? "active" : ""}>
                    <Link to="/freelancer-verify-identity">Verify Identity</Link>
                  </li>
                  <li className={pathname === "freelancer-profile-settings" ? "active" : ""}>
                    <Link to="/freelancer-profile-settings">Settings</Link>
                  </li>
                </ul>
                :""}
              </li>
              <li className={`has-submenu ${pathname === "about" || pathname === "blank-page" || pathname === "404-page" ||
              pathname === "user-account-details" || pathname === "login" || pathname === "register" || 
              pathname === "forgot-password" || pathname === "change-password" || pathname === "freelancer-invoices" || 
              pathname === "view-invoice"  ? "active" : ""}`}>
                    <Link to="#" className={isSideMenu === "pages" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu ==="pages" ? "": "pages")} >Pages <i className="fas fa-chevron-down" /></Link>              
                  { isSideMenu === "pages" ? 
                
                <ul className="submenu">
                  <li className={pathname === "about" ? "active" : ""}>
                    <Link to="/about">About us</Link>
                  </li>
                  <li className={pathname === "blank-page" ? "active" : ""}>
                    <Link to="/blank-page">Starter Page</Link>
                  </li>
                  <li className={pathname === "404-page" ? "active" : ""}>
                    <Link to="/404-page">404 Page</Link>
                  </li>
                  <li className={pathname === "user-account-details" ? "active" : ""}>
                    <Link to="/user-account-details">User Details</Link>
                  </li>
                  <li className={`has-submenu ${pathname === "freelancer-invoices" || pathname === "view-invoice"  ? "active" : ""}`}>
                    <Link to="#" className={isSideMenu3 === "invoices" ? "subdrop" : ""} onClick={()=> toggleSidebar3(isSideMenu3 ==="invoices" ? "": "invoices")}>Invoices</Link>
                    { isSideMenu3 === "invoices" ?
                    <ul className="submenu">
                      <li className={pathname === "freelancer-invoices" ? "active" : ""}>
                        <Link to="/freelancer-invoices">Invoices</Link>
                      </li>
                      <li className={pathname === "view-invoice" ? "active" : ""}>
                        <Link to="/view-invoice">Invoice View</Link>
                      </li>
                    </ul>
                    :""}
                  </li>
                  <li className={pathname === "login" ? "active" : ""}>
                    <Link to="/login">Login</Link>
                  </li>
                  <li className={pathname === "register" ? "active" : ""}>
                    <Link to="/register">Register</Link>
                  </li>
                  <li className={pathname === "onboardScreen" ? "active" : "" }onClick={Reload}>
                    <Link to="/onboardScreen">Onboard Screen</Link>
                  </li>
                  <li className={pathname === "forgot-password" ? "active" : ""}>
                    <Link to="/forgot-password">Forgot Password</Link>
                  </li>
                  <li className={pathname === "change-password" ? "active" : ""}>
                    <Link to="/change-password">Change Password</Link>
                  </li>
                </ul>
                  :""}
              </li>
              <li className={`has-submenu ${pathname === "blog-list" || pathname === "blog-grid" || 
              pathname === "blog-details" ? "active" : ""}`}>
                   <Link to="#" className={isSideMenu === "blog" ? "subdrop" : ""} onClick={()=> toggleSidebar(isSideMenu ==="blog" ? "": "blog")} >Blog <i className="fas fa-chevron-down" /></Link>              
                  { isSideMenu === "blog" ? 
                
                <ul className="submenu">
                  <li className={pathname === "blog-list" ? "active" : ""}>
                    <Link to="/blog-list">Blog List</Link>
                  </li>
                  <li className={pathname === "blog-grid" ? "active" : ""}>
                    <Link to="/blog-grid">Blog Grid</Link>
                  </li>
                  <li className={pathname === "blog-details" ? "active" : ""}>
                    <Link to="/blog-details">Blog Details</Link>
                  </li>
                </ul>
                
                :""
              }
              </li>
              <li>
                  <Link to="/admin/login" target="_blank">Admin</Link>
              </li>
            </ul>
          </div>
          {pathname === "user-account-details" ? 
            <ul className="nav header-navbar-rht" >
              {/* User Menu */}
              <li className="nav-item dropdown has-arrow main-drop account-item" >
                <Link to="#" id="dropdownmenu" className={`dropdown-toggle nav-link `} data-toggle="dropdown">
                  <span className="user-img">
                    <img src={Img_04} alt="" />
                  </span>
                  <span>John</span>
                </Link>
                <div id="checkshow" className="dropdown-menu emp">
                  <div className="drop-head">Account Details</div>
                  <Link className="dropdown-item" to="/user-account-details">
                    <i className="material-icons">verified_user</i> View profile
                  </Link>
                  <div className="drop-head">Projects Settings</div>
                  <Link className="dropdown-item" to="/manage-projects">
                    <i className="material-icons">business_center</i> Projects
                  </Link>
                  <Link className="dropdown-item" to="/favourites">
                    <i className="material-icons">local_play</i> Favourites
                  </Link>
                  <Link className="dropdown-item" to="/review">
                    <i className="material-icons">pie_chart</i> Reviews
                  </Link>
                  <div className="drop-head">Account Details</div>
                  <Link className="dropdown-item" to="/profile-settings">
                    {" "}
                    <i className="material-icons">settings</i> Profile Settings
                  </Link>
                  <Link className="dropdown-item" to="/">
                    <i className="material-icons">power_settings_new</i> Logout
                  </Link>
                </div>
              </li>
              {/* /User Menu */}
              <li>
                <Link to="/post-project" className="login-btn">
                  Post a Project{" "}
                </Link>
              </li>
            </ul> : pathname === "freelancer-invoices" || pathname === "project" || pathname === "view-invoice"|| pathname.includes("freelancer-") ?
            <ul className="nav header-navbar-rht">
              <li className="nav-item dropdown has-arrow account-item">
                <Link to="#" className="dropdown-toggle nav-link"  data-bs-toggle="dropdown">
                  <span className="user-img">
                    <img src={avatar_1} alt=""/>
                  </span>
                  <span>John</span>
                </Link>
                <div className="dropdown-menu emp">
                    <div className="drop-head">Account Details</div>
                      <Link className="dropdown-item" to="/user-account-details">
                        <i className="material-icons">verified_user</i> View profile
                      </Link>
                    <div className="drop-head">Projects Settings</div>
                      <Link className="dropdown-item" to="/manage-projects">
                        <i className="material-icons">business_center</i> Projects
                      </Link>
                      <Link className="dropdown-item" to="/favourites">
                        <i className="material-icons">local_play</i> Favourites
                      </Link>
                      <Link className="dropdown-item" to="/review">
                        <i className="material-icons">pie_chart</i> Reviews
                      </Link>
                    <div className="drop-head">Account Details</div>
                      <Link className="dropdown-item" to="/profile-settings">
                        {" "}
                        <i className="material-icons">settings</i> Profile Settings
                      </Link>
                      <Link className="dropdown-item" to="/">
                        <i className="material-icons">power_settings_new</i> Logout
                      </Link>
                  </div>
              </li>
              <li className={pathname === "post-project" ? "active" : ""}>
                <Link to="/post-project" className="login-btn">
                  Post a Project{" "}
                </Link>
              </li>
            </ul> :
            <ul className="nav header-navbar-rht">
              <li className={pathname === "register" ? "active" : ""}>
                <Link to="/register" className="reg-btn">
                  <i className="fas fa-user" /> Register
                </Link>
              </li>
              <li className={pathname === "login" ? "active" : ""}>
                <Link to="/login" className="log-btn">
                  <i className="fas fa-lock" /> Login
                </Link>
              </li>
              <li className={pathname === "post-project" ? "active" : ""}>
                <Link to="/post-project" className="login-btn" >
                  Post a Project{" "}
                </Link>
              </li>
            </ul> }
        </nav>
      </header>
}
      {/* /Header */}
    </>
     );
  
}

export default Header;
