// template-vuejs/src/views/frontend/freelancer/membership.vue
<template>
<div class="dashboard-page">
       <!-- Main Wrapper -->
        <div class="main-wrapper">
			<!-- Header -->
            <layout-freelancerprojectheader></layout-freelancerprojectheader>
			<!-- /Header -->

            <!-- Breadcrumb -->
			<div class="bread-crumb-bar">
				<div class="container">
					<div class="row align-items-center inner-banner">
						<div class="col-md-12 col-12 text-center">
							<div class="breadcrumb-list">
								<nav aria-label="breadcrumb" class="page-breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><router-link to="/index"><img src="../../../assets/img/home-icon.svg" alt="Post Author"> Home</router-link></li>
										<li class="breadcrumb-item" aria-current="page">Freelancer</li>
										<li class="breadcrumb-item" aria-current="page">Membership</li>
									</ol>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<div class="content content-page">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xl-3 col-md-4 theiaStickySidebar">
                            <div class="stickyside">
							<div class="settings-widget">
								<div class="settings-header d-sm-flex flex-row flex-wrap text-center text-sm-start align-items-center">
									<router-link to="/freelancer-profile"><img alt="profile image" src="../../../assets/img/user/avatar-1.jpg" class="avatar-lg rounded-circle"></router-link>
									<div class="ms-sm-3 ms-md-0 ms-lg-3 mt-2 mt-sm-0 mt-md-2 mt-lg-0">
										<p class="mb-2">Welcome,</p>
										<h3 class="mb-0"><router-link to="/freelancer-profile">George Wells</router-link></h3>
										<p class="mb-0">@georgewell</p>
									</div>
								</div>
								<div class="settings-menu">
									<ul>
										<li class="nav-item">
											<router-link to="/freelancer-dashboard" class="nav-link">
												<i class="material-icons">verified_user</i> Dashboard
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/freelancer-project-proposals" class="nav-link">
												<i class="material-icons">business_center</i> Projects
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/freelancer-favourites" class="nav-link">
												<i class="material-icons">local_play</i> Favourites
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/freelancer-review" class="nav-link">
												<i class="material-icons">record_voice_over</i> Reviews
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/freelancer-portfolio" class="nav-link">
												<i class="material-icons">pie_chart</i> Portfolio
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/freelancer-chats" class="nav-link">
												<i class="material-icons">chat</i> Messages
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/freelancer-membership" class="nav-link active">
												<i class="material-icons">person_add</i> Membership
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/freelancer-verify-identity" class="nav-link">
												<i class="material-icons">person_pin</i> Verify Identity
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/freelancer-withdraw-money" class="nav-link">
												<i class="material-icons">wifi_tethering</i> Payments
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/freelancer-profile-settings" class="nav-link">
												<i class="material-icons">settings</i>  Settings
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/" class="nav-link">
												<i class="material-icons">power_settings_new</i> Logout
                                            </router-link>
										</li>
									</ul>
								</div>
							</div>
                        </div>					
						</div>	
						<div class="col-xl-9 col-md-8">	
							<div class="freelance-title" id="plan">
								<h3>Freelancer Packages</h3>
								<p> Choose the best pricing that suites your requirements</p>
							</div>	
							<div class="row">
								<div class="col-lg-4">
									<div class="package-detail">
										<h4>Basic Plan</h4>
										<p>Go Pro, Best for the individuals</p>
										<h3 class="package-price">$19.00</h3>
										<div class="package-feature">
											<ul>
												<li>12 Project Credits</li>
												<li>10 Allowed Services</li>
												<li>20 Days visibility</li>
												<li>5 Featured Services</li>
												<li>20 Days visibility</li>
												<li>30 Days Package Expiry</li>
												<li class="non-check">Profile Featured</li>
											</ul>
										</div>
										<a href="javascript:void(0);" class="btn btn-primary price-btn btn-block">Select Plan</a>
									</div>
								</div>
								
								<div class="col-lg-4">
									<div class="package-detail">
										<h4>Business </h4>
										<p>Highest selling package features</p>
										<h3 class="package-price">$29.00</h3>
										<div class="package-feature">
											<ul>
												<li>15 Project Credits</li>
												<li>12 Allowed Services</li>
												<li>25 Days visibility</li>
												<li>10 Featured Services</li>
												<li>30 Days visibility</li>
												<li>40 Days Package Expiry</li>
												<li>Profile Featured</li>
											</ul>
										</div>
										<a href="javascript:void(0);" class="btn btn-primary price-btn btn-block">Select Plan</a>
									</div>
								</div>
								
								<div class="col-lg-4">
									<div class="package-detail">
										<h4>The Unlimita </h4>
										<p>Drive crazy, unlimited on the go</p>
										<h3 class="package-price">$79.00</h3>
										<div class="package-feature">
											<ul>
												<li>Unlimited Project Credits</li>
												<li>Unlimited Services</li>
												<li>Services Never Expire</li>
												<li>20 Featured Services</li>
												<li>Services Never Expire</li>
												<li>Package Never Expire</li>
												<li>Profile Featured</li>
											</ul>
										</div>
										<a href="javascript:void(0);" class="btn btn-primary price-btn btn-block">Select Plan</a>
									</div>
								</div>
							</div>
							
							<div class="row">
								<div class="col-lg-6">
									<div class="member-plan pro-box">
										<div class="pro-head">
											<h2><i class="fa fa-check-circle orange-text" aria-hidden="true"></i> Plan Details</h2>
										</div>
										<div class="pro-body member-detail">
											<div class="row">
												<div class="col-6">
													<h4 class="mb-0">The Ultima</h4>
													<div class="yr-amt">Anually Price</div>													
													<div class="expiry-on">Expiry On</div>												
													<div class="expiry">24 JAN 2022</div>									
												</div>
												<div class="col-6 change-plan">
													<h3>$1200</h3>
													<div class="yr-duration">Duration: One Year</div>
													<a href="#plan" class="btn btn-primary btn-plan black-btn">Change Plan</a>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="row">
								<div class="col-lg-12">
									<div class="pro-post">
										<div class="project-table">
											<div class="card-body">
												<h4>STATEMENT</h4>
												<div class="table-responsive table-box">
													<table class="table table-center table-hover datatable" id="freelancermembership">
														<thead class="thead-pink">
															<tr>
																<th>Purchased Date</th>
																<th>Details</th>
																<th>Expiry Date</th>
																<th>Type</th>
																<th>Status</th>
																<th>Price</th>
															</tr>
														</thead>
														<tbody>
															<tr>
																<td>15 October 2021</td>
																<td>
																	<p class="mb-0">The Unlimita</p>
																	<a href="javascript:void(0);" class="read-text">Invoice : IVIP12023598</a>
																</td>
																<td>15th July 2022</td>
																<td>Yearly</td>
																<td class="text-danger">Inactive</td>
																<td>$200.00</td>
															</tr>
															<tr>
																<td>15 October 2022</td>
																<td>
																	<p class="mb-0">The Unlimita</p>
																	<a href="javascript:void(0);" class="read-text">Invoice : IVIP12023598</a>
																</td>
																<td>15th July 2023</td>
																<td>Yearly</td>
																<td class="text-success">Active</td>
																<td>$170.00</td>
															</tr>
														</tbody>
													</table>
												</div>
												<div class="text-end mt-3">
													<ul class="paginations">
														<li><a href="javascript:void(0);"> <i class="fas fa-angle-left"></i> Previous</a></li>
														<li><a href="javascript:void(0);">1</a></li>
														<li><a href="javascript:void(0);" class="active">2</a></li>
														<li><a href="javascript:void(0);">3</a></li>
														<li><a href="javascript:void(0);">4</a></li>
														<li><a href="javascript:void(0);">Next <i class="fas fa-angle-right"></i></a></li>
													</ul>
												</div>
											</div>
										</div>
									</div>	
								</div>
							</div>							
						</div>
					</div>
				</div>
			</div>	
			
			<!-- /Page Content -->
           
            <!-- Footer -->
                <layout-footer />
            <!-- /Footer -->
        </div>
        <!-- /Main Wrapper -->
        </div>
</template>
<script>
    import util from '../../../assets/utils/util'
	export default {
		 mounted() {
            util.datatable('#freelancermembership')
		},
        computed: {
            currentPath() {
                return this.$route.name;
            }
    
        },  
        data() {
        return {
          activeClass: 'active',
        };
                //  isactive : true
      },
	}
	</script>

// template-react/src/frontend/components/forfreelancer/membership/index.jsx
import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import StickyBox from "react-sticky-box";
import { home_icon } from "../../imagepath";
import { Sidebar } from '../sidebar';
    
const FreelancerMembership = (props) => {   
  useEffect(() => {
    document.body.className = 'dashboard-page';
    return () => { document.body.className = ''; }
  });
        
  return (
        <>
        {/* Breadcrumb */}
      <div className="bread-crumb-bar">
        <div className="container">
          <div className="row align-items-center inner-banner">
            <div className="col-md-12 col-12 text-center">
              <div className="breadcrumb-list">
                <nav aria-label="breadcrumb" className="page-breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item"><Link to="#"><img src={home_icon} alt="Post Author" /> Home</Link></li>
                    <li className="breadcrumb-item" aria-current="page">FREELANCER
</li>
                    <li className="breadcrumb-item" aria-current="page">MEMBERSHIP</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Breadcrumb */}
          <div className="content">
            <div className="container-fluid">
              <div className="row">
                <div className="col-xl-3 col-md-4 theiaStickySidebar">
                    <StickyBox offsetTop={20} offsetBottom={20}>
                            <Sidebar/>
                        </StickyBox>
                </div>
                <div className="col-xl-9 col-md-8">
                  <div className="freelance-title" id="plan">
                    <h3>Freelancer Packages</h3>
                    <p> Choose the best pricing that suites your requirements</p>
                  </div>
                  <div className="row">
                    <div className="col-lg-4">
                      <div className="package-detail">
                        <h4>Basic Plan</h4>
                        <p>Go Pro, Best for the individuals</p>
                        <h3 className="package-price">$19.00</h3>
                        <div className="package-feature">
                          <ul>
                            <li>12 Project Credits</li>
                            <li>10 Allowed Services</li>
                            <li>20 Days visibility</li>
                            <li>5 Featured Services</li>
                            <li>20 Days visibility</li>
                            <li>30 Days Package Expiry</li>
                            <li className="non-check">Profile Featured</li>
                          </ul>
                        </div>
                        <a href="#" className="btn btn-primary price-btn btn-block">
                          Select Plan
                        </a>
                      </div>
                    </div>
                    <div className="col-lg-4">
                      <div className="package-detail">
                        <h4>Business </h4>
                        <p>Highest selling package features</p>
                        <h3 className="package-price">$29.00</h3>
                        <div className="package-feature">
                          <ul>
                            <li>15 Project Credits</li>
                            <li>12 Allowed Services</li>
                            <li>25 Days visibility</li>
                            <li>10 Featured Services</li>
                            <li>30 Days visibility</li>
                            <li>40 Days Package Expiry</li>
                            <li>Profile Featured</li>
                          </ul>
                        </div>
                        <a href="#" className="btn btn-primary price-btn btn-block">
                          Select Plan
                        </a>
                      </div>
                    </div>
                    <div className="col-lg-4">
                      <div className="package-detail">
                        <h4>The Unlimita </h4>
                        <p>Drive crazy, unlimited on the go</p>
                        <h3 className="package-price">$79.00</h3>
                        <div className="package-feature">
                          <ul>
                            <li>Unlimited Project Credits</li>
                            <li>Unlimited Services</li>
                            <li>Services Never Expire</li>
                            <li>20 Featured Services</li>
                            <li>Services Never Expire</li>
                            <li>Package Never Expire</li>
                            <li>Profile Featured</li>
                          </ul>
                        </div>
                        <a href="#" className="btn btn-primary price-btn btn-block">
                          Select Plan
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-lg-6">
                      <div className="member-plan pro-box">
                        <div className="pro-head">
                          <h2>
                            <i
                              className="fa fa-check-circle orange-text"
                              aria-hidden="true"
                            />{" "}
                            Plan Details
                          </h2>
                        </div>
                        <div className="pro-body member-detail">
                          <div className="row">
                            <div className="col-6">
                              <h4 className="mb-0">The Ultima</h4>
                              <div className="yr-amt">Anually Price</div>
                              <div className="expiry-on">Expiry On</div>
                              <div className="expiry">24 JAN 2022</div>
                            </div>
                            <div className="col-6 change-plan">
                              <h3>$1200</h3>
                              <div className="yr-duration">Duration: One Year</div>
                              <a
                                href="#plan"
                                className="btn btn-primary btn-plan black-btn"
                              >
                                Change Plan
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-lg-12">
                      <div className="pro-post">
                        <div className="project-table">
                          <div className="card-body">
                            <h4>STATEMENT</h4>
                            <div className="table-responsive table-box">
                              <table className="table table-center table-hover datatable">
                                <thead className="thead-pink">
                                  <tr>
                                    <th>Purchased Date</th>
                                    <th>Details</th>
                                    <th>Expiry Date</th>
                                    <th>Type</th>
                                    <th>Status</th>
                                    <th>Price</th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <tr>
                                    <td>15 October 2021</td>
                                    <td>
                                      <p className="mb-0">The Unlimita</p>
                                      <a href="#" className="read-text">
                                        Invoice : IVIP12023598
                                      </a>
                                    </td>
                                    <td>15th July 2022</td>
                                    <td>Yearly</td>
                                    <td className="text-danger">Inactive</td>
                                    <td>$200.00</td>
                                  </tr>
                                  <tr>
                                    <td>15 October 2022</td>
                                    <td>
                                      <p className="mb-0">The Unlimita</p>
                                      <a href="#" className="read-text">
                                        Invoice : IVIP12023598
                                      </a>
                                    </td>
                                    <td>15th July 2023</td>
                                    <td>Yearly</td>
                                    <td className="text-success">Active</td>
                                    <td>$170.00</td>
                                  </tr>
                                </tbody>
                              </table>
                            </div>
                            <div className="text-end mt-3">
                              <ul className="paginations">
                                <li>
                                  <a href="#">
                                    {" "}
                                    <i className="fas fa-angle-left" /> Previous
                                  </a>
                                </li>
                                <li>
                                  <a href="#">1</a>
                                </li>
                                <li>
                                  <a href="#" className="active">
                                    2
                                  </a>
                                </li>
                                <li>
                                  <a href="#">3</a>
                                </li>
                                <li>
                                  <a href="#">4</a>
                                </li>
                                <li>
                                  <a href="#">
                                    Next <i className="fas fa-angle-right" />
                                  </a>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>  
        </>
      )
  
}
export default FreelancerMembership;
