// template-angular/src/app/features-modules/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import {
  UntypedFormControl,
  UntypedFormGroup,
  Validators,
} from '@angular/forms';
import { Subscription } from 'rxjs';
import { WebStorage } from 'src/app/core/storage/web.storage';


@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  public Toggledata = true;
  public CustomControler: any;
  public subscription: Subscription;
  form = new UntypedFormGroup({
    email: new UntypedFormControl('admin@dreamguys.in', [Validators.required]),
    password: new UntypedFormControl('123456', [Validators.required]),
  });
  get f() {
    return this.form.controls;
  }

  constructor(private storage: WebStorage) {
    this.subscription = this.storage.Loginvalue.subscribe((data) => {
      if (data != 0) {
        this.CustomControler = data;
      }
    });
  }
  ngOnInit() {
    this.storage.Checkuser();
    localStorage.removeItem('LoginData');
  }

  submit() {
    this.storage.Login(this.form.value);
  }
  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
  iconLogle() {
    this.Toggledata = !this.Toggledata;
  }
  otherPages(val: string) {
    localStorage.setItem(val, val);
  }
}

<!-- Page Content -->
<div class="content content-page">
    <div class="container">					
        <div class="row">
            <div class="col-md-6 offset-md-3">
                
                <!-- Login Content -->
                <div class="account-content">
                    <div class="align-items-center justify-content-center">
                        <div class="login-right">
                            <div class="login-header text-center">
                                <a [routerLink] = "'/home'"><img src="assets/img/logo-01.png" alt="logo" class="img-fluid"></a>
                                <h3>Welcome Back</h3>
                                <p>Don't miss your next opportunity. Sign in to stay updated on your professional world.</p>
                            </div>
                            <form action="/auth/register">
                                <div class="form-group form-focus">
                                    <input type="email" class="form-control floating">
                                    <label class="focus-label">Email</label>
                                </div>
                                <div class="form-group form-focus">
                                    <input type="password" class="form-control floating">
                                    <label class="focus-label">Password</label>
                                </div>
                                <div class="form-group">
                                    <label class="custom_check">
                                        <input type="checkbox" name="rem_password">
                                        <span class="checkmark"></span> Remember password
                                    </label>
                                </div>
                                <button  [routerLink]="'/employer/dashboard'" class="btn btn-primary btn-block btn-lg login-btn" type="submit">Login</button>
                                <div class="login-or">
                                    <p>Or login with</p>
                                </div>
                                <!-- Social Login -->
                                <div class="row form-row social-login">
                                    <div class="col-lg-4">
                                        <a href="#" class="btn btn-twitter btn-block mb-1"> Twitter</a>
                                    </div>
                                    <div class="col-lg-4">
                                        <a href="#" class="btn btn-facebook btn-block mb-1"> Facebook</a>
                                    </div>
                                    <div class="col-lg-4">
                                        <a href="#" class="btn btn-google btn-block mb-1"> Google</a>
                                    </div>
                                </div>
                                <!-- /Social Login -->
                                <div class="row form-row login-foot">
                                    <div class="col-lg-6 login-forgot">
                                        <a class="forgot-link" [routerLink]="'/auth/forgot-password'">Forgot Password ?</a>
                                    </div>
                                    <div class="col-lg-6 dont-have">New to Kofejob? <a [routerLink]="'/auth/register'">Click here</a></div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /Login Content -->
                    
            </div>
        </div>
    </div>
</div>					
<!-- /Page Content -->

// template-vuejs/src/views/frontend/page/login.vue
<template>
<div class="account-page">
       <!-- Main Wrapper -->
        <div class="main-wrapper">
			<!-- Header -->
                <layout-header />
			<!-- /Header -->
			
			<!-- Page Content -->
			<div class="content">
				<div class="container">					
					<div class="row">
						<div class="col-md-6 offset-md-3">
							
							<!-- Login Content -->
							<div class="account-content">
								<div class="align-items-center justify-content-center">
									<div class="login-right">
										<div class="login-header text-center">
											<router-link to="/index"><img src="../../../assets/img/logo-01.png" alt="logo" class="img-fluid"></router-link>
											<h3>Welcome Back</h3>
											<p>Don't miss your next opportunity. Sign in to stay updated on your professional world.</p>
										</div>
										<form>
											<div class="form-group form-focus">
												<input type="text" class="form-control floating">
												<label class="focus-label">Email</label>
											</div>
											<div class="form-group form-focus">
												<input type="password" class="form-control floating">
												<label class="focus-label">Password</label>
											</div>											
											<div class="form-group">
												<label class="custom_check">
													<input type="checkbox" name="rem_password">
													<span class="checkmark"></span> Remember password
												</label>
											</div>
                                            <router-link to="/dashboard">
											<button class="btn btn-primary btn-block btn-lg login-btn" type="submit">Login</button>
                                            </router-link>
											<div class="login-or">
												<p>Or login with</p>
											</div>
											<div class="row social-login">
												<div class="col-4">
													<a href="javascript:void(0);" class="btn btn-twitter btn-block"> Twitter</a>
												</div>
												<div class="col-4">
													<a href="javascript:void(0);" class="btn btn-facebook btn-block"> Facebook</a>
												</div>
												<div class="col-4">
													<a href="javascript:void(0);" class="btn btn-google btn-block"> Google</a>
												</div>
											</div>
											<div class="row">
											<div class="col-6 text-start">
												<router-link class="forgot-link" to="/forgot-password">Forgot Password ?</router-link>
											</div>
											<div class="col-6 text-end dont-have">New to Kofejob? <router-link to="/register">Click here</router-link></div>
											</div>
										</form>
									</div>
								</div>
							</div>
							<!-- /Login Content -->
								
						</div>
					</div>
				</div>
			</div>					
			<!-- /Page Content -->
           
            <!-- Footer -->
                <layout-footer />
            <!-- /Footer -->
        </div>
        <!-- /Main Wrapper -->
        </div>
</template>
<script>
export default {
     mounted() {
    
    },
}
</script>
