// template-angular/src/app/features-modules/admin/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import {
  UntypedFormControl,
  UntypedFormGroup,
  Validators,
} from '@angular/forms';
import { Subscription } from 'rxjs';
import { WebStorage } from '../../../../core/storage/web.storage';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  public Toggledata = true;
  public CustomControler: any;
  public subscription: Subscription;
  form = new UntypedFormGroup({
    email: new UntypedFormControl('admin@dreamguys.in', [Validators.required]),
    password: new UntypedFormControl('123456', [Validators.required]),
  });
  get f() {
    return this.form.controls;
  }

  constructor(private storage: WebStorage) {
    this.subscription = this.storage.Loginvalue.subscribe((data) => {
      if (data != 0) {
        this.CustomControler = data;
      }
    });
  }
  ngOnInit() {
    this.storage.Checkuser();
    localStorage.removeItem('LoginData');
  }

  submit() {
    this.storage.Login(this.form.value);
  }
  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
  iconLogle() {
    this.Toggledata = !this.Toggledata;
  }
}

    <!-- Main Wrapper -->
    <div class="main-wrapper login-body">
        <div class="login-wrapper">
            <div class="container">
            
                <img class="img-fluid logo-dark mb-2" src="assets/img/logo-01.png" alt="Logo">
                <div class="loginbox">
                    
                    <div class="login-right">
                        <div class="login-right-wrap">
                            <h1>Welcome Back</h1>
                            <p class="account-subtitle text-center">Don't miss your next opportunity. Sign in to stay updated on your professional world.</p>
                            
                            <form [formGroup]="form" (ngSubmit)="submit()">
                                <div class="form-group form-focus focused">
                                    <label class="focus-label">Email</label>
                                    <input class="form-control floating"
                                        class="form-control"
                                        type="text"
                                        formControlName="email"
                                        id="email"
                                        [ngClass]="{
                                        'is-invalid': f['email'].touched && f['email'].invalid
                                        }"
                                  />
                                  <span class="profile-views"><i class="fas fa-user-circle"></i></span>
                                  <div
                                        class="invalid-feedback"
                                        *ngIf="CustomControler ?.status === 'email'"
                                    >
                                        {{ CustomControler.message }}
                                    </div>
                                    <div
                                    *ngIf="f['email'].touched && f['email'].invalid"
                                    class="invalid-feedback"
                                    >
                                    <div
                                        *ngIf="f['email'].errors && f['email'].errors['required']"
                                    >
                                        Email is required.
                                    </div>
                                    <div *ngIf="f['email'].errors && f['email'].errors['email']">
                                        Please, enter valid email address.
                                    </div>
                                    </div>
                                </div>
                                <div class="form-group form-focus focused">
                                    
                                    <label class="focus-label">Password</label>
                                    <input class="form-control floating"
                                    [type]="Toggledata ? 'password' : 'text'"
                                    formControlName="password"
                                    id="password"
                                    [ngClass]="{
                                      'is-invalid':
                                        f['password'].touched && f['password'].invalid
                                    }"
                                  />
                                  <span
                                    [ngClass]="Toggledata == true ? 'fas toggle-password fa-eye-slash' : 'fas toggle-password fa-eye'"
                                    (click)="iconLogle()"
                                    ></span>
                                  <div
                                    *ngIf="f['password'].touched && f['password'].invalid"
                                    class="invalid-feedback"
                                >
                                    <div
                                    *ngIf="
                                        f['password'].errors && f['password'].errors['required']
                                    "
                                    >
                                    Password is required.
                                    </div>
                                </div>
                                <div
                                    class="invalid-feedback"
                                    *ngIf="CustomControler ?.status === 'password'"
                                >
                                    {{ CustomControler.message }}
                                </div>
                                </div>											
                                <div class="form-group">
                                    <label class="custom_check">
                                        <input type="checkbox" name="rem_password">
                                        <span class="checkmark"></span> Remember password
                                    </label>
                                </div>
                                <button class="btn btn-primary btn-block btn-lg login-btn"  type="submit">Login</button>
                                <div class="login-or">
                                    <p>Or login with</p>
                                </div>
                                <div class="row social-login">
                                    <div class="col-4">
                                        <a href="javascript:void(0);" class="btn btn-twitter btn-block"> Twitter</a>
                                    </div>
                                    <div class="col-4">
                                        <a href="javascript:void(0);" class="btn btn-facebook btn-block"> Facebook</a>
                                    </div>
                                    <div class="col-4">
                                        <a href="javascript:void(0);" class="btn btn-google btn-block"> Google</a>
                                    </div>
                                </div>
                                <div class="row">
                                <div class="col-6 text-start">
                                    <a class="forgot-link" [routerLink] = "'/admin/auth/forgot-password'">Forgot Password ?</a>
                                </div>
                                <div class="col-6 text-end dont-have">New to Kofejob? <a [routerLink] = "'/admin/auth/register'">Click here</a></div>
                                </div>
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Main Wrapper -->

// template-vuejs/src/views/frontend/page/login.vue
<template>
<div class="account-page">
       <!-- Main Wrapper -->
        <div class="main-wrapper">
			<!-- Header -->
                <layout-header />
			<!-- /Header -->
			
			<!-- Page Content -->
			<div class="content">
				<div class="container">					
					<div class="row">
						<div class="col-md-6 offset-md-3">
							
							<!-- Login Content -->
							<div class="account-content">
								<div class="align-items-center justify-content-center">
									<div class="login-right">
										<div class="login-header text-center">
											<router-link to="/index"><img src="../../../assets/img/logo-01.png" alt="logo" class="img-fluid"></router-link>
											<h3>Welcome Back</h3>
											<p>Don't miss your next opportunity. Sign in to stay updated on your professional world.</p>
										</div>
										<form>
											<div class="form-group form-focus">
												<input type="text" class="form-control floating">
												<label class="focus-label">Email</label>
											</div>
											<div class="form-group form-focus">
												<input type="password" class="form-control floating">
												<label class="focus-label">Password</label>
											</div>											
											<div class="form-group">
												<label class="custom_check">
													<input type="checkbox" name="rem_password">
													<span class="checkmark"></span> Remember password
												</label>
											</div>
                                            <router-link to="/dashboard">
											<button class="btn btn-primary btn-block btn-lg login-btn" type="submit">Login</button>
                                            </router-link>
											<div class="login-or">
												<p>Or login with</p>
											</div>
											<div class="row social-login">
												<div class="col-4">
													<a href="javascript:void(0);" class="btn btn-twitter btn-block"> Twitter</a>
												</div>
												<div class="col-4">
													<a href="javascript:void(0);" class="btn btn-facebook btn-block"> Facebook</a>
												</div>
												<div class="col-4">
													<a href="javascript:void(0);" class="btn btn-google btn-block"> Google</a>
												</div>
											</div>
											<div class="row">
											<div class="col-6 text-start">
												<router-link class="forgot-link" to="/forgot-password">Forgot Password ?</router-link>
											</div>
											<div class="col-6 text-end dont-have">New to Kofejob? <router-link to="/register">Click here</router-link></div>
											</div>
										</form>
									</div>
								</div>
							</div>
							<!-- /Login Content -->
								
						</div>
					</div>
				</div>
			</div>					
			<!-- /Page Content -->
           
            <!-- Footer -->
                <layout-footer />
            <!-- /Footer -->
        </div>
        <!-- /Main Wrapper -->
        </div>
</template>
<script>
export default {
     mounted() {
    
    },
}
</script>
