// template-react/src/frontend/components/foremployers/projectproposal/viewproposal.jsx
import React from "react";
import { Link } from "react-router-dom";
import { Avatar_1,Avatar_2,Avatar_3,Avatar_4,Avatar_5,Flags_us,Flags_es,Flags_de,Flags_fr  } from "../../imagepath";
    
const ViewProposals = (props) => {  
 
    return (
        <>
            {/* Breadcrumb */}
            <div className="breadcrumb-bar">
                <div className="container">
                <div className="row align-items-center custom-breadcrumb">
                    <div className="col-md-12 col-12 text-center">
                    <h2 className="breadcrumb-title">Porposals</h2>
                    <nav aria-label="breadcrumb" className="page-breadcrumb">
                        <ol className="breadcrumb">
                        <li className="breadcrumb-item">
                            <Link to="/">Home</Link>
                        </li>
                        <li className="breadcrumb-item active" aria-current="page">
                            Project Details
                        </li>
                        </ol>
                    </nav>
                    </div>
                </div>
                </div>
            </div>
            {/* /Breadcrumb */}
            {/* Page Content */}
            <div className="content">
                <div className="container">
                <div className="row">
                    <div className="col-md-12">
                    <div className="profile">
                        <div className="profile-box">
                        <div className="provider-widget row">
                            <div className="pro-info-left col-md-8">
                            <div className="profile-info">
                                <p className="profile-cmpny">
                                Dreamguystech{" "}
                                <i className="fas fa-check-circle text-success ms-2" />
                                </p>
                                <h2 className="profile-title">
                                3D Renders and Amazon Product Store images/Video
                                </h2>
                                <div />
                            </div>
                            </div>
                            <div className="pro-info-right profile-inf">
                            <ul className="profile-right">
                                <li>
                                <div className="amt-hr">
                                    $20.00 <p>( FIXED )</p>
                                </div>
                                </li>
                            </ul>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                <div className="row">
                    <div className="col-12">
                    <Link
                        to="/project-details"
                        className="btn btn-primary bck-btn mb-4"
                    >
                        <i className="fas fa-long-arrow-alt-left me-2" /> Back to Project{" "}
                    </Link>
                    </div>
                    <div className="col-12">
                    <div className="pro-post widget-box">
                        <div className="average-bids">
                        <p>
                            <span className="text-highlight">18 freelancers</span> are
                            bidding on average{" "}
                            <span className="text-highlight">$17.00</span> for this job
                        </p>
                        </div>
                        <div className="proposal-cards">
                        {/* project proposal  */}
                        <div className="bids-card">
                            <div className="row align-items-center">
                            <div className="col-lg-2">
                                <div className="author-img-wrap">
                                <a href="#">
                                    <img
                                    className="img-fluid"
                                    alt=""
                                    src={Avatar_1}
                                    />
                                </a>
                                </div>
                            </div>
                            <div className="col-lg-8">
                                <div className="author-detail">
                                <h4>
                                    <a href="#">George Wells</a>{" "}
                                    <img
                                    src={Flags_de}
                                    height={16}
                                    alt="Lang"
                                    />
                                </h4>
                                <div className="rating">
                                    <span className="average-rating">4.1</span>
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star" />
                                </div>
                                <p className="mb-0">
                                    Look forward to hearing from you, I am a good designer
                                    and developer. I can handle your daily bases task with
                                    no extra effort. Please contact me as I am jobless
                                    nowadays.
                                </p>
                                </div>
                            </div>
                            <div className="col-lg-2">
                                <div className="proposal-amnt text-end">
                                <h3>$17.00</h3>
                                <p className="mb-0">in 14 days</p>
                                </div>
                            </div>
                            </div>
                        </div>
                        {/* /project proposal  */}
                        {/* project proposal  */}
                        <div className="bids-card">
                            <div className="row align-items-center">
                            <div className="col-lg-2">
                                <div className="author-img-wrap">
                                <a href="#">
                                    <img
                                    className="img-fluid"
                                    alt=""
                                    src={Avatar_2}
                                    />
                                </a>
                                </div>
                            </div>
                            <div className="col-lg-8">
                                <div className="author-detail">
                                <h4>
                                    <a href="#">Timothy Smith</a>{" "}
                                    <img
                                    src={Flags_fr}
                                    height={16}
                                    alt="Lang"
                                    />
                                </h4>
                                <div className="rating">
                                    <span className="average-rating">4.9</span>
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star" />
                                </div>
                                <p className="mb-0">
                                    Look forward to hearing from you, I am a good designer
                                    and developer. I can handle your daily bases task with
                                    no extra effort. Please contact me as I am jobless
                                    nowadays.
                                </p>
                                </div>
                            </div>
                            <div className="col-lg-2">
                                <div className="proposal-amnt text-end">
                                <h3>$12.00</h3>
                                <p className="mb-0">in 18 days</p>
                                </div>
                            </div>
                            </div>
                        </div>
                        {/* /project proposal  */}
                        {/* project proposal  */}
                        <div className="bids-card">
                            <div className="row align-items-center">
                            <div className="col-lg-2">
                                <div className="author-img-wrap">
                                <a href="#">
                                    <img
                                    className="img-fluid"
                                    alt=""
                                    src={Avatar_3}
                                    />
                                </a>
                                </div>
                            </div>
                            <div className="col-lg-8">
                                <div className="author-detail">
                                <h4>
                                    <a href="#">Janet Paden</a>{" "}
                                    <img
                                    src={Flags_us}
                                    height={16}
                                    alt="Lang"
                                    />
                                </h4>
                                <div className="rating">
                                    <span className="average-rating">4.2</span>
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star" />
                                </div>
                                <p className="mb-0">
                                    Look forward to hearing from you, I am a good designer
                                    and developer. I can handle your daily bases task with
                                    no extra effort. Please contact me as I am jobless
                                    nowadays.
                                </p>
                                </div>
                            </div>
                            <div className="col-lg-2">
                                <div className="proposal-amnt text-end">
                                <h3>$20.00</h3>
                                <p className="mb-0">in 20 days</p>
                                </div>
                            </div>
                            </div>
                        </div>
                        {/* /project proposal  */}
                        {/* project proposal  */}
                        <div className="bids-card">
                            <div className="row align-items-center">
                            <div className="col-lg-2">
                                <div className="author-img-wrap">
                                <a href="#">
                                    <img
                                    className="img-fluid"
                                    alt=""
                                    src={Avatar_4}
                                    />
                                </a>
                                </div>
                            </div>
                            <div className="col-lg-8">
                                <div className="author-detail">
                                <h4>
                                    <a href="#">James Douglas</a>{" "}
                                    <img
                                    src={Flags_es}
                                    height={16}
                                    alt="Lang"
                                    />
                                </h4>
                                <div className="rating">
                                    <span className="average-rating">3.9</span>
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star" />
                                    <i className="fas fa-star" />
                                </div>
                                <p className="mb-0">
                                    Look forward to hearing from you, I am a good designer
                                    and developer. I can handle your daily bases task with
                                    no extra effort. Please contact me as I am jobless
                                    nowadays.
                                </p>
                                </div>
                            </div>
                            <div className="col-lg-2">
                                <div className="proposal-amnt text-end">
                                <h3>$10.00</h3>
                                <p className="mb-0">in 22 days</p>
                                </div>
                            </div>
                            </div>
                        </div>
                        {/* /project proposal  */}
                        {/* project proposal  */}
                        <div className="bids-card">
                            <div className="row align-items-center">
                            <div className="col-lg-2">
                                <div className="author-img-wrap">
                                <a href="#">
                                    <img
                                    className="img-fluid"
                                    alt=""
                                    src={Avatar_5}
                                    />
                                </a>
                                </div>
                            </div>
                            <div className="col-lg-8">
                                <div className="author-detail">
                                <h4>
                                    <a href="#">Floyd Lewis</a>{" "}
                                    <img
                                    src={Flags_de}
                                    height={16}
                                    alt="Lang"
                                    />
                                </h4>
                                <div className="rating">
                                    <span className="average-rating">3.5</span>
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star" />
                                    <i className="fas fa-star" />
                                </div>
                                <p className="mb-0">
                                    Look forward to hearing from you, I am a good designer
                                    and developer. I can handle your daily bases task with
                                    no extra effort. Please contact me as I am jobless
                                    nowadays.
                                </p>
                                </div>
                            </div>
                            <div className="col-lg-2">
                                <div className="proposal-amnt text-end">
                                <h3>$22.00</h3>
                                <p className="mb-0">in 25 days</p>
                                </div>
                            </div>
                            </div>
                        </div>
                        {/* /project proposal  */}
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            {/* /Page Content */}
        </>
    )
  
}
export default ViewProposals;

// template-vuejs/src/views/frontend/page/viewproposal.vue
<template>
<div>
       <!-- Main Wrapper -->
        <div class="main-wrapper">
			<!-- Header -->
                <layout-header />
			<!-- /Header -->

            <!-- Breadcrumb -->
			<div class="breadcrumb-bar">
				<div class="container">
					<div class="row align-items-center custom-breadcrumb">
						<div class="col-md-12 col-12 text-center">
							<h2 class="breadcrumb-title">Porposals</h2>
							<nav aria-label="breadcrumb" class="page-breadcrumb">
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/index">Home</router-link></li>
									<li class="breadcrumb-item active" aria-current="page">Project Details</li>
								</ol>
							</nav>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Page Content -->
			<div class="content">
				<div class="container">	
					<div class="row">	
						<div class="col-md-12">	
							<div class="profile">			
								<div class="profile-box">			
									<div class="provider-widget row">
										<div class="pro-info-left col-md-8">
											<div class="profile-info">
												<p class="profile-cmpny">Dreamguystech <i class="fas fa-check-circle text-success ms-2"></i></p>
												<h2 class="profile-title">3D Renders and Amazon Product Store images/Video</h2>
												<div></div>
											</div>
										</div>
										<div class="pro-info-right profile-inf">
											<ul class="profile-right">
												<li><div class="amt-hr">$20.00 <p>(  FIXED )</p></div></li>
											</ul>
										</div>
									</div>						
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-12">
							<router-link to="/project-details" class="btn btn-primary bck-btn mb-4"><i class="fas fa-long-arrow-alt-left me-2"></i> Back to Project </router-link>
						</div>
						<div class="col-12">
							<div class="pro-post widget-box">
								<div class="average-bids">
									<p><span class="text-highlight">18 freelancers</span> are bidding on average <span class="text-highlight">$17.00</span> for this job</p>
								</div>
								<div class="proposal-cards">
								
									<!-- project proposal  -->
									<div class="bids-card">
										<div class="row align-items-center">
											<div class="col-lg-2">
												<div class="author-img-wrap">
													<a href="javascript:void(0);"><img class="img-fluid" alt="" src="../../../assets/img/user/avatar-1.jpg"></a>
												</div>
											</div>
											<div class="col-lg-8">
												<div class="author-detail">
													<h4><a href="javascript:void(0);">George Wells</a> <img src="../../../assets/img/flags/de.png" height="16" alt="Lang"></h4>
													<div class="rating mapgridrating1">							
														<span class="average-rating">4.1</span>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star"></i>
													</div>
													<p class="mb-0">Look forward to hearing from you, I am a good designer and developer. I can handle your daily bases task with no extra effort. Please contact me as I am jobless nowadays.</p>
												</div>
											</div>
											<div class="col-lg-2">
												<div class="proposal-amnt text-end">
													<h3>$17.00</h3>
													<p class="mb-0">in 14 days</p>
												</div>
											</div>
										</div>
									</div>
									<!-- /project proposal  -->
									
									<!-- project proposal  -->
									<div class="bids-card">
										<div class="row align-items-center">
											<div class="col-lg-2">
												<div class="author-img-wrap">
													<a href="javascript:void(0);"><img class="img-fluid" alt="" src="../../../assets/img/user/avatar-2.jpg"></a>
												</div>
											</div>
											<div class="col-lg-8">
												<div class="author-detail">
													<h4><a href="javascript:void(0);">Timothy Smith</a> <img src="../../../assets/img/flags/fr.png" height="16" alt="Lang"></h4>
													<div class="rating mapgridrating1">							
														<span class="average-rating">4.9</span>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star"></i>
													</div>
													<p class="mb-0">Look forward to hearing from you, I am a good designer and developer. I can handle your daily bases task with no extra effort. Please contact me as I am jobless nowadays.</p>
												</div>
											</div>
											<div class="col-lg-2">
												<div class="proposal-amnt text-end">
													<h3>$12.00</h3>
													<p class="mb-0">in 18 days</p>
												</div>
											</div>
										</div>
									</div>
									<!-- /project proposal  -->
									
									<!-- project proposal  -->
									<div class="bids-card">
										<div class="row align-items-center">
											<div class="col-lg-2">
												<div class="author-img-wrap">
													<a href="javascript:void(0);"><img class="img-fluid" alt="" src="../../../assets/img/user/avatar-3.jpg"></a>
												</div>
											</div>
											<div class="col-lg-8">
												<div class="author-detail">
													<h4><a href="javascript:void(0);">Janet Paden</a> <img src="../../../assets/img/flags/us.png" height="16" alt="Lang"></h4>
													<div class="rating mapgridrating1">							
														<span class="average-rating">4.2</span>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star"></i>
													</div>
													<p class="mb-0">Look forward to hearing from you, I am a good designer and developer. I can handle your daily bases task with no extra effort. Please contact me as I am jobless nowadays.</p>
												</div>
											</div>
											<div class="col-lg-2">
												<div class="proposal-amnt text-end">
													<h3>$20.00</h3>
													<p class="mb-0">in 20 days</p>
												</div>
											</div>
										</div>
									</div>
									<!-- /project proposal  -->
									
									<!-- project proposal  -->
									<div class="bids-card">
										<div class="row align-items-center">
											<div class="col-lg-2">
												<div class="author-img-wrap">
													<a href="javascript:void(0);"><img class="img-fluid" alt="" src="../../../assets/img/user/avatar-4.jpg"></a>
												</div>
											</div>
											<div class="col-lg-8">
												<div class="author-detail">
													<h4><a href="javascript:void(0);">James Douglas</a> <img src="../../../assets/img/flags/es.png" height="16" alt="Lang"></h4>
													<div class="rating mapgridrating1">							
														<span class="average-rating">3.9</span>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star"></i>
														<i class="fas fa-star"></i>
													</div>
													<p class="mb-0">Look forward to hearing from you, I am a good designer and developer. I can handle your daily bases task with no extra effort. Please contact me as I am jobless nowadays.</p>
												</div>
											</div>
											<div class="col-lg-2">
												<div class="proposal-amnt text-end">
													<h3>$10.00</h3>
													<p class="mb-0">in 22 days</p>
												</div>
											</div>
										</div>
									</div>
									<!-- /project proposal  -->
									
									<!-- project proposal  -->
									<div class="bids-card">
										<div class="row align-items-center">
											<div class="col-lg-2">
												<div class="author-img-wrap">
													<a href="javascript:void(0);"><img class="img-fluid" alt="" src="../../../assets/img/user/avatar-5.jpg"></a>
												</div>
											</div>
											<div class="col-lg-8">
												<div class="author-detail">
													<h4><a href="javascript:void(0);">Floyd Lewis</a> <img src="../../../assets/img/flags/de.png" height="16" alt="Lang"></h4>
													<div class="rating mapgridrating1">							
														<span class="average-rating">3.5</span>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star filled"></i>
														<i class="fas fa-star"></i>
														<i class="fas fa-star"></i>
													</div>
													<p class="mb-0">Look forward to hearing from you, I am a good designer and developer. I can handle your daily bases task with no extra effort. Please contact me as I am jobless nowadays.</p>
												</div>
											</div>
											<div class="col-lg-2">
												<div class="proposal-amnt text-end">
													<h3>$22.00</h3>
													<p class="mb-0">in 25 days</p>
												</div>
											</div>
										</div>
									</div>
									<!-- /project proposal  -->
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>		
			<!-- /Page Content -->
           
            <!-- Footer -->
                <layout-footer />
            <!-- /Footer -->
        </div>
        <!-- /Main Wrapper -->
        <employeemodal></employeemodal>
        </div>
</template>
<script>
export default {
     mounted() {
    
    },
}
</script>
