// template-react/src/frontend/components/foremployers/settings/index.jsx
import React , {useEffect} from "react";
import { Link } from "react-router-dom";
import StickyBox from "react-sticky-box";
import { home_icon, Img_02 } from "../../imagepath";
import { Sidebar } from '../sidebar';
    
const Settings = (props) => {   
  useEffect(() => {
    document.body.className = 'dashboard-page';
    return () => { document.body.className = ''; }
  });  
        
  return (
    <>
    {/* Breadcrumb */}
    <div className="bread-crumb-bar">
        <div className="container">
          <div className="row align-items-center inner-banner">
            <div className="col-md-12 col-12 text-center">
              <div className="breadcrumb-list">
                <nav aria-label="breadcrumb" className="page-breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item"><Link to="#"><img src={home_icon} alt="Post Author" /> Home</Link></li>
                    <li className="breadcrumb-item" aria-current="page">Employee</li>
                    <li className="breadcrumb-item" aria-current="page">Settings</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Breadcrumb */}
    {/* Page Content */}
    <div className="content content-page">
      <div className="container-fluid">
        <div className="row">
          {/* sidebar */}
          <div className="col-xl-3 col-md-4 theiaStickySidebar">
              <StickyBox offsetTop={20} offsetBottom={20}>
                <Sidebar/>
              </StickyBox>
          </div>
          {/* /sidebar */}
          <div className="col-xl-9 col-md-8">
            <div className="pro-pos">
              <nav className="user-tabs mb-4">
                <ul className="nav nav-tabs nav-tabs-bottom nav-justified">
                  <li className="nav-item">
                    <Link className="nav-link active" to="/profile-settings">
                      Basic Settings
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/change-password">
                      Change Password
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/delete-account">
                      Delete Account
                    </Link>
                  </li>
                </ul>
              </nav>
              <div className="setting-content">
                <div className="card">
                  <div className="pro-head">
                    <h3 className="pro-title without-border mb-0">
                      Profile Basics{" "}
                    </h3>
                  </div>
                  <form >
                    <div className="pro-body p-0">
                      <div className="form-row pro-pad">
                        <div className="form-group col-md-6">
                          <label>Username</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="form-group col-md-6">
                          <label>Email Address</label>
                          <input type="email" className="form-control" />
                        </div>
                        <div className="form-group col-md-6">
                          <label>Dispaly Name</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="form-group col-md-6">
                          <label>Tagline</label>
                          <input type="email" className="form-control" />
                        </div>
                        <div className="form-group col-md-6">
                          <label>Contact Number</label>
                          <input type="email" className="form-control" />
                        </div>
                        <div className="form-group col-md-6">
                          <label>Category</label>
                          <select className="form-control select">
                            <option value={0}>Male</option>
                            <option value={1}>Female</option>
                          </select>
                        </div>
                        <div className="form-group col-md-6">
                          <label>Gender</label>
                          <select className="form-control select">
                            <option value={0}>Male</option>
                            <option value={1}>Female</option>
                          </select>
                        </div>
                        <div className="form-group col-md-6">
                          <label>Language </label>
                          <input type="text" className="form-control" />
                        </div>
                      </div>
                      <div className="form-row pro-pad pt-0">
                        <div className="form-group col-md-6 pro-pic">
                          <label>Profile Picture</label>
                          <div className="d-flex align-items-center">
                            <div className="upload-images">
                              <img src={Img_02} alt="Image" />
                              <a
                                href=""
                                className="btn btn-icon btn-danger btn-sm"
                              >
                                <i className="far fa-trash-alt" />
                              </a>
                            </div>
                            <label className="file-upload image-upbtn ms-3">
                              Change Image <input type="file" />
                            </label>
                          </div>
                          <p>Image size 300*300</p>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
                <div className="card">
                  <div className="pro-head">
                    <h3 className="pro-title without-border mb-0">Location</h3>
                  </div>
                  <div className="pro-body">
                    <div className="row">
                      <div className="form-group col-md-12">
                        <label>Address</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>State</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Zipcode</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Country</label>
                        <select className="form-control select">
                          <option value={0}>India</option>
                          <option value={1}>China</option>
                          <option value={2}>Japan</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card">
                  <div className="pro-head">
                    <h3 className="pro-title without-border mb-0">Overview</h3>
                  </div>
                  <div className="pro-body">
                    <div className="row">
                      <div className="form-group col-md-12">
                        <textarea
                          className="form-control"
                          rows={5}
                          defaultValue={""}
                        />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card">
                  <div className="pro-head">
                    <h3 className="pro-title without-border mb-0">
                      Social Links
                    </h3>
                  </div>
                  <div className="pro-body">
                    <div className="row">
                      <div className="form-group col-md-6">
                        <label>Facebook</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Dribble</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Twitter</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>LinkedIn</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Behance</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Behance</label>
                        <input type="text" className="form-control" />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card">
                  <div className="text-end">
                    <div className="pro-body">
                      <button
                        className="btn btn-secondary click-btn btn-plan"
                        type="submit"
                      >
                        Cancel
                      </button>&nbsp;
                      <button
                        className="btn btn-primary click-btn btn-plan"
                        type="submit"
                      >
                        Update
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* /Page Content */}
  </>
      )
  
}
export default Settings;

// template-vuejs/src/views/admin/main/settings/settings.vue
<template>
    <div>
    <!-- Main Wrapper -->
        <div class="main-wrapper">
            <layout-adminheader></layout-adminheader>
			<layout-adminsidebar></layout-adminsidebar>
			
				<!-- Page Wrapper -->
                <div class="page-wrapper">
                    <div class="content container-fluid">
                        <div class="page-header">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h3 class="page-title">Settings</h3>
                                    <ul class="breadcrumb">
                                        <li class="breadcrumb-item"><router-link to="/admin/index">Home</router-link></li>
                                        <li class="breadcrumb-item"><router-link to="/admin/settings">Settings</router-link></li>
                                        <li class="breadcrumb-item active">General Settings</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    
                        <div class="row">
                            <div class="col-lg-12">
    
                                <!-- Settings Menu -->
                                <div class="settings-menu-links">
                                    <ul class="nav nav-tabs menu-tabs">
                                        <li class="nav-item active">
                                            <router-link class="nav-link" to="/admin/settings">General Settings</router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link class="nav-link" to="/admin/localization-details">Localization</router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link class="nav-link" to="/admin/payment-settings">Payment Settings</router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link class="nav-link" to="/admin/email-settings">Email Settings</router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link class="nav-link" to="/admin/social-settings">Social Media Login</router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link class="nav-link" to="/admin/social-links">Social Links</router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link class="nav-link" to="/admin/seo-settings">SEO Settings</router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link class="nav-link" to="/admin/others-settings">Others</router-link>
                                        </li>
                                    </ul>
                                </div>
                                <!-- Settings Menu -->
    
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="card">
                                            <div class="card-body pt-0">
                                                <div class="card-header">
                                                    <h5 class="card-title">Website Basic Details</h5>
                                                </div>
                                                <form>
                                                    <div class="settings-form">
                                                        <div class="form-group">
                                                            <label>Website Name <span class="star-red">*</span></label>
                                                            <input type="text" class="form-control" placeholder="Enter Website Name">
                                                        </div>
                                                        <div class="form-group">
                                                            <p class="settings-label">Logo <span class="star-red">*</span></p>
                                                            <div class="settings-btn">
                                                                <input type="file" accept="image/*" name="image" id="file"  onchange="loadFile(event)" class="hide-input">
                                                                <label for="file" class="upload">
                                                                    <i class="feather-upload"></i>
                                                                </label>
                                                            </div>
                                                            <h6 class="settings-size">Recommended image size is <span>150px x 150px</span></h6>
                                                            <div class="upload-images">
                                                                <img src="../../../../assets/admin-img/logo.png" alt="Image">
                                                                <a href="javascript:void(0);" class="btn-icon logo-hide-btn">
                                                                    <i class="feather-x-circle"></i>
                                                                </a>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <p class="settings-label">Favicon <span class="star-red">*</span></p>
                                                            <div class="settings-btn">
                                                                <input type="file" accept="image/*" name="image" id="file"  onchange="loadFile(event)" class="hide-input">
                                                                <label for="file" class="upload">
                                                                    <i class="feather-upload"></i>
                                                                </label>
                                                            </div>
                                                            <h6 class="settings-size">
                                                                Recommended image size is <span>16px x 16px or 32px x 32px</span>
                                                            </h6>
                                                            <h6 class="settings-size mt-1">Accepted formats: only png and ico</h6>
                                                            <div class="upload-images upload-size">
                                                                <img src="../../../../assets/admin-img/favicon.png" alt="Image">
                                                                <a href="javascript:void(0);" class="btn-icon logo-hide-btn">
                                                                    <i class="feather-x-circle"></i>
                                                                </a>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-5 col-md-6">
                                                                <div class="form-group">
                                                                    <div class="status-toggle d-flex justify-content-between align-items-center">
                                                                        <p class="mb-0">RTL</p>
                                                                        <input type="checkbox" id="status_1" class="check">
                                                                        <label for="status_1" class="checktoggle">checkbox</label>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="form-group mb-0">
                                                            <div class="settings-btns">
                                                                <button type="submit" class="btn btn-orange">Update</button>
                                                                <button type="submit" class="btn btn-grey">Cancel</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
    
                                    <div class="col-md-6">
                                        <div class="card">
                                            <div class="card-body pt-0">
                                                <div class="card-header">
                                                    <h5 class="card-title">Address Details</h5>
                                                </div>
                                                <form>
                                                    <div class="settings-form">
                                                        <div class="form-group">
                                                            <label>Address Line 1 <span class="star-red">*</span></label>
                                                            <input type="text" class="form-control" placeholder="Enter Address Line 1">
                                                        </div>
                                                        <div class="form-group">
                                                            <label>Address Line 2 <span class="star-red">*</span></label>
                                                            <input type="text" class="form-control" placeholder="Enter Address Line 2">
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label>City <span class="star-red">*</span></label>
                                                                    <input type="text" class="form-control">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label>State/Province <span class="star-red">*</span></label>
                                                                    <vue-select :options="state" />
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label>Zip/Postal Code <span class="star-red">*</span></label>
                                                                    <input type="text" class="form-control">
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label>Country <span class="star-red">*</span></label>
                                                                    <vue-select :options="country" />
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="form-group mb-0">
                                                            <div class="settings-btns">
                                                                <button type="submit" class="btn btn-orange">Update</button>
                                                                <button type="submit" class="btn btn-grey">Cancel</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Page Wrapper -->
		
        </div>
		<!-- /Main Wrapper -->

    </div>
</template>
<script>
	export default {
		 mounted() {
		},
		methods:{
		},
		data() {
			return {
                state: ["Select", "California", "Tasmania", "Auckland", "Marlborough"],
                country: ["Select", "India", "London", "France", "USA"]
			}
		}
	}
	</script>
