// template-vuejs/src/views/frontend/employer/withdrawmoney.vue
<template>
<div class="dashboard-page">
       <!-- Main Wrapper -->
        <div class="main-wrapper">
			<!-- Header -->
                <layout-employeeheader />
			<!-- /Header -->

            <!-- Page Content --> 
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						
						<!-- sidebar -->
						<div class="col-xl-3 col-md-4 theiaStickySidebar">
                            <div class="stickyside">
							<div class="settings-widget">
								<div class="settings-header d-sm-flex flex-row flex-wrap text-center text-sm-start align-items-center">
									<router-link to="/user-account-details"><img alt="profile image" src="../../../assets/img/img-04.jpg" class="avatar-lg rounded-circle"></router-link>
									<div class="ms-sm-3 ms-md-0 ms-lg-3 mt-2 mt-sm-0 mt-md-2 mt-lg-0">
										<p class="mb-2">Welcome,</p>
										<router-link to="/user-account-details"><h3 class="mb-0">John Danie S.</h3></router-link>
										<p class="mb-0">@johndaniee</p>
									</div>
								</div>
								<div class="settings-menu">
									<ul>
										<li class="nav-item">
											<router-link to="/dashboard" class="nav-link">
												<i class="material-icons">verified_user</i> Dashboard
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/manage-projects" class="nav-link">
												<i class="material-icons">business_center</i> Projects
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/favourites" class="nav-link">
												<i class="material-icons">local_play</i> Favourites
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/review" class="nav-link">
												<i class="material-icons">record_voice_over</i> Reviews
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/chats" class="nav-link">
												<i class="material-icons">chat</i> Messages
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/membership-plans" class="nav-link">
												<i class="material-icons">person_add</i> Membership
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/milestones" class="nav-link">
												<i class="material-icons">pie_chart</i> Milestones
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/verify-identity" class="nav-link">
												<i class="material-icons">person_pin</i> Verify Identity
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/deposit-funds" class="nav-link active">
												<i class="material-icons">wifi_tethering</i> Payments
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/profile-settings" class="nav-link">
												<i class="material-icons">settings</i> Settings
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/index" class="nav-link">
												<i class="material-icons">power_settings_new</i> Logout
                                            </router-link>
										</li>
									</ul>
								</div>
							</div>	
                            </div>				
						</div>
						<!-- /sidebar -->
						
						<div class="col-xl-9 col-md-8">
							<div class="row">
								<div class="col-md-12">							
									<nav class="user-tabs mb-4">
										<ul class="nav nav-tabs nav-tabs-bottom nav-justified">
											<li class="nav-item">
												<router-link class="nav-link" to="/deposit-funds">Deposit Funds</router-link>
											</li>
											<li class="nav-item">
												<router-link class="nav-link active" to="/withdraw-money">Withdraw Money</router-link>
											</li>
											<li class="nav-item">
												<router-link class="nav-link" to="/transaction-history">Transaction History</router-link>
											</li>
										</ul>
									</nav>
								</div>
								<div class="col-md-12">							
									<div class="transaction-position">
										<h3 class="mb-0">Withdraw Amount</h3>
									</div>
								</div>
								
								<!-- /Add Wallet -->
								<div class="col-md-12">
									<div class="card">
										<div class="payment-list wallet card-body">
											<h3>Add Wallet</h3>
											<div class="form-group profile-group">
												<div class="input-group">
													<div class="input-group-prepend">
														<button class="btn dol-btn" type="submit">$</button>
													</div>
													<input type="text" class="form-control">										
												</div>
											</div>
											<label class="custom_radio me-4">
												<input type="radio" value="Yes" checked="">
												<span class="checkmark"></span> Paypal
											</label>
											<label class="custom_radio">
												<input type="radio" value="Yes">
												<span class="checkmark"></span> Card
											</label>
											<div class="bootstrap-tags text-start ps-0">
												<span class="badge badge-pill badge-skills">$50</span> 
												<span class="badge badge-pill badge-skills">$100</span> 
												<span class="badge badge-pill badge-skills">$150</span> 
											</div>
															
											<div class="row">
												<div class="col-md-12">
													<div class="form-group">
														<label for="card_number">Card Number</label>
														<input class="form-control" id="card_number" type="text">
													</div>
												</div>
												<div class="col-md-6">
													<div class="form-group">
														<label for="first_name">First Name</label>
														<input class="form-control" id="first_name" type="text">
													</div>
												</div>
												<div class="col-md-6">
													<div class="form-group">
														<label for="last_name">Last Name</label>
														<input class="form-control" id="last_name" type="text">
													</div>
												</div>
												<div class="col-md-4">
													<div class="form-group">
														<label for="expiry_on">Expires on</label>
														<input class="form-control" id="expiry_on" type="text">
													</div>
												</div>
												<div class="col-md-8">
													<div class="form-group">
														<label for="cvv">CVV (Security Code) </label>
														<input class="form-control" id="cvv" type="text">
													</div>
												</div>
												<div class="col-md-8 btn-pad">
													<a href="javascript:void(0);" class="click-btn btn-primary">Continue</a>
												</div>
											</div>
										</div>			
									</div>											
								</div>	
								<!-- /Add Wallet -->
								
								<!-- Wallet -->
								<div class="col-md-6">					
									<div class="card">		
										<div class="wallet-detail card-body">
											<div class="wallet-title pt-0 ps-0">
												<h3 class="mb-0">Wallet</h3>
											</div>
											<div class="wallet-bal">
												<span class="dol-circle"><i class="fa fa-dollar-sign" aria-hidden="true"></i></span>
												<div class="wallet-amt">
													<p>Available Balance</p>
													<h3 class="mb-0">$250.60 </h3>
												</div>
											</div>
											<div class="wallet-content">
												<div class="wallet-pay">
													<p>Total Credit</p>
													<h3 class="mb-0">$500.00</h3>
												</div>
												<div class="wallet-pay">
													<p>Total Credit</p>
													<h3 class="mb-0">$500.00</h3>
												</div>
											</div>
										</div>
									</div>
								</div>
								<!-- /Wallet -->
							</div>						
						</div>						
					</div>
				</div>
			</div>				
			<!-- /Page Content -->
           
            <!-- Footer -->
                <layout-footer />
            <!-- /Footer -->
        </div>
        <!-- /Main Wrapper -->

        </div>
</template>
<script>
	export default {
		 mounted() {
		
		},
		methods:{
		},
		data() {
			return {
			}
		}
	}
	</script>

// template-react/src/frontend/components/foremployers/withdrawmoney/index.jsx
import React , {useEffect} from "react";
import { Link } from "react-router-dom";
import StickyBox from "react-sticky-box";
import { home_icon } from "../../imagepath";
import { Sidebar } from '../sidebar';
    
const Withdrawmoney = (props) => {  
  useEffect(() => {
    document.body.className = 'dashboard-page';
    return () => { document.body.className = ''; }
  });   
        
  return (
        <>
        {/* Breadcrumb */}
    <div className="bread-crumb-bar">
        <div className="container">
          <div className="row align-items-center inner-banner">
            <div className="col-md-12 col-12 text-center">
              <div className="breadcrumb-list">
                <nav aria-label="breadcrumb" className="page-breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item"><Link to="#"><img src={home_icon} alt="Post Author" /> Home</Link></li>
                    <li className="breadcrumb-item" aria-current="page">FREELANCER
</li>
                    <li className="breadcrumb-item" aria-current="page">PAYMENTS</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Breadcrumb */}
         {/* Page Content */}
  <div className="content content-page">
    <div className="container-fluid">
      <div className="row">
        {/* sidebar */}
        <div className="col-xl-3 col-md-4 theiaStickySidebar">
             <StickyBox offsetTop={20} offsetBottom={20}>
                <Sidebar/>
              </StickyBox>
        </div>
        {/* /sidebar */}
        <div className="col-xl-9 col-md-8">
          <div className="row">
            <div className="col-md-12">
              <nav className="user-tabs mb-4">
                <ul className="nav nav-tabs nav-tabs-bottom nav-justified">
                  <li className="nav-item">
                    <Link className="nav-link" to="/deposit-funds">
                      Deposit Funds
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link active" to="/withdraw-money">
                      Withdraw Money
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/transaction-history">
                      Transaction History
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>
            <div className="col-md-12">
              <div className="transaction-position">
                <h3 className="mb-0">Withdraw Amount</h3>
              </div>
            </div>
            {/* /Add Wallet */}
            <div className="col-md-12">
              <div className="card">
                <div className="payment-list wallet card-body">
                  <h3>Add Wallet</h3>
                  <div className="form-group profile-group">
                    <div className="input-group">
                      <div className="input-group-prepend">
                        <button className="btn dol-btn" type="submit">
                          $
                        </button>
                      </div>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  <label className="custom_radio me-4">
                    <input type="radio" defaultValue="Yes" defaultChecked />
                    <span className="checkmark" /> Paypal
                  </label>
                  <label className="custom_radio">
                    <input type="radio" defaultValue="Yes" />
                    <span className="checkmark" /> Card
                  </label>
                  <div className="bootstrap-tags text-start ps-0">
                    <span className="badge badge-pill badge-skills">$50</span>
                    <span className="badge badge-pill badge-skills">$100</span>
                    <span className="badge badge-pill badge-skills">$150</span>
                  </div>
                  <div className="row">
                    <div className="col-md-12">
                      <div className="form-group">
                        <label htmlFor="card_number">Card Number</label>
                        <input
                          className="form-control"
                          id="card_number"
                          type="text"
                        />
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="form-group">
                        <label htmlFor="first_name">First Name</label>
                        <input
                          className="form-control"
                          id="first_name"
                          type="text"
                        />
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="form-group">
                        <label htmlFor="last_name">Last Name</label>
                        <input
                          className="form-control"
                          id="last_name"
                          type="text"
                        />
                      </div>
                    </div>
                    <div className="col-md-4">
                      <div className="form-group">
                        <label htmlFor="expiry_on">Expires on</label>
                        <input
                          className="form-control"
                          id="expiry_on"
                          type="text"
                        />
                      </div>
                    </div>
                    <div className="col-md-8">
                      <div className="form-group">
                        <label htmlFor="cvv">CVV (Security Code) </label>
                        <input className="form-control" id="cvv" type="text" />
                      </div>
                    </div>
                    <div className="col-md-8 btn-pad">
                      <a href="#" className="click-btn btn-primary">
                        Continue
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Add Wallet */}
            {/* Wallet */}
            <div className="col-md-6">
              <div className="card">
                <div className="wallet-detail card-body">
                  <div className="wallet-title pt-0 ps-0">
                    <h3 className="mb-0">Wallet</h3>
                  </div>
                  <div className="wallet-bal">
                    <span className="dol-circle">
                      <i className="fa fa-dollar-sign" aria-hidden="true" />
                    </span>
                    <div className="wallet-amt">
                      <p>Available Balance</p>
                      <h3 className="mb-0">$250.60 </h3>
                    </div>
                  </div>
                  <div className="wallet-content">
                    <div className="wallet-pay">
                      <p>Total Credit</p>
                      <h3 className="mb-0">$500.00</h3>
                    </div>
                    <div className="wallet-pay">
                      <p>Total Credit</p>
                      <h3 className="mb-0">$500.00</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Wallet */}
          </div>
        </div>
      </div>
    </div>
  </div>
  {/* /Page Content */}
        </>
      )
  
}
export default Withdrawmoney;
