// template-vuejs/src/views/admin/main/settings/deleteaccount.vue
<template>
    <div>
    <!-- Main Wrapper -->
        <div class="main-wrapper">
            <layout-adminheader></layout-adminheader>
			<layout-adminsidebar></layout-adminsidebar>
			
			<!-- Page Wrapper -->
			<div class="page-wrapper">
				<div class="content container-fluid">
				
					<div class="page-header">
						<div class="row">
							<div class="col-sm-6">
								<h3 class="page-title">Settings</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/admin/index">Dashboard</router-link>
									</li>
									<li class="breadcrumb-item active">Delete Account</li>
								</ul>
							</div>
						</div>
					</div>
					
					<div class="row">
						<div class="col-xl-3 col-md-4">
						
							<!-- Settings Menu -->
							<div class="widget settings-menu">
								<ul>
									<li class="nav-item">
										<router-link to="/admin/settings" class="nav-link">
											<i class="far fa-user"></i> <span>Profile Settings</span>
                                        </router-link>
									</li>
									<li class="nav-item">
										<router-link to="/admin/tax-types" class="nav-link">
											<i class="far fa-check-square"></i> <span>Tax Types</span>
                                        </router-link>
									</li>
									<li class="nav-item">
										<router-link to="/admin/change-password" class="nav-link">
											<i class="fas fa-unlock-alt"></i> <span>Change Password</span>
                                        </router-link>
									</li>
									<li class="nav-item">
										<router-link to="/admin/delete-account" class="nav-link active">
											<i class="fas fa-ban"></i> <span>Delete Account</span>
                                        </router-link>
									</li>
								</ul>
							</div>
							<!-- /Settings Menu -->
							
						</div>
						
						<div class="col-xl-9 col-md-8">
							<div class="card">
								<div class="card-body pt-0">
									<div class="card-header mb-4">
										<h5 class="card-title">Delete your account</h5>
									</div>
								
									<!-- Form -->
									<form>
										<p class="card-text">When you delete your account, you lose access to Kanakku account services, and we permanently delete your personal data.</p>
										<p class="card-text">Are you sure you want to close your account?</p>

										<div class="form-group">
											<div class="form-check form-checkbox">
												<input type="checkbox" class="form-check-input" id="delete_account">
												<label class="form-check-label text-danger" for="delete_account">Confirm that I want to delete my account.</label>
											</div>
										</div>

										<div class="text-end">
											<button type="submit" class="btn btn-primary">Save Changes</button>
										</div>
									</form>
									<!-- /Form -->
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Page Wrapper -->
		
        </div>
		<!-- /Main Wrapper -->

    </div>
</template>

// template-react/src/frontend/components/foremployers/deleteaccount/index.jsx
import React , {useEffect} from "react";
import { Link } from "react-router-dom";
import StickyBox from "react-sticky-box";
import { home_icon } from "../../imagepath";
import { Sidebar } from '../sidebar';
    
const DeleteAccount = (props) => {   
    useEffect(() => {
      document.body.className = 'dashboard-page';
      return () => { document.body.className = ''; }
    });  
        
  return (
    <>
    {/* Breadcrumb */}
    <div className="bread-crumb-bar">
        <div className="container">
          <div className="row align-items-center inner-banner">
            <div className="col-md-12 col-12 text-center">
              <div className="breadcrumb-list">
                <nav aria-label="breadcrumb" className="page-breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item"><Link to="index.html"><img src={home_icon} alt="Post Author" /> Home</Link></li>
                    <li className="breadcrumb-item" aria-current="page">Employee</li>
                    <li className="breadcrumb-item" aria-current="page">Settings</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    {/* /Breadcrumb */}
    {/* Page Content */}
    <div className="content">
      <div className="container-fluid">
        <div className="row">
          <div className="col-xl-3 col-md-4 theiaStickySidebar">
             <StickyBox offsetTop={20} offsetBottom={20}>
                <Sidebar/>
              </StickyBox>
          </div>
          <div className="col-xl-9 col-md-8">
            <nav className="user-tabs mb-4">
              <ul className="nav nav-tabs nav-tabs-bottom nav-justified">
                <li className="nav-item">
                    <Link className="nav-link" to="/profile-settings">
                      Basic Settings
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/change-password">
                      Change Password
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link active" to="/delete-account">
                      Delete Account
                    </Link>
                  </li>
              </ul>
            </nav>
            <div className="setting-content">
              <div className="pro-card">
                <div className="pro-head">
                  <h3 className="pro-title without-border mb-0">
                    Delete Account
                  </h3>
                </div>
                <div className="pro-body">
                  <form >
                    <div className="form-group">
                      <label>Please Explain Further**</label>
                      <textarea
                        className="form-control"
                        rows={5}
                        defaultValue={""}
                      />
                    </div>
                    <div className="form-group">
                      <label>Password*</label>
                      <input type="password" className="form-control" />
                    </div>
                    <div className="row">
                      <div className="col-md-12">
                        <a
                          className="btn btn-primary click-btn btn-plan"
                          data-bs-toggle="modal"
                          href="#delete-acc"
                        >
                          Delete Account
                        </a>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* /Page Content */}
     {/* The Modal */}
  <div className="modal fade custom-modal" id="delete-acc">
    <div className="modal-dialog modal-dialog-centered modal-md">
      <div className="modal-content">
        <div className="modal-body del-modal">
          <form>
            <div className="text-center pt-0 mb-5">
              <i className="fas fa-exclamation-triangle fa-3x" />
              <h3>Are you sure? Want to delete Account</h3>
            </div>
            <div className="submit-section text-center">
              <button
                data-bs-dismiss="modal"
                className="btn btn-primary black-btn click-btn"
              >
                Cancel
              </button>&nbsp;
              <button type="submit" className="btn btn-primary click-btn">
                Submit
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {/* /The Modal */}
  </>
      )
  
}
export default DeleteAccount;
