// template-react/src/frontend/components/CompanyDetails/company-gallery.jsx
import React from "react";
import { Link } from "react-router-dom";
import SimpleReactLightbox from "simple-react-lightbox";
import { about_details, home_icon, logo_details, profile_details, Tab_icon_01, Tab_icon_08, Tab_icon_09, Tab_icon_10, Tab_icon_11 } from "../imagepath";
import GalleryComponent from "./galleryComponents";





const CompanyGallery = () => {
    return (
        <>
            {/* Breadcrumb */}
            <div className="bread-crumb-bar">
                <div className="container">
                    <div className="row align-items-center inner-banner">
                        <div className="col-md-12 col-12 text-center">
                            <div className="breadcrumb-list">
                                <nav aria-label="breadcrumb" className="page-breadcrumb">
                                    <ol className="breadcrumb">
                                        <li className="breadcrumb-item"><Link to="#"><img src={home_icon} alt="" /> Home</Link></li>
                                        <li className="breadcrumb-item" aria-current="page">Employers</li>
                                        <li className="breadcrumb-item active" aria-current="page">COMPANY PROFILE</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Breadcrumb */}
            {/* Profile Banner */}
            <section className="profile-baner">
                <div className="container">
                    <div className="row">
                        <div className="col-auto">
                            <div className="profile-img">
                                <img src={profile_details} alt="" />
                            </div>
                        </div>
                        <div className="col">
                            <div className="profile-main">
                                <h2>Amaze Tech  PVT LTD. <i className="fas fa-check-circle" /></h2>
                                <p>Since July 2017</p>
                                <div className="about-list">
                                    <ul>
                                        <li><img src={logo_details} alt="Lang" /> UK</li>
                                        <li><i className="fas fa-map-marker-alt" /> Alabama, USA</li>
                                        <li><i className="far fa-clock" /> Poster 1 hour ago</li>
                                    </ul>
                                </div>
                                <div className="rating">
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star filled" />
                                    <i className="fas fa-star " />
                                    <i className="fas fa-star" />
                                    <span className="average-rating ml-2"> 4.6 (25)</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {/* Profile Banner */}
            {/* Page Content */}
            <div className="content">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-8 col-md-12">
                            <div className="pro-view">
                                {/* Tab Detail */}
                                <nav className="provider-tabs mb-4 abouts-view">
                                    <ul className="nav nav-tabs nav-tabs-solid nav-justified">
                                        <li className="nav-item">
                                            <Link className="nav-link " to="/company-details">
                                                <img src={about_details} alt="User Image" />
                                                <p className="bg-red">About Us</p>
                                            </Link>
                                        </li>
                                        <li className="nav-item">
                                            <Link className="nav-link" to="/company-project">
                                                <img src={Tab_icon_09} alt="User Image" />
                                                <p>Projects</p>
                                            </Link>
                                        </li>
                                        <li className="nav-item ">
                                            <Link className="nav-link active-about" to="#">
                                                <img src={Tab_icon_10} alt="User Image" />
                                                <p>Gallery</p>
                                            </Link>
                                        </li>
                                        <li className="nav-item">
                                            <Link className="nav-link" to="/company-review">
                                                <img src={Tab_icon_11} alt="User Image" />
                                                <p>Reviews</p>
                                            </Link>
                                        </li>
                                    </ul>
                                </nav>
                                {/* /Tab Detail */}
                                {/* About Tab Content */}
                                <div className="pro-post widget-box company-post">
                                    <h3 className="pro-title">Gallery</h3>
                                    <div className="pro-content company-gallery">
                                        <SimpleReactLightbox>
                                            <GalleryComponent/>
                                        </SimpleReactLightbox>
                                    </div>
                                </div>
                                {/* /About Tab Content */}
                            </div>
                        </div>
                        {/* profile Sidebar */}
                        <div className="col-lg-4 col-md-12 sidebar-right theiaStickySidebar company-profile">
                            {/* About Widget */}
                            <div className="pro-post widget-box about-widget profile-overview">
                                <div className="profile-head">
                                    <h4 className="pro-title mb-0">Profile Overview</h4>
                                </div>
                                <ul className="latest-posts pro-content">
                                    <li><p>Company Name</p><h6>Amaze Tech  PVT LTD.</h6></li>
                                    <li><p>Company Established</p><h6>02-12-2005</h6></li>
                                    <li><p>No of Employees</p><h6>1500 - 1850</h6></li>
                                    <li><p>Owner Name</p><h6>Charles Dickens</h6></li>
                                    <li><p>Email</p><h6>amazetechpvt.ltd@gmail.com</h6></li>
                                    <li><p>Website</p><h6>www.amazetechpvt.ltd.com</h6></li>
                                </ul>
                                <div className="contact-btn">
                                    <Link to="#" className="btn btn-primary"><i className="fas fa-phone-alt" /> Contact</Link>
                                </div>
                            </div>
                            {/* /About Widget */}
                            {/* Company Location */}
                            <div className="pro-post widget-box location-widget">
                                <div className="profile-head">
                                    <h4 className="pro-title">Company Location</h4>
                                </div>
                                <div className="map-location">
                                    <iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d2965.0824050173574!2d-93.63905729999999!3d41.998507000000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sWebFilings%2C+University+Boulevard%2C+Ames%2C+IA!5e0!3m2!1sen!2sus!4v1390839289319" />
                                </div>
                            </div>
                            {/* /Company Location */}
                            {/* Working Widget */}
                            <div className="pro-post widget-box  working-days">
                                <div className="profile-head">
                                    <h4 className="pro-title mb-0">Working Days</h4>
                                </div>
                                <ul className="latest-posts pro-content">
                                    <li><p>Monday</p><h6>9AM - 5PM</h6></li>
                                    <li><p>Tuesday </p><h6>9AM - 5PM</h6></li>
                                    <li><p>Wednesday </p><h6>9AM - 5PM</h6></li>
                                    <li><p>Thursday </p><h6>9AM - 5PM</h6></li>
                                    <li><p>Friday </p><h6>9AM - 5PM</h6></li>
                                    <li><p>Saturday </p><h6>9AM - 5PM</h6></li>
                                    <li><p>Sunday </p><h6><span>Close</span></h6></li>
                                </ul>
                            </div>
                            {/* /Working Widget */}
                            {/* Social Widget */}
                            <div className="pro-post widget-box social-widget">
                                <div className="profile-head">
                                    <h4 className="pro-title">SOCIAL LINKS</h4>
                                </div>
                                <ul className="social-link-profile">
                                    <li><Link to="#"><i className="fab fa-facebook" /></Link></li>
                                    <li><Link to="#"><i className="fab fa-twitter" /></Link></li>
                                    <li><Link to="#"><i className="fab fa-instagram" /></Link></li>
                                    <li><Link to="#"><i className="fab fa-linkedin" /></Link></li>
                                    <li><Link to="#"><i className="fab fa-telegram" /></Link></li>
                                </ul>
                            </div>
                            {/* /Social Widget */}
                        </div>
                        {/* /Profile Sidebar */}
                    </div>
                </div>
            </div>
            {/* /Page Content */}
        </>
    );
}
export default CompanyGallery;

// template-angular/src/app/features-modules/employer/company-profile/company-gallery/company-gallery.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-company-gallery',
  templateUrl: './company-gallery.component.html',
  styleUrls: ['./company-gallery.component.scss']
})
export class CompanyGalleryComponent implements OnInit {

  constructor() { }

  images = [
    {
      path: 'assets/img/gallery-10.jpg',
    },
    {
      path: 'assets/img/gallery-3.jpg'
    },
    {
      path: 'assets/img/gallery-4.jpg',
    },
    {
      path: 'assets/img/gallery-5.jpg'
    },
    {
      path: 'assets/img/gallery-6.jpg',
    },
    {
      path: 'assets/img/gallery-7.jpg'
    },
    {
      path: 'assets/img/gallery-8.jpg'
    },
    {
      path: 'assets/img/gallery-9.jpg',
    },
    {
      path: 'assets/img/gallery-11.jpg'
    }
  ]

  ngOnInit(): void {
  }

}

			<!-- Breadcrumb -->
			<div class="bread-crumb-bar">
				<div class="container">
					<div class="row align-items-center inner-banner">
						<div class="col-md-12 col-12 text-center">
							<div class="breadcrumb-list">
								<nav aria-label="breadcrumb" class="page-breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><a [routerLink]="'/home'"><img src="assets/img/home-icon.svg" alt=""> Home</a></li>
										<li class="breadcrumb-item" aria-current="page">Employers</li>
										<li class="breadcrumb-item active" aria-current="page">COMPANY PROFILE</li>
									</ol>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Profile Banner -->
			<section class="profile-baner">
				<div class="container">
					<div class="row">
						<div class="col-auto">
							<div class="profile-img">
								<img src="assets/img/profile.jpg"  alt="">
							</div>
						</div>
						<div class="col">
							<div class="profile-main">
								<h2>Amaze Tech  PVT LTD. <i class="fas fa-check-circle"></i></h2>
								<p>Since July 2017</p>
								<div class="about-list">
									<ul>
										<li><img src="assets/img/en.png"  alt="Lang"> UK</li>
										<li><i class="fas fa-map-marker-alt"></i> Alabama, USA</li>
										<li><i class="far fa-clock"></i> Poster 1 hour ago</li>
									</ul>
								</div>
								<div class="rating">		
									<i class="fas fa-star filled"></i>
									<i class="fas fa-star filled"></i>
									<i class="fas fa-star filled"></i>
									<i class="fas fa-star "></i>
									<i class="fas fa-star"></i>
									<span class="average-rating">4.6 (25)</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<!-- Profile Banner -->
			
			<!-- Page Content -->
			<div class="content content-page">
				<div class="container">	
					<div class="row">
						<div class="col-lg-8 col-md-12">
							<div class="pro-view">
								
								<!-- Tab Detail -->
                                <nav class="provider-tabs abouts-view">
									<ul class="nav nav-tabs nav-tabs-solid nav-justified">
										<li class="nav-item">
											<a class="nav-link " [routerLink]="'/employer/company-profile'">
												<img src="assets/img/icon/tab-icon-01.png"  alt="User Image">
												<p class="bg-red">About Us</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" [routerLink]="'/employer/company-project'">
												<img src="assets/img/icon/tab-icon-09.png"  alt="User Image">
												<p >Projects</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link active-about" [routerLink]="'/employer/company-gallery'">
												<img src="assets/img/icon/tab-icon-10.png"  alt="User Image">
												<p>Gallery</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" [routerLink]="'/employer/company-reviews'">
												<img src="assets/img/icon/tab-icon-11.png"  alt="User Image">
												<p>Reviews</p>
											</a>
										</li>
									</ul>
								</nav>
								<!-- /Tab Detail -->
								
								<!-- About Tab Content -->
								<div class="pro-post widget-box company-post" >
									<h3 class="pro-title">Gallery</h3>
									<div class="pro-content company-gallery">
										<div class="row">
											<div class="col-sm-6 col-md-6 col-lg-4 col-xl-4"  *ngFor = "let image of images">
												<div class="project-widget">
													<div class="pro-image">													
														<a href="{{image.path}}" data-lightbox="gallery1">
															<img class="img-fluid" alt="User Image" src="{{image.path}}">
															<div class="view-gallery">
																<i class="far fa-eye"></i>
															</div>
														</a>
													</div>
												</div>
											</div>
											<div class="col-md-12 text-center">
												<a href="#" class="btn more-btn"><img src="assets/img/loader-icon.svg" height="24" alt="User Image">Load More </a>
											</div>
										</div>
									</div>
								</div>
								<!-- /About Tab Content -->
								
							</div>
						</div>
					
						<!-- profile Sidebar -->
						<div class="col-lg-4 col-md-12 sidebar-right   company-profile">	

							<!-- About Widget -->	
							<div class="pro-post widget-box about-widget profile-overview">
								<div class="profile-head">
									<h4 class="pro-title mb-0">Profile Overview</h4>
								</div>
								<ul class="latest-posts pro-content">
									<li><p>Company Name</p><h6>Amaze Tech  PVT LTD.</h6></li>
									<li><p>Company Established</p><h6>02-12-2005</h6></li>
									<li><p>No of Employees</p><h6>1500 - 1850</h6></li>
									<li><p>Owner Name</p><h6>Charles Dickens</h6></li>
									<li><p>Email</p><h6>amazetechpvt.ltd@gmail.com</h6></li>
									<li><p>Website</p><h6>www.amazetechpvt.ltd.com</h6></li>
								</ul>
								<div class="contact-btn">
									<a href="#" class="btn btn-primary"><i class="fas fa-phone-alt"></i> Contact</a>
								</div>
							</div>
							<!-- /About Widget -->
							
							<!-- Company Location -->	
							<div class="pro-post widget-box location-widget">
								<div class="profile-head">
									<h4 class="pro-title">Company Location</h4>
								</div>
								<div class="map-location">
									<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d2965.0824050173574!2d-93.63905729999999!3d41.998507000000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sWebFilings%2C+University+Boulevard%2C+Ames%2C+IA!5e0!3m2!1sen!2sus!4v1390839289319" ></iframe>
								</div>
							</div>
							<!-- /Company Location -->
							
							<!-- Working Widget -->	
							<div class="pro-post widget-box  working-days">
								<div class="profile-head">
									<h4 class="pro-title mb-0">Working Days</h4>
								</div>
								<ul class="latest-posts pro-content">
									<li><p>Monday</p><h6>9AM - 5PM</h6></li>
									<li><p>Tuesday </p><h6>9AM - 5PM</h6></li>
									<li><p>Wednesday </p><h6>9AM - 5PM</h6></li>
									<li><p>Thursday </p><h6>9AM - 5PM</h6></li>
									<li><p>Friday </p><h6>9AM - 5PM</h6></li>
									<li><p>Saturday </p><h6>9AM - 5PM</h6></li>
									<li><p>Sunday </p><h6><span>Close</span></h6></li>
								</ul>
							</div>
							<!-- /Working Widget -->	
							
							<!-- Social Widget -->	
							<div class="pro-post widget-box social-widget">
								<div class="profile-head">
									<h4 class="pro-title">SOCIAL LINKS</h4>
								</div>
								<ul class="social-link-profile">
									<li><a href="#"><i class="fab fa-facebook"></i></a></li>
									<li><a href="#"><i class="fab fa-twitter"></i></a></li>
									<li><a href="#"><i class="fab fa-instagram"></i></a></li>
									<li><a href="#"><i class="fab fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fab fa-telegram"></i></a></li>
								</ul>
							</div>
							<!-- /Social Widget -->
						
						</div>
						<!-- /Profile Sidebar -->
						
					</div>
				</div>
			</div>		
			<!-- /Page Content -->
