// template-angular/src/app/features-modules/freelancer/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss']
})
export class ProfileComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  scroll(el: HTMLElement) {
    el.scrollIntoView();
}

images = [
  {
    path: 'assets/img/project-8.jpg',
    name:'Education',
    role:'Web design'
  },
  {
    path: 'assets/img/project-9.jpg',
    name:'PHOTOSHOOT',
    role:'Web design'
  },
  {
    path: 'assets/img/project-10.jpg',
    name:'ELECTRICAL',
    role:'Web design'
  },
  {
    path: 'assets/img/project-11.jpg',
    name:'PROJECT NAME',
    role:'Web design'
  },
]
}

			<!-- Breadcrumb -->
			<div class="bread-crumb-bar">
				<div class="container">
					<div class="row align-items-center inner-banner">
						<div class="col-md-12 col-12 text-center">
							<div class="breadcrumb-list">
								<nav aria-label="breadcrumb" class="page-breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><a [routerLink]="'/home'"><img src="assets/img/home-icon.svg" alt=""> Home</a></li>
										<li class="breadcrumb-item" aria-current="page">Developer details</li>
									</ol>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Page Content -->
			<div class="content content-page">
				<div class="container">	
					<div class="row">
						<div class="col-lg-8 col-md-12">
							<div class="developer-box head-develop">
								<div class="developer-profile-img">
									<img src="assets/img/profile-bg.jpg" alt="" class="img-fluid" >
									<div class="img-profile">
										<img src="assets/img/img-04.jpg" alt="" class="img-fluid" >
									</div>
								</div>
								<h2>John Danie S <i class="fas fa-check-circle"></i></h2>
								<p>iOS Expert + Node Dev <span>Full time</span></p>
								<ul class="develope-list-rate">
									<li>
										<div class="rating">	
											<span class="average-rating">4.6 </span>
											<i class="fas fa-star filled"></i>
											<i class="fas fa-star filled"></i>
											<i class="fas fa-star filled"></i>
											<i class="fas fa-star filled"></i>
											<i class="fas fa-star filled"></i>
										</div>
									</li>
									<li>Member Since,Aug 5, 2018</li>
									<li class="bl-0"><img src="assets/img/flags/pl.png" alt="" height="16"> Poland</li>
									<li class="emp-edit"><a href="#"><i class="fas fa-pencil-alt"></i> Edit</a></li>
								</ul>
								<div class="proposal-box">
									<div class="proposal-value">
										<h4>$20.00</h4>
										<span>( Per Hour )</span>
									</div>
								</div>
								<ul class="feed-back-detail">
									<li>Recommended<span>89%</span></li>
									<li>Completed Projects<span>22</span></li>
									<li>Clients<span>48</span></li>
									<li>Ongoing Projects<span>2</span></li>
									<li>Feedbacks<span>5</span></li>
									<li>Rehired<span>12</span></li>
								</ul>
							</div>
							<div class="pro-view develop-view">
								<!-- Tab Detail -->
								<nav class="provider-tabs mb-4 abouts-view">
									<ul class="nav nav-tabs nav-tabs-solid nav-justified">
										<li class="nav-item">
											<a class="nav-link active-about" (click) = "scroll(target)">
												<img src="assets/img/icon/tab-icon-21.svg"  alt="User Image">
												<p class="bg-red">Overview</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" (click) = "scroll(project)">
												<img src="assets/img/icon/tab-icon-16.svg"  alt="User Image">
												<p class="bg-blue">Projects</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" (click) = "scroll(experience)">
												<img src="assets/img/icon/tab-icon-17.svg"  alt="User Image">
												<p class="bg-violet">Experience</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" (click) = "scroll(education)">
												<img src="assets/img/icon/tab-icon-18.svg"  alt="User Image">
												<p class="bg-yellow">Education</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" (click) = "scroll(skill)">
												<img src="assets/img/icon/tab-icon-19.svg"  alt="User Image">
												<p class="bg-pink">Skills</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" (click) = "scroll(feedback)">
												<img src="assets/img/icon/tab-icon-20.svg"  alt="User Image">
												<p class="bg-green">Feedbacks</p>
											</a>
										</li>
									</ul>
								</nav>
								<!-- /Tab Detail -->
								
								<!-- Overview Tab Content -->
								<div class="pro-post widget-box" #target>
									<h3 class="pro-title">Overview</h3>
									<div class="pro-content">
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget vestibulum lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor aliquam felis, nec condimentum ipsum commodo id. Vivamus sit amet augue nec urna efficitur tincidunt. Vivamus consectetur aliquam lectus commodo viverra. Nunc eu augue nec arcu efficitur faucibus.</p>
										<div class="mt-4">
											<h4 class="widget-title">My services include:</h4>
											<ul class="pro-list">
												<li>Cross-platform games</li>
												<li>Game concept and level designing</li>
												<li>Multiplayer integration</li>
												<li>Re-skin</li>
												<li>Ads and in-app purchase (Maximize your Revenue)</li>
												<li>Game Optimisations</li>
												<li>2D/3D Animation</li>
											</ul>
										</div>
										<p>Graphic DesigningSocial Network IntegrationVirtual Reality (VR)Augmented Reality (AR)Game con promotional graphics and video app store and Playstore publishing </p>
									</div>
								</div>
								<!-- /Overview Tab Content -->
								
								<!-- Project Tab Content -->								
								<div class="pro-post project-widget widget-box project-gallery" #project>
									<h3 class="pro-title">PROJECTS</h3>
									<div class="pro-content">
										<div class="row">
											<div class="col-sm-6 col-md-6 col-lg-4 col-xl-3" *ngFor = "let image of images">
												<div class="project-widget">
													<div class="pro-image">		
														<a href="assets/img/project-8.jpg" data-lightbox="gallery1">
															<img class="img-fluid" alt="User Image" [src]="image.path">
														</a>
													</div>
													<div class="project-footer">
														<div class="d-flex align-items-center">
															<div class="pro-detail">
																<h3 class="pro-name">
																	{{image.name}}
																</h3>
																<p class="pro-designation">{{image.role}}</p>
															</div>
															<div class="view-image">
																<a href="project.html"><i class="fas fa-arrow-right"></i></a>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="col-md-12">
												<a href="project.html" class="btn more-btn">View more </a>
											</div>
										</div>
									</div>
								</div>
								<!-- /Project Tab Content -->
								
								<!-- Experience Tab Content -->
								<div class="pro-post project-widget widget-box develop-experiance" #experience>
									<h3 class="pro-title">Experience</h3>
									<div class="pro-content">
										<div class="row">
											<div class="col-lg-4 col-md-6 d-flex">
												<div class="experiance-list">
													<div class="experiance-logo d-flex align-items-center justify-content-center">
														<img class="img-fluid" alt="" src="assets/img/icon/icon-10.png">
													</div>
													<h4>Logo Designer</h4>
													<h5>Techline <br> July 9, 2018 - March 18, 2021</h5>
													<p>I am a professional graphic designer. I have more than 10-years of experience in graphics design. If you are looking for any graphic related work, contact me, I'll glad to help you.</p>
												</div>
											</div>
											<div class="col-lg-4 col-md-6 d-flex">
												<div class="experiance-list">
													<div class="experiance-logo d-flex align-items-center justify-content-center">
														<img class="img-fluid" alt="" src="assets/img/icon/icon-10.png">
													</div>
													<h4>UI Designer</h4>
													<h5>Techline <br> May 10, 2020 - March 10, 2022</h5>
													<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget vestibulum lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor aliquam felis</p>
												</div>
											</div>
											<div class="col-lg-4 col-md-6 d-flex">
												<div class="experiance-list">
													<div class="experiance-logo d-flex align-items-center justify-content-center">
														<img class="img-fluid" alt="" src="assets/img/icon/icon-10.png">
													</div>
													<h4>UX Designer</h4>
													<h5>Techline <br> Sep 10, 2018 - Jan 18, 2020</h5>
													<p>Lorem ipsum dolor sit amet ,nec condimentum ipsum commodo id. Vivamus sit amet augue nec urna efficitur tincidunt. Vivamus consectetur aliquam lectus commodo viverra. Nunc eu augue nec arcu efficitur faucibus.</p>
												</div>
											</div>
										</div>
									</div>
								</div>
								<!-- /Experience Tab Content -->
								
								<!-- Educational Tab Content -->
								<div class="pro-post project-widget widget-box" #education>
									<h3 class="pro-title">Educational Details</h3>
									<div class="pro-content">
										<div class="row">
											<div class="col-lg-6 col-md-6 d-flex">
												<div class="experiance-list">
													<div class="experiance-logo logo-bg d-flex align-items-center justify-content-center">
														<img class="img-fluid" alt="" src="assets/img/icon/icon-11.png">
													</div>
													<h4>Bachelor of Science in Game Programming & Development</h4>
													<h5>Hampshire University January 12, 2015 - January 19, 2019</h5>
													<p>Graphic Designing artworks through making plans and utilizing the helpful analysis of companions, educators, and bosses to improve those plans. Careful discipline brings about promising results, and the capacity to acknowledge and gain from analysis from peers and even the purchaser everywhere is pivotal for accomplishment in this field.</p>
												</div>
											</div>
											<div class="col-lg-6 col-md-6 d-flex">
												<div class="experiance-list">
													<div class="experiance-logo logo-bg d-flex align-items-center justify-content-center">
														<img class="img-fluid" alt="" src="assets/img/icon/icon-11.png">
													</div>
													<h4>Master in Gaming STudi Design</h4>
													<h5>Techline  July 9, 2018 - March 18, 2021</h5>
													<p>I am a professional graphic designer. I have more than 10-years of experience in graphics design. If you are looking for any graphic related work, contact me, I'll glad to help you.</p>
												</div>
											</div>
										</div>
									</div>
								</div>
								<!-- /Educational Tab Content -->
								
								<!-- Technical Tab Content -->
								<div class="pro-post project-widget widget-box technical-skill" #skill>
									<h3 class="pro-title">Technical Skills</h3>
									<div class="pro-content">
										<div class="tags">
										<span class="badge badge-pill badge-skills">+ Web Design</span>
										<span class="badge badge-pill badge-skills">+ UI Design</span>
										<span class="badge badge-pill badge-skills">+ Node Js</span>
										<span class="badge badge-pill badge-skills">+ Javascript</span>
										</div>
									</div>
								</div>								
								<!-- /Technical Tab Content -->
								
								<!-- Feedback Tab Content -->
								<div class="pro-post author-widget clearfix develop-feedback" #feedback>
									<div class="widget-title-box clearfix d-flex">
										<h3 class="pro-title mb-0">Feedbacks</h3>
										<a href="review.html" class="feedback-view">View All</a>
									</div>
									<div class="about-author">
										<div class="about-author-img">
											<div class="author-img-wrap">
												<a href="company-profile.html"><img class="img-fluid" alt="" src="assets/img/img-03.jpg"></a>
											</div>
										</div>
										<div class="author-details">
											<a href="company-profile.html" class="blog-author-name">Logo Designer</a>
											<h6>Techline  July 9, 2018 - March 18, 2021</h6>
											<p class="mb-0">I am a professional graphic designer. I have more than 10-years of experience in graphics design. If you are looking for any graphic related work, contact me, I'll glad to help you.</p>
										</div>
									</div>
									<div class="about-author">
										<div class="about-author-img">
											<div class="author-img-wrap">
												<a href="company-profile.html"><img class="img-fluid" alt="" src="assets/img/img-02.jpg"></a>
											</div>
										</div>
										<div class="author-details">
											<a href="company-profile.html" class="blog-author-name">Web Designer</a>
											<h6>Techline  July 9, 2018 - March 18, 2021</h6>
											<p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget vestibulum lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor aliquam felis</p>
										</div>
									</div>
									<div class="about-author">
										<div class="about-author-img">
											<div class="author-img-wrap">
												<a href="company-profile.html"><img class="img-fluid" alt="" src="assets/img/img-03.jpg"></a>
											</div>
										</div>
										<div class="author-details">
											<a href="company-profile.html" class="blog-author-name">UX Designer</a>
											<h6>Techline  July 9, 2018 - March 18, 2021</h6>
											<p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget vestibulum lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor aliquam felis</p>
										</div>
									</div>
									<div class="about-author">
										<div class="about-author-img">
											<div class="author-img-wrap">
												<a href="company-profile.html"><img class="img-fluid" alt="" src="assets/img/img-04.jpg"></a>
											</div>
										</div>
										<div class="author-details">
											<a href="company-profile.html" class="blog-author-name">Php Developer</a>
											<h6>Techline  July 9, 2018 - March 18, 2021</h6>
											<p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget vestibulum lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor aliquam felis</p>
										</div>
									</div>
								</div>								
								<!-- /Feedback Tab Content -->
								
							</div>
						</div>
					
						<!-- Blog Sidebar -->
						<div class="col-lg-4 col-md-12 sidebar-right developer-view">		
						
							<!-- About Widget -->	
							<div class="pro-post widget-box about-widget about-field">
								<h4 class="pro-title ">About Me</h4>
								<table class="table">
									<tbody>
									  <tr>
										<td>Gender</td>
										<td>Male</td>
									  </tr>
									  <tr>
										<td>Experience</td>
										<td>5 Years</td>
									  </tr>
									  <tr>
										<td>Location</td>
										<td>Istanbul/Turkey</td>
									  </tr>
									</tbody>
								</table>
							</div>
							<!-- /About Widget -->
							
							<!-- Language Widget -->
							<div class="pro-post widget-box language-widget">
								<h4 class="pro-title mb-0">Language Skills</h4>
								<ul class="latest-posts pro-content">
									<li><p>English</p>
										<div class="progress progress-md mb-0">
											<div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</li>
									<li><p>Russian</p>
										<div class="progress progress-md mb-0">
											<div class="progress-bar bg-success" role="progressbar" style="width: 65%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
										</div></li>
									<li><p>German</p>
										<div class="progress progress-md mb-0">
											<div class="progress-bar bg-warning" role="progressbar" style="width: 85%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</li>
								</ul>
							</div>
							<!-- /Language Widget -->
							
							<!-- Follow Widget -->
							<div class="pro-post widget-box follow-widget">
								<ul class="follow-posts pro-post">
									<li><p>Following</p><h6>49</h6></li>	
									<li><p>Followers</p><h6>422</h6></li>	
								</ul>
								<div class="text-center">
									<a href="#" class="btn follow-btn">+ Follow</a>
								</div>
							</div>
							<!-- /Follow Widget -->

							<!-- Categories -->
							<div class="pro-post category-widget link-box">
								<div class="widget-title-box">
									<h4 class="pro-title">Social Links</h4>
								</div>
								<ul class="latest-posts pro-content mb-3">
									<li><a href="#">http://www.facebook.com/john...</a></li>
									<li><a href="#">http://www.Twitter.com/john...</a></li>
									<li><a href="#">Http://www.googleplus.com/john... </a></li>
									<li><a href="#"> Http://www.behance.com/john...</a></li>
									<li><a href="#"> Http://www.pinterest.com/john...</a></li>
								</ul>
							</div>
							<!-- /Categories -->
							
							<!-- LInk Widget -->	
							<div class="pro-post widget-box post-widget profile-link">
								<h3 class="pro-title">Profile Link</h3>
								<div class="pro-content">
									<div class="form-group profile-group mb-0">
									<div class="input-group">
										<input type="text" class="form-control" value="https://www.kofejob.com/developer/daren/12454687">
										<div class="input-group-append">
											<button class="btn btn-success sub-btn" type="submit"><i class="fa fa-clone"></i></button>
										</div>
									</div>
									</div>
								</div>
							</div>
							<!-- /Link Widget -->		
							
							<!-- Social Widget -->	
							<div class="pro-post widget-box social-widget develop-social-link">
								<div class="profile-head">
									<h4 class="pro-title">SOCIAL LINKS</h4>
								</div>
								<ul class="social-link-profile">
									<li><a href="#"><i class="fas fa-share-alt"></i></a></li>
									<li><a href="#"><i class="fab fa-facebook"></i></a></li>
									<li><a href="#"><i class="fab fa-twitter"></i></a></li>
									<li><a href="#"><i class="fab fa-instagram"></i></a></li>
									<li><a href="#"><i class="fab fa-linkedin"></i></a></li>
									<li><a href="#"><i class="fab fa-telegram"></i></a></li>
								</ul>
							</div>
							<!-- /Social Widget -->
						
						</div>
						<!-- /Blog Sidebar -->
						
					</div>
				</div>
			</div>		
			<!-- /Page Content -->

// template-vuejs/src/views/frontend/freelancer/profile.vue
<template>
<div>
       <!-- Main Wrapper -->
        <div class="main-wrapper">
			<!-- Header -->
            <layout-freelancerprojectheader></layout-freelancerprojectheader>
			<!-- /Header -->

            <!-- Breadcrumb -->
			<div class="bread-crumb-bar">
				<div class="container">
					<div class="row align-items-center inner-banner">
						<div class="col-md-12 col-12 text-center">
							<div class="breadcrumb-list">
								<nav aria-label="breadcrumb" class="page-breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><router-link to="/index"><img src="../../../assets/img/home-icon.svg" alt=""> Home</router-link></li>
										<li class="breadcrumb-item" aria-current="page">Freelancer Profile</li>
									</ol>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Page Content -->
			<div class="content">
				<div class="container">	
					<div class="row">	
						<div class="col-md-12">	
							<div class="profile profile-freelance">			
								<div class="profile-box">			
									<div class="provider-widget">
										<div class="pro-info-left">
											<div class="provider-img "><img src="../../../assets/img/user/avatar-1.jpg" class="img-fluid" alt="User"></div>
											<div class="profile-info">
												<h2 class="profile-title">George Well</h2>
												<p class="profile-position">iOS Expert</p>
												<div><a href="javascript:void(0);" class="btn full-btn">Full time</a></div>							
												<ul class="profile-preword">
													<li><img src="../../../assets/img/flags/pl.png" alt="" height="16"> Poland</li>
													<li>
														<div class="rating mapgridrating1">							
															<span class="average-rating">4.6</span>
															<i class="fas fa-star filled"></i>
															<i class="fas fa-star filled"></i>
															<i class="fas fa-star filled"></i>
															<i class="fas fa-star filled"></i>
															<i class="fas fa-star"></i>
														</div>
													</li>
												</ul>
											</div>
										</div>
										<div class="pro-info-right profile-inf">
											<router-link class="btn profile-edit-btn" to="/freelancer-profile-settings">Edit Profile</router-link>
										</div>
									</div>						
								</div>
								<div class="profile-list">
									<ul>
										<li>
											<span class="cont bg-blue">22</span>
											<strong class="proj-title"> Completed Projects</strong>
										</li>
										<li>
											<span class="cont bg-red">5</span>
											<strong class="proj-title"> Ongoing Projects</strong>
										</li>
										<li>
											<span class="cont bg-violet">89%</span>
											<strong class="proj-title"> Recommended</strong>
										</li>
										<li>
											<span class="cont bg-yellow">12</span>
											<strong class="proj-title"> Rehired</strong>
										</li>
										<li>
											<span class="cont bg-pink">48</span>
											<strong class="proj-title"> Clients</strong>
										</li>
										<li>
											<span class="cont bg-navy">5</span>
											<strong class="proj-title"> Feedbacks</strong>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					
					<div class="row">
						<div class="col-lg-8 col-md-12">							
							<div class="pro-view">
								
								<!-- Tab Detail -->
								<nav class="provider-tabs mb-4">
									<ul class="nav nav-tabs nav-tabs-solid nav-justified">
										<li class="nav-item">
											<a class="nav-link" href="#overview">
												<img src="../../../assets/img/icon/tab-icon-01.png" height="25" alt="User Image">
												<p class="bg-red">Overview</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" href="#project">
												<img src="../../../assets/img/icon/tab-icon-02.png" height="25" alt="User Image">
												<p class="bg-blue">Projects</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" href="#experience">
												<img src="../../../assets/img/icon/tab-icon-03.png" height="25" alt="User Image">
												<p class="bg-violet">Experience</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" href="#education">
												<img src="../../../assets/img/icon/tab-icon-04.png" height="25" alt="User Image">
												<p class="bg-yellow">Education</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" href="#skill">
												<img src="../../../assets/img/icon/tab-icon-05.png" height="25" alt="User Image">
												<p class="bg-pink">Skills</p>
											</a>
										</li>
										<li class="nav-item">
											<a class="nav-link" href="#feedback">
												<img src="../../../assets/img/icon/tab-icon-06.png" height="25" alt="User Image">
												<p class="bg-green">Feedbacks</p>
											</a>
										</li>
									</ul>
								</nav>
								<!-- /Tab Detail -->
								
								<!-- Overview Tab Content -->
								<div class="pro-post widget-box" id="overview">
									<h3 class="pro-title">Overview</h3>
									<div class="pro-content">
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget vestibulum lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque tempor aliquam felis, nec condimentum ipsum commodo id. Vivamus sit amet augue nec urna efficitur tincidunt. Vivamus consectetur aliquam lectus commodo viverra. Nunc eu augue nec arcu efficitur faucibus.</p>
										<div class="mt-4">
											<h4 class="widget-title">My services include:</h4>
											<ul class="pro-list">
												<li>Cross-platform games</li>
												<li>Game concept and level designing</li>
												<li>Multiplayer integration</li>
												<li>Re-skin</li>
												<li>Ads and in-app purchase (Maximize your Revenue)</li>
												<li>Game Optimisations</li>
												<li>2D/3D Animation</li>
											</ul>
										</div>
										<p>Graphic DesigningSocial Network IntegrationVirtual Reality (VR)Augmented Reality (AR)Game con promotional graphics and video app store and Playstore publishing </p>
									</div>
								</div>
								<!-- /Overview Tab Content -->
								
								<!-- Experience Tab Content -->
								<div class="pro-post project-widget widget-box" id="experience">
									<h3 class="pro-title">Experience</h3>
									<div class="pro-content">
										<div class="widget-list mb-0">
											<ul class="clearfix">
												<li>
													<h4>Logo Designer</h4>
													<h5>Techline  July 9, 2018 - March 18, 2021</h5>
													<p>I am a professional graphic designer. I have more than 10-years of experience in graphics design. If you are looking for any graphic related work, contact me, I'll glad to help you.</p>
												</li>
												<li>
													<h4>Logo Designer</h4>
													<h5>Techline  July 9, 2018 - March 18, 2021</h5>
													<p>I am a professional graphic designer. I have more than 10-years of experience in graphics design. If you are looking for any graphic related work, contact me, I'll glad to help you.</p>
												</li>
												<li>
													<h4>Logo Designer</h4>
													<h5>Techline  July 9, 2018 - March 18, 2021</h5>
													<p>I am a professional graphic designer. I have more than 10-years of experience in graphics design. If you are looking for any graphic related work, contact me, I'll glad to help you.</p>
												</li>
											</ul>
										</div>
									</div>
								</div>
								<!-- /Experience Tab Content -->
								
								<!-- Educational Tab Content -->
								<div class="pro-post project-widget widget-box" id="education">
									<h3 class="pro-title">Educational Details</h3>
									<div class="pro-content">
										<div class="widget-list mb-0">
											<ul class="clearfix">
												<li>
													<h4>Bachelor of Science in Game Programming & Development</h4>
													<h5>Hampshire University  January 12, 2015 - January 19, 2019</h5>
													<p>Graphic Designing artworks through making plans and utilizing the helpful analysis of companions, educators, and bosses to improve those plans. Careful discipline brings about promising results, and the capacity to acknowledge and gain from analysis from peers and even the purchaser everywhere is pivotal for accomplishment in this field.</p>
												</li>
												<li>
													<h4>Master in Gaming STudi Design</h4>
													<h5>Techline  July 9, 2018 - March 18, 2021</h5>
													<p>I am a professional graphic designer. I have more than 10-years of experience in graphics design. If you are looking for any graphic related work, contact me, I'll glad to help you.</p>
												</li>
											</ul>
										</div>
									</div>
								</div>
								<!-- /Educational Tab Content -->
								
								<!-- Technical Tab Content -->
								<div class="pro-post project-widget widget-box" id="skill">
									<h3 class="pro-title">Technical Skills</h3>
									<div class="pro-content">
										<div class="tags">
										<span class="badge badge-pill badge-skills">+ Web Design</span>
										<span class="badge badge-pill badge-skills">+ UI Design</span>
										<span class="badge badge-pill badge-skills">+ Node Js</span>
										<span class="badge badge-pill badge-skills">+ Javascript</span>
										</div>
									</div>
								</div>								
								<!-- /Technical Tab Content -->
								
							</div>
						</div>
					
						<!-- Blog Sidebar -->
						<div class="col-lg-4 col-md-12 sidebar-right theiaStickySidebar">		
							
							<div class="pro-post widget-box follow-widget">
								<a href="javascript:void(0);" class="btn follow-btn">+ Follow</a>
								<ul class="follow-posts pro-post">
									<li><p>Following</p><h6>49</h6></li>	
									<li><p>Followers</p><h6>422</h6></li>	
								</ul>
							</div>
							
							<div class="pro-post widget-box language-widget">
								<h4 class="pro-title">LANGUAGE SKILLS</h4>
								<ul class="latest-posts pro-content pt-0">
									<li><p>English</p>
										<div class="progress progress-md mb-0">
											<div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</li>
									<li><p>Russian</p>
										<div class="progress progress-md mb-0">
											<div class="progress-bar bg-success" role="progressbar" style="width: 65%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
										</div></li>
									<li><p>German</p>
										<div class="progress progress-md mb-0">
											<div class="progress-bar bg-warning" role="progressbar" style="width: 50%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</li>
								</ul>
							</div>

							<div class="pro-post widget-box about-widget">
								<h4 class="pro-title mb-0">ABOUT ME</h4>
								<ul class="latest-posts pro-content">
									<li><p>Gender</p><h6>Male</h6></li>
									<li><p>Experience</p><h6>5 Years</h6></li>
									<li><p>Location</p><h6>Istanbul/Turkey</h6></li>
								</ul>
							</div>

							<!-- Categories -->
							<div class="pro-post category-widget">
								<div class="widget-title-box">
									<h4 class="pro-title">SOCIAL LINKS</h4>
								</div>
								<ul class="latest-posts pro-content">
									<li><a href="javascript:void(0);">http://www.facebook.com/john...</a></li>
									<li><a href="javascript:void(0);">http://www.Twitter.com/john...</a></li>
									<li><a href="javascript:void(0);">Http://www.googleplus.com/john... </a></li>
									<li><a href="javascript:void(0);"> Http://www.behance.com/john...</a></li>
									<li><a href="javascript:void(0);"> Http://www.pinterest.com/john...</a></li>
								</ul>
							</div>
							<!-- /Categories -->
							
							<!-- Link Widget -->	
							<div class="pro-post widget-box post-widget">
								<h3 class="pro-title">Profile Link</h3>
								<div class="pro-content">
									<div class="form-group profile-group mb-0">
									<div class="input-group">
										<input type="text" class="form-control" value="https://www.kofejob.com/developer/daren/12454687">
										<div class="input-group-append">
											<button class="btn btn-success sub-btn" type="submit"><i class="fa fa-clone"></i></button>
										</div>
									</div>
									</div>
								</div>
							</div>
							<!-- /Link Widget -->	

						</div>
						<!-- /Blog Sidebar -->
						
					</div>
				</div>
			</div>		
			<!-- /Page Content -->
           
            <!-- Footer -->
                <layout-footer />
            <!-- /Footer -->
        </div>
        <!-- /Main Wrapper -->

        </div>
</template>
<script>
	export default {
		 mounted() {
		},
        computed: {
            currentPath() {
                return this.$route.name;
         }
        },  
        data() {
        return {
          activeClass: 'active',
        };
                //  isactive : true
      },
	}
	</script>
