// template-angular/src/app/features-modules/employer/postproject/postproject.component.ts
import { Component, OnDestroy, OnInit, ViewEncapsulation } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { Validators, Editor, Toolbar } from 'ngx-editor';
import jsonDoc from './docs'

@Component({
  selector: 'app-postproject',
  templateUrl: './postproject.component.html',
  styleUrls: ['./postproject.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class PostprojectComponent implements OnInit,OnDestroy {
  public skillsArray: any = [];
  public isChecked:boolean = true;
  readioSelected:any;
  showcontent:any;
  editordoc = jsonDoc;
  selected = 'select';
  selected1 = 'select';
  editor: Editor | any;
  toolbar: Toolbar = [
    ['bold', 'italic'],
    ['underline', 'strike'],
    ['code', 'blockquote'],
    ['ordered_list', 'bullet_list'],
    [{ heading: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] }],
    ['link', 'image'],
    ['text_color', 'background_color'],
    ['align_left', 'align_center', 'align_right', 'align_justify'],
  ];

  form = new FormGroup({
    editorContent: new FormControl(
      { value: jsonDoc, disabled: false },
      Validators.required()
    ),
  });

  constructor() { }

  ngOnInit(): void {
    this.editor = new Editor();
  }
  hide(){
    this.showcontent=this.readioSelected;
  }
  public addSkills():void {
    this.skillsArray.push(1)
  }
  public deleteSkills(index:any):void {
    this.skillsArray.splice(index, 1)
  }
  ngOnDestroy(): void {
    if (this.editor){
      this.editor.destroy();

    }
  }
  tag = ['Valve profit'];
}

			<!-- Breadcrumb -->
			<div class="bread-crumb-bar">
				<div class="container">
					<div class="row align-items-center inner-banner">
						<div class="col-md-12 col-12 text-center">
							<div class="breadcrumb-list">
								<nav aria-label="breadcrumb" class="page-breadcrumb">
									<ol class="breadcrumb">
										<li class="breadcrumb-item"><a [routerLink]="'/home'"><img src="assets/img/home-icon.svg" alt=""> Home</a></li>
										<li class="breadcrumb-item" aria-current="page">Post a Project</li>
									</ol>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
						
			<!-- Page Content -->
			<div class="content content-page">	
				<div class="container">
					<div class="row">		
						<div class="col-md-12">		
							<div class="select-project mb-4">		
							<form action="dashboard.html">	
								<div class="title-box widget-box">
								
									<!-- Project Title -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Project Name</h3>
											<div class="form-group mb-0">
												<input type="text" class="form-control" placeholder="Enter Project title">
											</div>
										</div>					
									</div>
									<!-- /Project Title -->
									
									<!-- Category Content -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Category Type</h3>
											<div class="form-group mb-0">
												<mat-select class="form-control"  [(value)]="selected1">
													<mat-option value="select">Select</mat-option>
													<mat-option value="apps">Apps Development</mat-option>
													<mat-option value="ui">UI Development</mat-option>
													<mat-option value="java">JAVA</mat-option>
												  </mat-select>
											</div>
										</div>					
									</div>	
									<!-- /Category Content -->
									
									<!-- Price Content -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Pricing Type</h3>
											<div class="form-group price-cont mb-0" id="price_type">
												<mat-select class="form-control"  [(value)]="selected">
													<mat-option value="select">Select</mat-option>
													<mat-option value="Budget">Fixed Budget Price</mat-option>
													<mat-option value="Hourly">Hourly Pricing</mat-option>
													<mat-option value="Biding">Biding Price</mat-option>
												  </mat-select>
											</div>
											<div class="form-group mt-3" id="price_id" style="display: none;">
												<div class="input-group">
													<div class="input-group-prepend">
														<button type="button" class="btn btn-white dropdown-toggle" data-bs-toggle="dropdown">$</button>
														<div class="dropdown-menu">
															<a class="dropdown-item" href="#">Dollars</a>
															<a class="dropdown-item" href="#">Euro</a>
															<a class="dropdown-item" href="#">Bitcoin</a>
														</div>
													</div>
													<input type="text" class="form-control" placeholder="20.00">
												</div>
											</div>
											<div class="form-group mt-3" id="hour_id" style="display: none;">
												<div class="row">
													<div class="col-md-6 mb-2">
														<div class="input-group form-inline">
															<div class="input-group-prepend">
																<button type="button" class="btn btn-white dropdown-toggle" data-bs-toggle="dropdown">$</button>
																<div class="dropdown-menu">
																	<a class="dropdown-item" href="#">Dollars</a>
																	<a class="dropdown-item" href="#">Euro</a>
																	<a class="dropdown-item" href="#">Bitcoin</a>
																</div>
															</div>
															<input type="text" class="form-control mr-2" placeholder="20.00"> <label> / hr</label>
														</div>
													</div>
													<div class="col-md-6">
														<div class="input-group form-inline">
															<label>For </label> <input type="text" class="form-control ml-2" placeholder=" ( eg: 2 Weeks)"> 
														</div>
													</div>
												</div>
											</div>
										</div>					
									</div>		
									<!-- /Price Content -->
									
									<!-- Skills Content -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Desired areas of expertise </h3>
											<div class="form-group mb-0">
												<tag-input [(ngModel)]='tag' class="form-control tags-service" placeholder="Enter Tag" [ngModelOptions]="{standalone: true}"></tag-input>
												<p class="text-muted mb-0">Enter skills for needed for project</p>
											</div>
										</div>					
									</div>
									<!-- /Skills Content -->
									
									<!-- Project Period Content -->
									<div class="title-content">	
										<div class="title-detail">
											<h3>Period of Project</h3>
											<div class="form-group mb-0" id="pro_period">
												<div class="radio">
													<label class="custom_radio">
														<input type="radio"  name="period" [value]="2" (change)="hide()" [(ngModel)]="readioSelected">
														<span class="checkmark"></span>  Start  immediately  after the  candidate is selected
													</label>
												</div>
												<div class="radio">
													<label class="custom_radio">
														<input type="radio"  name="period" [value]="1" (change)="hide()" [(ngModel)]="readioSelected" [checked]="isChecked">
														<span class="checkmark"></span>  Job will Start On 
													</label>
												</div>
											</div>
											<div class="row" [style.display]="showcontent == 1? 'block' : 'none'" >
												<div class="col-md-4">
													<div class="filter-widget mb-0" id="period_date">
														<div class="cal-icon"> 
															<input class="form-control" matInput [matDatepicker]="picker" placeholder="Select Date">
															<mat-datepicker-toggle matIconSuffix [for]="picker"></mat-datepicker-toggle>
															<mat-datepicker #picker></mat-datepicker>
															<!-- <input type="date" class="form-control datetimepicker" placeholder="Select Date"> -->
														</div>			
													</div>								
												</div>								
											</div>								
										</div>					
									</div>
									<!-- /Project Period Content -->
									
									<!-- /Add Document -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Add Documents</h3>
											<div class="custom-file">
												<input type="file" class="custom-file-input">
												<label class="custom-file-label"></label>
											</div>
											<p class="mb-0">Size of the Document should be Below 2MB</p>											
										</div>					
									</div>	
									<!-- /Add Document -->
									
									<!-- Add Links -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Add Links</h3>
											<div class="links-info">
												<div class="row form-row links-cont">
													<div class="col-12 col-md-11">
														<div class="form-group mb-0">
															<input type="text" class="form-control">
															<p class="mb-0">Add Reference links if any</p>
														</div> 
													</div>
													<div class="col-12 col-md-1">
														<a href="javascript:void(0);" class="btn add-links" (click)="addSkills()"><i class="fas fa-plus"></i></a>
													</div>
												</div>
												<div class="row form-row links-cont" *ngFor="let skills of skillsArray; let i = index">
													<div class="col-12 col-md-11 col-lg-11">
														<div class="form-group">
															<label>Add</label>
															<input type="text" class="form-control">
														</div>
													</div>
													<div class="col-12 col-md-1 col-lg-1" *ngIf="i != 10">
														<label class="d-md-block d-sm-none d-none">&nbsp;</label>
														<a href="javascript:void(0);" class="btn btn-danger trash" (click)="deleteSkills(i)"><i class="far fa-trash-alt"></i></a>
													</div>
												</div>
											</div>										
										</div>					
									</div>
									<!-- /Add Links -->	

									<!-- Project Title -->
									<div class="title-content pb-0">
										<div class="title-detail">
											<h3>Write Description of Projects </h3>
											<form [formGroup]="form">
												<div class="editor">
													<ngx-editor-menu [editor]="editor" [toolbar]="toolbar">
													</ngx-editor-menu>
													<ngx-editor [editor]="editor" formControlName="editorContent">
													</ngx-editor>
												</div>
											</form>
										</div>					
									</div>
									<!-- /Project Title -->
									
									<div class="row">
										<div class="col-md-12 text-end">
											<div class="btn-item">
												<button type="submit" class="btn next-btn">Submit</button>
											</div>
										</div>
									</div>
									
								</div>
								<!-- Project Title -->

							</form>					
							</div>					
						</div>					
					</div>					
				</div>					
			</div>					
			<!-- /Page Content -->

// template-react/src/frontend/components/postproject/index.jsx
import React from "react";
import { Link } from "react-router-dom";
import ReactSummernote from 'react-summernote';
import 'react-summernote/dist/react-summernote.css'; 
    
const PostProject = (props) => {  
          
  return (
    <>
    {/* Breadcrumb */}
    <div className="breadcrumb-bar">
      <div className="container">
        <div className="row align-items-center inner-banner">
          <div className="col-md-12 col-12 text-center">
            <h2 className="breadcrumb-title">Post a Project</h2>
            <nav aria-label="breadcrumb" className="page-breadcrumb">
              <ol className="breadcrumb">
                <li className="breadcrumb-item">
                  <Link to="/">Home</Link>
                </li>
                <li className="breadcrumb-item active" aria-current="page">
                  {" "}
                  Post a Project
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
    {/* /Breadcrumb */}
    {/* Page Content */}
    <div className="content">
      <div className="container">
        <div className="row">
          <div className="col-md-12">
            <div className="select-project mb-4">
              <form >
                <div className="title-box widget-box">
                  {/* Project Title */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Project Name</h3>
                      <div className="form-group mb-0">
                        <input
                          type="text"
                          className="form-control"
                          placeholder="Enter Project title"
                        />
                      </div>
                    </div>
                  </div>
                  {/* /Project Title */}
                  {/* Category Content */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Category Type</h3>
                      <div className="form-group mb-0">
                        <select className="form-control select">
                          <option value={0}>Select</option>
                          <option value={1}>Apps Development</option>
                          <option value={2}>UI Development</option>
                          <option value={3}>Jaa</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  {/* /Category Content */}
                  {/* Price Content */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Pricing Type</h3>
                      <div className="form-group price-cont mb-0" id="price_type">
                        <select name="price" className="form-control select">
                          <option value={0}>Select</option>
                          <option value={1}>Fixed Budget Price</option>
                          <option value={2}>Hourly Pricing</option>
                          <option value={3}>Biding Price</option>
                        </select>
                      </div>
                      <div
                        className="form-group mt-3"
                        id="price_id"
                        style={{ display: "none" }}
                      >
                        <div className="input-group">
                          <div className="input-group-prepend">
                            <button
                              type="button"
                              className="btn btn-white dropdown-toggle"
                              data-bs-toggle="dropdown"
                            >
                              $
                            </button>
                            <div className="dropdown-menu">
                              <a className="dropdown-item" href="#">
                                Dollars
                              </a>
                              <a className="dropdown-item" href="#">
                                Euro
                              </a>
                              <a className="dropdown-item" href="#">
                                Bitcoin
                              </a>
                            </div>
                          </div>
                          <input
                            type="text"
                            className="form-control"
                            placeholder={20.0}
                          />
                        </div>
                      </div>
                      <div
                        className="form-group mt-3"
                        id="hour_id"
                        style={{ display: "none" }}
                      >
                        <div className="row">
                          <div className="col-md-6 mb-2">
                            <div className="input-group form-inline">
                              <div className="input-group-prepend">
                                <button
                                  type="button"
                                  className="btn btn-white dropdown-toggle"
                                  data-bs-toggle="dropdown"
                                >
                                  $
                                </button>
                                <div className="dropdown-menu">
                                  <a className="dropdown-item" href="#">
                                    Dollars
                                  </a>
                                  <a className="dropdown-item" href="#">
                                    Euro
                                  </a>
                                  <a className="dropdown-item" href="#">
                                    Bitcoin
                                  </a>
                                </div>
                              </div>
                              <input
                                type="text"
                                className="form-control mr-2"
                                placeholder={20.0}
                              />{" "}
                              <label> / hr</label>
                            </div>
                          </div>
                          <div className="col-md-6">
                            <div className="input-group form-inline">
                              <label>For </label>{" "}
                              <input
                                type="text"
                                className="form-control ml-2"
                                placeholder=" ( eg: 2 Weeks)"
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Price Content */}
                  {/* Skills Content */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Desired areas of expertise </h3>
                      <div className="form-group mb-0">
                        <input
                          type="text"
                          data-role="tagsinput"
                          className="input-tags form-control"
                          name="services"
                          defaultValue="Web Design"
                          id="services"
                          placeholder="UX, UI, App Design, Wireframing, Branding"
                        />
                        <p className="text-muted mb-0">
                          Enter skills for needed for project
                        </p>
                      </div>
                    </div>
                  </div>
                  {/* /Skills Content */}
                  {/* Project Period Content */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Period of Project</h3>
                      <div className="form-group mb-0" id="pro_period">
                        <div className="radio">
                          <label className="custom_radio">
                            <input
                              type="radio"
                              defaultValue="period"
                              name="period"
                            />
                            <span className="checkmark" /> Start immediately after
                            the candidate is selected
                          </label>
                        </div>
                        <div className="radio">
                          <label className="custom_radio">
                            <input
                              type="radio"
                              defaultValue="job"
                              name="period"
                              defaultChecked
                            />
                            <span className="checkmark" /> Job will Start On
                          </label>
                        </div>
                      </div>
                      <div className="row">
                        <div className="col-md-4">
                          <div className="filter-widget mb-0" id="period_date">
                            <div className="cal-icon">
                              <input
                                type="text"
                                className="form-control datetimepicker"
                                placeholder="Select Date"
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Project Period Content */}
                  {/* /Add Document */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Add Documents</h3>
                      <div className="custom-file">
                        <input type="file" className="custom-file-input" />
                        <label className="custom-file-label" />
                      </div>
                      <p className="mb-0">
                        Size of the Document should be Below 2MB
                      </p>
                    </div>
                  </div>
                  {/* /Add Document */}
                  {/* Add Links */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Add Links</h3>
                      <div className="links-info">
                        <div className="row form-row links-cont">
                          <div className="col-12 col-md-11">
                            <div className="form-group mb-0">
                              <input type="text" className="form-control" />
                              <p className="mb-0">Add Reference links if any</p>
                            </div>
                          </div>
                          <div className="col-12 col-md-1">
                            <a
                              href=""
                              className="btn add-links"
                            >
                              <i className="fas fa-plus" />
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Add Links */}
                  {/* Project Title */}
                  <div className="title-content pb-0">
                    <div className="title-detail">
                      <h3>Write Description of Projects </h3>
                      <div className="form-group mb-0">                                              
                        <ReactSummernote
                          value="Default value"
                          options={{
                            lang: 'ru-RU',
                            height: 350,
                            dialogsInBody: true,
                            toolbar: [
                              ['style', ['style']],
                              ['font', ['bold', 'underline', 'clear']],
                              ['fontname', ['fontname']],
                              ['para', ['ul', 'ol', 'paragraph']],
                              ['table', ['table']],
                              ['insert', ['link', 'picture', 'video']],
                              ['view', ['fullscreen', 'codeview']]
                            ]
                          }}
                        />
                      </div>
                    </div>
                  </div>
                  {/* /Project Title */}
                  <div className="row">
                    <div className="col-md-12 text-end">
                      <div className="btn-item">
                        <button type="submit" className="btn next-btn">
                          Submit
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
                {/* Project Title */}
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* /Page Content */}
  </>
      )
  
}
export default PostProject;
