// template-angular/src/app/features-modules/freelancer/dashboard/dashboard.component.ts
import { Component, OnInit,  ViewChild } from '@angular/core';
import {
  ChartComponent,
  ApexAxisChartSeries,
  ApexChart,
  ApexXAxis,
  ApexDataLabels,
  ApexTitleSubtitle,
  ApexStroke,
  ApexGrid,
  ApexNonAxisChartSeries,
  ApexPlotOptions,
} from "ng-apexcharts";

export type ChartOptions = {
  series: ApexAxisChartSeries| any;
  chart: ApexChart| any;
  xaxis: ApexXAxis| any;
  dataLabels: ApexDataLabels| any;
  grid: ApexGrid| any;
  stroke: ApexStroke| any;
  title: ApexTitleSubtitle| any;
};
export type radialChartOptions = {
  series: ApexNonAxisChartSeries | any;
  chart: ApexChart | any;
  labels: string[] | any;
  plotOptions: ApexPlotOptions | any;
};

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {
  @ViewChild("chart") chart: ChartComponent | any;
  public chartOptions: Partial<ChartOptions>;
  public radialchartOptions: Partial<ChartOptions> | any;
  
  constructor() {
    this.chartOptions = {
      series: [
        {
          name: "Desktops",
          data: [10, 41, 35, 51, 49, 62, 69, 91, 148]
        }
      ],
      chart: {
        height: 350,
        type: "line",
        zoom: {
          enabled: false
        }
      },
      dataLabels: {
        enabled: false
      },
      stroke: {
        curve: "straight"
      },
      title: {
        text: "Product Trends by Month",
        align: "left"
      },
      grid: {
        row: {
          colors: ["#f3f3f3", "transparent"], // takes an array which will be repeated on columns
          opacity: 0.5
        }
      },
      xaxis: {
        categories: [
          "Jan",
          "Feb",
          "Mar",
          "Apr",
          "May",
          "Jun",
          "Jul",
          "Aug",
          "Sep"
        ]
      }
    };


    this.radialchartOptions = {
      series: [85, 75, 60, 40],
      colors: ['#7B46BE', '#FA6CA4', '#FACD3A', '#24C0DC'],
      labels: ['Applied Jobs', 'Messenger', 'Facebook', 'LinkedIn'],
      chart: {
        height: 280,
        type: "radialBar"
      },
      plotOptions: {
        radialBar: {
          offsetY: 0,
          startAngle: 0,
          endAngle: 270,
          hollow: {
            margin: 5,
            size: '50%',
            background: 'transparent',
            image: undefined,
          },
          dataLabels: {
            name: {
              show: false,
            },
            value: {
              show: false,
            },
            total: {
              show: true,
              label: "Total",
              formatter: function() {
                return "249";
              }
            }
          }
        }
      },
      legend: {
        show: false,
        floating: true,
        fontSize: '16px',
        position: 'bottom',
        offsetX: 160,
        offsetY: 15,
        labels: {
          useSeriesColors: true,
        },
        markers: {
          size: 0
        },
        itemMargin: {
          vertical: 3
        }
      },
      responsive: [{
        breakpoint: 480,
        options: {
          legend: {
              show: false
          }
        }
      }]
    };
  }
 
  ngOnInit() {
  }

}

<div class="dashboard-sec">
    <div class="row">
        <div class="col-md-6 col-lg-4">
            <div class="dash-widget">
                <div class="dash-info">
                    <div class="dash-widget-info">Completed Jobs</div>
                    <div class="dash-widget-count">30</div>
                </div>
                <div class="dash-widget-more">
                    <a [routerLink] = "'/freelancer/freelancer-projects/completed-projects'" class="d-flex">View Details <i class="fas fa-arrow-right ms-auto"></i></a>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4">
            <div class="dash-widget">
                <div class="dash-info">
                    <div class="dash-widget-info">Task Completed</div>
                    <div class="dash-widget-count">5</div>
                </div>
                <div class="dash-widget-more">
                    <a [routerLink] = "'/freelancer/freelancer-projects/completed-projects'" class="d-flex">View Details <i class="fas fa-arrow-right ms-auto"></i></a>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4">
            <div class="dash-widget">
                <div class="dash-info">
                    <div class="dash-widget-info">Reviews</div>
                    <div class="dash-widget-count">25</div>
                </div>
                <div class="dash-widget-more">
                    <a [routerLink] = "'/freelancer/reviews'" class="d-flex">View Details <i class="fas fa-arrow-right ms-auto"></i></a>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Chart Content -->
    <div class="row">
        <div class="col-xl-8 d-flex">
            <div class="card flex-fill">
                <div class="pro-head">	
                    <h5 class="card-title mb-0">Your Profile View</h5> 
                    <div class="month-detail">	
                        <select class="form-select">
                            <option value="0">Last 6 months</option>
                            <option value="1" >Last 2 months</option>
                        </select>
                    </div>
                </div>
                <div class="pro-body">									
                    <div id="chartprofile">
                        <apx-chart
                                [series]="chartOptions.series"
                                [chart]="chartOptions.chart"
                                [xaxis]="chartOptions.xaxis"
                                [dataLabels]="chartOptions.dataLabels"
                                [grid]="chartOptions.grid"
                                [stroke]="chartOptions.stroke"
                                [title]="chartOptions.title"
                              ></apx-chart>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-4 d-flex">
            <div class="flex-fill card">
                <div class="pro-head b-0">	
                    <h5 class="card-title mb-0">Static Analytics</h5> 
                </div>
                <div class="pro-body">									
                    <div id="chartradial">
                        <apx-chart
                                [series]="radialchartOptions.series"
                                [chart]="radialchartOptions.chart"
                                [plotOptions]="radialchartOptions.plotOptions"
                                [labels]="radialchartOptions.labels"
                              ></apx-chart>
                    </div>
                    <ul class="static-list">
                        <li><span><i class="fas fa-circle text-violet me-1"></i> Applied Jobs</span> <span class="sta-count">30</span></li>
                        <li><span><i class="fas fa-circle text-pink me-1"></i> Active Proposals</span> <span class="sta-count">30</span></li>
                        <li><span><i class="fas fa-circle text-yellow me-1"></i> Applied Proposals</span> <span class="sta-count">30</span></li>
                        <li><span><i class="fas fa-circle text-blue me-1"></i> Bookmarked Projects</span> <span class="sta-count">30</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /Chart Content -->
    
    <div class="row">
        <!-- Plan  Details-->
        <div class="col-xl-6 d-flex">					
            <div class="card flex-fill">
                <div class="pro-head">
                    <h2>Membership Plan Details</h2>
                    <div><i class="fas fa-check-circle verified orange-text fa-2x"></i></div>
                </div>
                <div class="pro-body">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="plan-details">
                                <h4>The Ultima</h4>
                                <div class="yr-amt">Anually Price</div>
                                <h3>$1200</h3>
                                <div class="yr-duration">Duration: One Year</div>
                                <div class="expiry">Expiry: 24 JAN 2022</div>
                                <a [routerLink] = "'/freelancer/membership'" class="btn btn-primary btn-plan">Change Plan</a>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="plan-feature">
                                <ul>
                                    <li>12 Project Credits</li>
                                    <li>10 Allowed Services</li>
                                    <li>20 Days visibility</li>
                                    <li>5 Featured Services</li>
                                    <li>20 Days visibility</li>
                                    <li>30 Days Package Expiry</li>
                                    <li>Profile Featured</li>
                                </ul>
                                <a [routerLink] = "'/freelancer/membership'" >View Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Plan  Details -->
        
        <!-- Ongoing Projects -->
        <div class="col-xl-6 d-flex">					
            <div class="card flex-fill">
                <div class="pro-head">
                    <h2>Ongoing Projects</h2>
                    <a [routerLink] = "'/freelancer/freelancer-projects/ongoing-projects'"  class="btn fund-btn">View All</a>
                </div>
                <div class="pro-body p-0">
                    <div class="on-project">
                        <h5>Web Scraping</h5>
                        <p>I need some data to be scraped from various social media....</p>
                        <div class="pro-info">
                            <ul class="list-details">
                                <li>
                                    <div class="slot">
                                        <p>Job Type</p>
                                        <h5>Hourly</h5>
                                    </div>
                                </li>
                                <li>
                                    <div class="slot">
                                        <p>Project Price</p>
                                        <h5>$120</h5>
                                    </div>
                                </li>
                                <li>
                                    <div class="slot">
                                        <p>Location</p>
                                        <h5>3 Received</h5>
                                    </div>
                                </li>
                                <li>
                                    <div class="slot">
                                        <p>Expiry</p>
                                        <h5>4 Days Left</h5>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="on-project">
                        <h5>New Service</h5>
                        <p>I need some data to be scraped from various social media....</p>
                        <div class="pro-info">
                            <ul class="list-details">
                                <li>
                                    <div class="slot">
                                        <p>Job Type</p>
                                        <h5>Hourly</h5>
                                    </div>
                                </li>
                                <li>
                                    <div class="slot">
                                        <p>Project Price</p>
                                        <h5>$90</h5>
                                    </div>
                                </li>
                                <li>
                                    <div class="slot">
                                        <p>Location</p>
                                        <h5>3 Received</h5>
                                    </div>
                                </li>
                                <li>
                                    <div class="slot">
                                        <p>Expiry</p>
                                        <h5>5 Days Left</h5>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="on-project">
                        <h5>Website Layout changes</h5>
                        <p>I need some data to be scraped from various social media....</p>
                        <div class="pro-info">
                            <ul class="list-details">
                                <li>
                                    <div class="slot">
                                        <p>Job Type</p>
                                        <h5>Hourly</h5>
                                    </div>
                                </li>
                                <li>
                                    <div class="slot">
                                        <p>Project Price</p>
                                        <h5>$70</h5>
                                    </div>
                                </li>
                                <li>
                                    <div class="slot">
                                        <p>Location</p>
                                        <h5>3 Received</h5>
                                    </div>
                                </li>
                                <li>
                                    <div class="slot">
                                        <p>Expiry</p>
                                        <h5>7 Days Left</h5>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Ongoing Projects -->
    </div>
    
    <!-- Past Earnings -->
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4">
                <div class="pro-head">
                    <h2>Past Earnings</h2>
                    <a [routerLink] = "'/freelancer/payments'" class="btn fund-btn">View All</a>
                </div>
                <div class="pro-body p-0">
                    <div class="earn-feature">
                        <div class="row align-items-center">
                            <div class="col-lg-7 col-md-6">
                                <div class="earn-info">
                                    <p>I want some customization and installation on wordpress</p>
                                    <div class="date">October 5, 2021</div>
                                </div>
                            </div>
                            <div class="col-lg-5 col-md-6">
                                <div class="earn-img">
                                    <span><img src="assets/img/user/avatar-1.jpg" alt="logo" class="img-fluid avatar-md rounded-circle"> George Wells</span>
                                    <div class="price">$90</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="earn-feature">
                        <div class="row align-items-center">
                            <div class="col-lg-7 col-md-6">
                                <div class="earn-info">
                                    <p>I want simple Joomla 4 component development </p>
                                    <div class="date">October 12, 2021</div>
                                </div>
                            </div>
                            <div class="col-lg-5 col-md-6">
                                <div class="earn-img">
                                    <span><img src="assets/img/user/avatar-2.jpg" alt="logo" class="img-fluid avatar-md rounded-circle"> Timothy Smith</span>
                                    <div class="price">$150</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="earn-feature">
                        <div class="row align-items-center">
                            <div class="col-lg-7 col-md-6">
                                <div class="earn-info">
                                    <p>I want migrate Wordpress website </p>
                                    <div class="date">October 15, 2021</div>
                                </div>
                            </div>
                            <div class="col-lg-5 col-md-6">
                                <div class="earn-img">
                                    <span><img src="assets/img/user/avatar-3.jpg" alt="logo" class="img-fluid avatar-md rounded-circle"> Janet Paden</span>
                                    <div class="price">$70</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="earn-feature">
                        <div class="row align-items-center">
                            <div class="col-lg-7 col-md-6">
                                <div class="earn-info">
                                    <p>I want Landing Page Redesign / Sales Page Redesign</p>
                                    <div class="date">October 20, 2021</div>
                                </div>
                            </div>
                            <div class="col-lg-5 col-md-6">
                                <div class="earn-img">
                                    <span><img src="assets/img/user/avatar-4.jpg" alt="logo" class="img-fluid avatar-md rounded-circle"> James Douglas</span>
                                    <div class="price">$120</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Past Earnings -->
    
</div>

// template-react/src/frontend/components/forfreelancer/dashboard/index.jsx
import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import StickyBox from "react-sticky-box";
import ApexCharts from 'apexcharts';
import { Avatar_1,Avatar_2,Avatar_3,Avatar_4, home_icon } from "../../imagepath";
import { Sidebar } from '../sidebar';

const FreelancerDashboard = (props) => {  
  
  var chartprofileoptions = {
          series: [{
            name: "profile view",
            data: [100, 150, 200, 250, 200, 250, 200, 200, 200, 200, 300, 350]
          }],
          chart: {
            height: 360,
            type: 'line',		  
            toolbar: {
              show: false
            },
            zoom: {
                enabled: false
              }
            },
            dataLabels: {
              enabled: false
            },
            colors: ["#FF5B37"],
            stroke: {
              curve: 'straight',
              width: [1]
            },
            markers: {
              size: 4,
              colors: ["#FF5B37"],
              strokeColors: "#FF5B37",
              strokeWidth: 1,
              hover: {
                size: 7,
              }
            },
            grid: {
              position: 'front',
              borderColor: '#ddd',
              strokeDashArray: 7,
              xaxis: {
                lines: {
                  show: true
                }
              }
            },
            xaxis: {
              categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
              lines: {
                show: false,
              }
            },
            yaxis: {
              lines: {
                show: true,
              }
            }
        };
  
	var chartradialOptions = {
        series: [85, 75, 60, 40],
        chart: {		  
          toolbar: {
            show: false
          },
          height: 250,
          type: 'radialBar',
        },
        plotOptions: {
          radialBar: {
            offsetY: 0,
            startAngle: 0,
            endAngle: 270,
            hollow: {
              margin: 5,
              size: '50%',
              background: 'transparent',
              image: undefined,
            },
            dataLabels: {
              name: {
                show: false,
              },
              value: {
                show: false,
              }
            }
          }
        },
        colors: ['#7B46BE', '#FA6CA4', '#FACD3A', '#24C0DC'],
        labels: ['Applied Jobs', 'Messenger', 'Facebook', 'LinkedIn'],
        legend: {
          show: false,
          floating: true,
          fontSize: '16px',
          position: 'bottom',
          offsetX: 160,
          offsetY: 15,
          labels: {
            useSeriesColors: true,
          },
          markers: {
            size: 0
          },
          formatter: function(seriesName, opts) {
            return seriesName + ":  " + opts.w.globals.series[opts.seriesIndex]
          },
          itemMargin: {
            vertical: 3
          }
        },
        responsive: [{
          breakpoint: 480,
          options: {
            legend: {
                show: false
            }
          }
        }]
      };
  useEffect(() => {
    let chartprofileoptionsColumn =  document.getElementById("chartprofile");
			let chartprofileoptionsChart = new ApexCharts(chartprofileoptionsColumn, chartprofileoptions);
			chartprofileoptionsChart.render();
			
			let invoiceColumn =  document.getElementById("chartradial");
			let invoiceChart = new ApexCharts(invoiceColumn, chartradialOptions);
			invoiceChart.render();
    document.body.className = 'dashboard-page';
    return () => { document.body.className = ''; }
  });
  return (
      <>
      {/* Breadcrumb */}
      <div className="bread-crumb-bar">
        <div className="container">
          <div className="row align-items-center inner-banner">
            <div className="col-md-12 col-12 text-center">
              <div className="breadcrumb-list">
                <nav aria-label="breadcrumb" className="page-breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item"><Link to="#"><img src={home_icon} alt="Post Author" /> Home</Link></li>
                    <li className="breadcrumb-item" aria-current="page">FREELANCER
</li>
                    <li className="breadcrumb-item" aria-current="page">DASHBOARD</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Breadcrumb */}
        {/* Page Content */}
        <div className="content">
          <div className="container-fluid">
            <div className="row">
              <div className="col-xl-3 col-md-4 theiaStickySidebar">
                  <StickyBox offsetTop={20} offsetBottom={20}>
                      <Sidebar/>
                  </StickyBox>
              </div>
              <div className="col-xl-9 col-md-8">
                <div className="dashboard-sec">
                  <div className="row">
                    <div className="col-md-6 col-lg-4">
                      <div className="dash-widget">
                        <div className="dash-info">
                          <div className="dash-widget-info">Completed Jobs</div>
                          <div className="dash-widget-count">30</div>
                        </div>
                        <div className="dash-widget-more">
                          <Link
                            to="/freelancer-completed-projects"
                            className="d-flex"
                          >
                            View Details <i className="fas fa-arrow-right ms-auto" />
                          </Link>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-6 col-lg-4">
                      <div className="dash-widget">
                        <div className="dash-info">
                          <div className="dash-widget-info">Task Completed</div>
                          <div className="dash-widget-count">5</div>
                        </div>
                        <div className="dash-widget-more">
                          <Link
                            to="/freelancer-completed-projects"
                            className="d-flex"
                          >
                            View Details <i className="fas fa-arrow-right ms-auto" />
                          </Link>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-6 col-lg-4">
                      <div className="dash-widget">
                        <div className="dash-info">
                          <div className="dash-widget-info">Reviews</div>
                          <div className="dash-widget-count">25</div>
                        </div>
                        <div className="dash-widget-more">
                          <Link to="/freelancer-review" className="d-flex">
                            View Details <i className="fas fa-arrow-right ms-auto" />
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* Chart Content */}
                  <div className="row">
                    <div className="col-xl-8 d-flex">
                      <div className="card flex-fill">
                        <div className="pro-head">
                          <h5 className="card-title mb-0">Your Profile View</h5>
                          <div className="month-detail">
                            <select className="form-control">
                              <option value={0}>Last 6 months</option>
                              <option value={1}>Last 2 months</option>
                            </select>
                          </div>
                        </div>
                        <div className="pro-body">
                          <div id="chartprofile" />
                        </div>
                      </div>
                    </div>
                    <div className="col-xl-4 d-flex">
                      <div className="flex-fill card">
                        <div className="pro-head b-0">
                          <h5 className="card-title mb-0">Static Analytics</h5>
                        </div>
                        <div className="pro-body">
                          <div id="chartradial" />
                          <ul className="static-list">
                            <li>
                              <span>
                                <i className="fas fa-circle text-violet me-1" />{" "}
                                Applied Jobs
                              </span>{" "}
                              <span className="sta-count">30</span>
                            </li>
                            <li>
                              <span>
                                <i className="fas fa-circle text-pink me-1" /> Active
                                Proposals
                              </span>{" "}
                              <span className="sta-count">30</span>
                            </li>
                            <li>
                              <span>
                                <i className="fas fa-circle text-yellow me-1" />{" "}
                                Applied Proposals
                              </span>{" "}
                              <span className="sta-count">30</span>
                            </li>
                            <li>
                              <span>
                                <i className="fas fa-circle text-blue me-1" />{" "}
                                Bookmarked Projects
                              </span>{" "}
                              <span className="sta-count">30</span>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Chart Content */}
                  <div className="row">
                    {/* Plan  Details*/}
                    <div className="col-xl-6 d-flex">
                      <div className="card flex-fill">
                        <div className="pro-head">
                          <h2>Membership Plan Details</h2>
                          <div>
                            <i className="fas fa-check-circle verified orange-text fa-2x" />
                          </div>
                        </div>
                        <div className="pro-body">
                          <div className="row">
                            <div className="col-md-6 col-sm-6">
                              <div className="plan-details">
                                <h4>The Ultima</h4>
                                <div className="yr-amt">Anually Price</div>
                                <h3>$1200</h3>
                                <div className="yr-duration">Duration: One Year</div>
                                <div className="expiry">Expiry: 24 JAN 2022</div>
                                <Link
                                  to="/freelancer-membership"
                                  className="btn btn-primary btn-plan"
                                >
                                  Change Plan
                                </Link>
                              </div>
                            </div>
                            <div className="col-md-6 col-sm-6">
                              <div className="plan-feature">
                                <ul>
                                  <li>12 Project Credits</li>
                                  <li>10 Allowed Services</li>
                                  <li>20 Days visibility</li>
                                  <li>5 Featured Services</li>
                                  <li>20 Days visibility</li>
                                  <li>30 Days Package Expiry</li>
                                  <li>Profile Featured</li>
                                </ul>
                                <Link to="/freelancer-membership">View Details</Link>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* /Plan  Details */}
                    {/* Ongoing Projects */}
                    <div className="col-xl-6 d-flex">
                      <div className="card flex-fill">
                        <div className="pro-head">
                          <h2>Ongoing Projects</h2>
                          <Link
                            to="/freelancer-ongoing-projects"
                            className="btn fund-btn"
                          >
                            View All
                          </Link>
                        </div>
                        <div className="pro-body p-0">
                          <div className="on-project">
                            <h5>Web Scraping</h5>
                            <p>
                              I need some data to be scraped from various social
                              media....
                            </p>
                            <div className="pro-info">
                              <ul className="list-details">
                                <li>
                                  <div className="slot">
                                    <p>Job Type</p>
                                    <h5>Hourly</h5>
                                  </div>
                                </li>
                                <li>
                                  <div className="slot">
                                    <p>Project Price</p>
                                    <h5>$120</h5>
                                  </div>
                                </li>
                                <li>
                                  <div className="slot">
                                    <p>Location</p>
                                    <h5>3 Received</h5>
                                  </div>
                                </li>
                                <li>
                                  <div className="slot">
                                    <p>Expiry</p>
                                    <h5>4 Days Left</h5>
                                  </div>
                                </li>
                              </ul>
                            </div>
                          </div>
                          <div className="on-project">
                            <h5>New Service</h5>
                            <p>
                              I need some data to be scraped from various social
                              media....
                            </p>
                            <div className="pro-info">
                              <ul className="list-details">
                                <li>
                                  <div className="slot">
                                    <p>Job Type</p>
                                    <h5>Hourly</h5>
                                  </div>
                                </li>
                                <li>
                                  <div className="slot">
                                    <p>Project Price</p>
                                    <h5>$90</h5>
                                  </div>
                                </li>
                                <li>
                                  <div className="slot">
                                    <p>Location</p>
                                    <h5>3 Received</h5>
                                  </div>
                                </li>
                                <li>
                                  <div className="slot">
                                    <p>Expiry</p>
                                    <h5>5 Days Left</h5>
                                  </div>
                                </li>
                              </ul>
                            </div>
                          </div>
                          <div className="on-project">
                            <h5>Website Layout changes</h5>
                            <p>
                              I need some data to be scraped from various social
                              media....
                            </p>
                            <div className="pro-info">
                              <ul className="list-details">
                                <li>
                                  <div className="slot">
                                    <p>Job Type</p>
                                    <h5>Hourly</h5>
                                  </div>
                                </li>
                                <li>
                                  <div className="slot">
                                    <p>Project Price</p>
                                    <h5>$70</h5>
                                  </div>
                                </li>
                                <li>
                                  <div className="slot">
                                    <p>Location</p>
                                    <h5>3 Received</h5>
                                  </div>
                                </li>
                                <li>
                                  <div className="slot">
                                    <p>Expiry</p>
                                    <h5>7 Days Left</h5>
                                  </div>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {/* /Ongoing Projects */}
                  </div>
                  {/* Past Earnings */}
                  <div className="row">
                    <div className="col-md-12">
                      <div className="card mb-4">
                        <div className="pro-head">
                          <h2>Past Earnings</h2>
                          <Link to="/freelancer-payment" className="btn fund-btn">
                            View All
                          </Link>
                        </div>
                        <div className="pro-body p-0">
                          <div className="earn-feature">
                            <div className="row align-items-center">
                              <div className="col-lg-7 col-md-6">
                                <div className="earn-info">
                                  <p>
                                    I want some customization and installation on
                                    wordpress
                                  </p>
                                  <div className="date">October 5, 2021</div>
                                </div>
                              </div>
                              <div className="col-lg-5 col-md-6">
                                <div className="earn-img">
                                  <span>
                                    <img
                                      src={Avatar_1}
                                      alt="logo"
                                      className="img-fluid avatar-md rounded-circle"
                                    />{" "}
                                    George Wells
                                  </span>
                                  <div className="price">$90</div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="earn-feature">
                            <div className="row align-items-center">
                              <div className="col-lg-7 col-md-6">
                                <div className="earn-info">
                                  <p>I want simple Joomla 4 component development </p>
                                  <div className="date">October 12, 2021</div>
                                </div>
                              </div>
                              <div className="col-lg-5 col-md-6">
                                <div className="earn-img">
                                  <span>
                                    <img
                                      src={Avatar_2}
                                      alt="logo"
                                      className="img-fluid avatar-md rounded-circle"
                                    />{" "}
                                    Timothy Smith
                                  </span>
                                  <div className="price">$150</div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="earn-feature">
                            <div className="row align-items-center">
                              <div className="col-lg-7 col-md-6">
                                <div className="earn-info">
                                  <p>I want migrate Wordpress website </p>
                                  <div className="date">October 15, 2021</div>
                                </div>
                              </div>
                              <div className="col-lg-5 col-md-6">
                                <div className="earn-img">
                                  <span>
                                    <img
                                      src={Avatar_3}
                                      alt="logo"
                                      className="img-fluid avatar-md rounded-circle"
                                    />{" "}
                                    Janet Paden
                                  </span>
                                  <div className="price">$70</div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="earn-feature">
                            <div className="row align-items-center">
                              <div className="col-lg-7 col-md-6">
                                <div className="earn-info">
                                  <p>
                                    I want Landing Page Redesign / Sales Page Redesign
                                  </p>
                                  <div className="date">October 20, 2021</div>
                                </div>
                              </div>
                              <div className="col-lg-5 col-md-6">
                                <div className="earn-img">
                                  <span>
                                    <img
                                      src={Avatar_4}
                                      alt="logo"
                                      className="img-fluid avatar-md rounded-circle"
                                    />{" "}
                                    James Douglas
                                  </span>
                                  <div className="price">$120</div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Past Earnings */}
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* /Page Content */}
      </>
      )
  
}
export default FreelancerDashboard;
