// template-angular/src/app/features-modules/admin/verifyidentity/verifyidentity.component.ts
import { Component, OnInit, ViewChild, OnDestroy } from '@angular/core';

import { Subject } from "rxjs";
import { MatLegacyTableDataSource as MatTableDataSource } from '@angular/material/legacy-table';
import { Sort } from '@angular/material/sort';
import { ShareDataService } from 'src/app/core/data/share-data.service';

@Component({
  selector: 'app-verifyidentity',
  templateUrl: './verifyidentity.component.html',
  styleUrls: ['./verifyidentity.component.scss']
})
export class VerifyidentityComponent implements OnInit {

  public searchDataValue = '';
  dataSource!: MatTableDataSource<any>;

  // pagination variables
  public lastIndex: number = 0;
  public pageSize: number = 10;
  public totalData: any = 0;
  public skip: number = 0;
  public limit: number = this.pageSize;
  public pageIndex: number = 0;
  public serialNumberArray: Array<any> = [];
  public currentPage: number = 1;
  public pageNumberArray: Array<any> = [];
  public pageSelection: Array<pageSelection> = [];
  public totalPages: number = 0;
  public lstIdentity!: any[];
  public url: any = "admin";
  public filter:boolean = false;
  constructor(private data: ShareDataService ) { }

  ngOnInit(): void {
    this.getlstIdentity();

  }
    //Filter toggle
    openFilter(){
      this.filter = !this.filter
    }
    private getlstIdentity(): void {
      this.lstIdentity = [];
      this.serialNumberArray = [];
  
      this.data.adminIdentityList().subscribe((res: any) => {
        this.totalData = res.totalData;
        res.data.map((res: any, index: number) => {
          let serialNumber = index + 1;
          if (index >= this.skip && serialNumber <= this.limit) {
            res.id = serialNumber;
            this.lstIdentity.push(res);
            this.serialNumberArray.push(serialNumber);
          }
        });
           this.dataSource = new MatTableDataSource<any>(this.lstIdentity);
      this.calculateTotalPages(this.totalData, this.pageSize);
      });
  
   
    }
    public sortData(sort: Sort) {
      const data = this.lstIdentity.slice();
  
      if (!sort.active || sort.direction === '') {
        this.lstIdentity = data;
      } else {
        this.lstIdentity = data.sort((a: any, b: any) => {
          const aValue = (a as any)[sort.active];
          const bValue = (b as any)[sort.active];
          return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
        });
      }
    }
  
    public searchData(value: any): void {
      this.dataSource.filter = value.trim().toLowerCase();
      this.lstIdentity = this.dataSource.filteredData;
    }
  
    public getMoreData(event: string): void {
      if (event == 'next') {
        this.currentPage++;
        this.pageIndex = this.currentPage - 1;
        this.limit += this.pageSize;
        this.skip = this.pageSize * this.pageIndex;
        this.getlstIdentity();
      } else if (event == 'previous') {
        this.currentPage--;
        this.pageIndex = this.currentPage - 1;
        this.limit -= this.pageSize;
        this.skip = this.pageSize * this.pageIndex;
        this.getlstIdentity();
      }
    }
  
    public moveToPage(pageNumber: number): void {
      this.currentPage = pageNumber;
      this.skip = this.pageSelection[pageNumber - 1].skip;
      this.limit = this.pageSelection[pageNumber - 1].limit;
      if (pageNumber > this.currentPage) {
        this.pageIndex = pageNumber - 1;
      } else if (pageNumber < this.currentPage) {
        this.pageIndex = pageNumber + 1;
      }
      this.getlstIdentity();
    }
  
    public changePageSize(): void {
      this.pageSelection = [];
      this.limit = this.pageSize;
      this.skip = 0;
      this.currentPage = 1;
      this.getlstIdentity();
    }
  
    private calculateTotalPages(totalData: number, pageSize: number): void {
      this.pageNumberArray = [];
      this.totalPages = totalData / pageSize;
      if (this.totalPages % 1 != 0) {
        this.totalPages = Math.trunc(this.totalPages + 1);
      }
      for (var i = 1; i <= this.totalPages; i++) {
        let limit = pageSize * i;
        let skip = limit - pageSize;
        this.pageNumberArray.push(i);
        this.pageSelection.push({ skip: skip, limit: limit });
      }
    }
}
export interface pageSelection {
  skip: number;
  limit: number;
}

			<!-- Page Wrapper -->
            <div class="page-wrapper">
                <div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">Verify Identity Details</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><a [routerLink]="'/admin/dashboard'">Home</a></li>
									<li class="breadcrumb-item active">Verify Identity Details</li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /Page Header -->


					<div class="row">
						<div class="col-lg-12">
							<div class="card bg-white">
								<div class="card-body pt-0">
									<div class="card-header mb-4">
										<ul role="tablist" class="nav nav-pills card-header-pills nav-justified">
											<li class="nav-item">
												<a href="#employer" data-bs-toggle="tab" class="nav-link active me-1">Employers</a>
											</li>
											<li class="nav-item">
												<a href="#freelancer" data-bs-toggle="tab" class="nav-link">Freelancers</a>
											</li>
										</ul>
									</div>
									<div class="tab-content pt-0">
										<div role="tabpanel" id="employer" class="tab-pane fade show active">
											<div class="card">
												<div class="card-body">
													<div class="table-responsive">
														<div class="table_header">
															<div class="dataTables_length">
																<label>
																	Show
																</label>
																<select [(ngModel)]="pageSize" (ngModelChange)="changePageSize()"
																class="form-control form-control-sm">
																<option value="10">10</option>
																<option value="25">25</option>
																<option value="50">50</option>
																<option value="100">100</option>
															</select>
															<label >Entries</label>
															</div>
															<div class="dataTables_filter">
																<label>
																	Search:
																</label>
																<input [(ngModel)]="searchDataValue"
																	(ngModelChange)="searchData(searchDataValue)"
																	class="form-control form-control-sm" />
															</div>
														</div>
														<div class="table-scroll">
															<table matSort (matSortChange)="sortData($event)"
																class="table table-center table-hover mb-0 datatable">
																<thead>
																	<tr>
																		<th mat-sort-header="id">No</th>
																		<th mat-sort-header="name">Name</th>
																		<th mat-sort-header="contact">Contact Number</th>	
																		<th mat-sort-header="passport">CNIC / Passport / NIN / SSN</th>	
																		<th mat-sort-header="image">Document</th>	
																		<th mat-sort-header="address">Address</th>
																		<th>Action</th>
																	</tr>
																</thead>
																<tbody>
																	<tr *ngFor = "let identity of lstIdentity; let i = index">
																		<td>{{identity.id}}</td>
																		<td>{{identity.name}}</td>
																		<td>{{identity.contact}}</td>
																		<td>{{identity.passport}}</td>
																		<td>
																			<h2 class="table-avatar">
																				<a [routerLink]="'/admin/profile'"><img class="me-2 rounded-circle" [src]="identity.image" alt="User Image"></a>
																			</h2>
																		</td>
																		<td>{{identity.address}}</td>
																		<td>
																			<a href="javascript:" class="btn btn-success btn-disable me-2">Approve</a>
																			<a href="javascript:" class="btn btn-disable">Reject</a>
																		</td>
																	</tr>																		
																</tbody>
															</table>
														</div>
														<div class="table_footer">
															<div class="col-sm-12 col-md-5">
																<div class="dataTables_info">
																	Showing {{ serialNumberArray[0] }} to
																	{{ serialNumberArray[serialNumberArray.length - 1] }} of
																	{{ totalData }} entries
																</div>
															</div>
													
															<div class="col-sm-12 col-md-7">
																<div class="pagination_section">
																	<ul class="pagination">
																		<li class="page-item" [ngClass]="{
													disabled: currentPage == 1
													}">
																			<a (click)="getMoreData('previous')" class="page-link"
																				href="javascript:void(0);" tabindex="-1">Previous</a>
																		</li>
													
																		<ng-container *ngFor="let item of pageNumberArray; let i = index">
																			<li class="page-item" [class.active]="item === currentPage" [ngClass]="
														(pageNumberArray[currentPage - 2] > item &&
														item != 1 &&
														pageNumberArray.length > 6) ||
														(pageNumberArray[currentPage] < item &&
														item != 1 &&
														pageNumberArray.length > 6 &&
														pageNumberArray.length != item)
														? 'hide-page-no'
														: 'show-page-no'
													">
																				<a (click)="moveToPage(item)" class="page-link"
																					href="javascript:void(0);">
																					{{ item }}
																				</a>
																			</li>
																			<li class="page-item" *ngIf="
														i == 0 && pageNumberArray.length > 6 && currentPage > 2
													" [hidden]="currentPage == 1" (click)="moveToPage(currentPage - 2)">
																				<a class="page-link" href="javascript:void(0);"> ... </a>
																			</li>
																			<li *ngIf="
														i == pageNumberArray.length - 2 &&
														pageNumberArray.length > 6
													" [hidden]="
														currentPage >=
														pageNumberArray[pageNumberArray.length - 2] ||
														totalData < serialNumberArray[serialNumberArray.length - 1]
													" class="page-item" (click)="moveToPage(currentPage + 2)">
																				<a class="page-link" href="javascript:void(0);"> ... </a>
																			</li>
																		</ng-container>
													
																		<li class="page-item" [ngClass]="{
													disabled:
														currentPage ==
														pageNumberArray[pageNumberArray.length - 1] ||
														lstIdentity.length == 0
													}">
																			<a (click)="getMoreData('next')" class="page-link"
																				href="javascript:void(0);">Next
																			</a>
																		</li>
																	</ul>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div role="tabpanel" id="freelancer" class="tab-pane fade">
											<div class="card">
												<div class="card-body">
													<div class="table-responsive">
														<div class="table_header">
															<div class="dataTables_length">
																<label>
																	Show
																</label>
																<select [(ngModel)]="pageSize" (ngModelChange)="changePageSize()"
																class="form-control form-control-sm">
																<option value="10">10</option>
																<option value="25">25</option>
																<option value="50">50</option>
																<option value="100">100</option>
															</select>
															<label >Entries</label>
															</div>
															<div class="dataTables_filter">
																<label>
																	Search:
																</label>
																<input [(ngModel)]="searchDataValue"
																	(ngModelChange)="searchData(searchDataValue)"
																	class="form-control form-control-sm" />
															</div>
														</div>
														<div class="table-scroll">
															<table matSort (matSortChange)="sortData($event)"
																class="table table-center table-hover mb-0 datatable">
																<thead>
																	<tr>
																		<th mat-sort-header="id">No</th>
																		<th mat-sort-header="name">Name</th>
																		<th mat-sort-header="contact">Contact Number</th>	
																		<th mat-sort-header="passport">CNIC / Passport / NIN / SSN</th>	
																		<th mat-sort-header="image">Document</th>	
																		<th mat-sort-header="address">Address</th>
																		<th>Action</th>
																	</tr>
																</thead>
																<tbody>
																	<tr *ngFor = "let identity of lstIdentity; let i = index">
																		<td>{{identity.id}}</td>
																		<td>{{identity.name}}</td>
																		<td>{{identity.contact}}</td>
																		<td>{{identity.passport}}</td>
																		<td>
																			<h2 class="table-avatar">
																				<a [routerLink]="'/admin/profile'"><img class="me-2 rounded-circle" [src]="identity.image" alt="User Image"></a>
																			</h2>
																		</td>
																		<td>{{identity.address}}</td>
																		<td>
																			<a href="javascript:" class="btn btn-success btn-disable me-2">Approve</a>
																			<a href="javascript:" class="btn btn-disable">Reject</a>
																		</td>
																	</tr>																		
																</tbody>
															</table>
														</div>
														<div class="table_footer">
															<div class="col-sm-12 col-md-5">
																<div class="dataTables_info">
																	Showing {{ serialNumberArray[0] }} to
																	{{ serialNumberArray[serialNumberArray.length - 1] }} of
																	{{ totalData }} entries
																</div>
															</div>
													
															<div class="col-sm-12 col-md-7">
																<div class="pagination_section">
																	<ul class="pagination">
																		<li class="page-item" [ngClass]="{
													disabled: currentPage == 1
													}">
																			<a (click)="getMoreData('previous')" class="page-link"
																				href="javascript:void(0);" tabindex="-1">Previous</a>
																		</li>
													
																		<ng-container *ngFor="let item of pageNumberArray; let i = index">
																			<li class="page-item" [class.active]="item === currentPage" [ngClass]="
														(pageNumberArray[currentPage - 2] > item &&
														item != 1 &&
														pageNumberArray.length > 6) ||
														(pageNumberArray[currentPage] < item &&
														item != 1 &&
														pageNumberArray.length > 6 &&
														pageNumberArray.length != item)
														? 'hide-page-no'
														: 'show-page-no'
													">
																				<a (click)="moveToPage(item)" class="page-link"
																					href="javascript:void(0);">
																					{{ item }}
																				</a>
																			</li>
																			<li class="page-item" *ngIf="
														i == 0 && pageNumberArray.length > 6 && currentPage > 2
													" [hidden]="currentPage == 1" (click)="moveToPage(currentPage - 2)">
																				<a class="page-link" href="javascript:void(0);"> ... </a>
																			</li>
																			<li *ngIf="
														i == pageNumberArray.length - 2 &&
														pageNumberArray.length > 6
													" [hidden]="
														currentPage >=
														pageNumberArray[pageNumberArray.length - 2] ||
														totalData < serialNumberArray[serialNumberArray.length - 1]
													" class="page-item" (click)="moveToPage(currentPage + 2)">
																				<a class="page-link" href="javascript:void(0);"> ... </a>
																			</li>
																		</ng-container>
													
																		<li class="page-item" [ngClass]="{
													disabled:
														currentPage ==
														pageNumberArray[pageNumberArray.length - 1] ||
														lstIdentity.length == 0
													}">
																			<a (click)="getMoreData('next')" class="page-link"
																				href="javascript:void(0);">Next
																			</a>
																		</li>
																	</ul>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>		
						</div>			
					</div>
				</div>
			</div>
			<!-- /Page Wrapper -->

// template-vuejs/src/views/admin/main/verify/verifyidentity.vue
<template>
    <div>
    <!-- Main Wrapper -->
        <div class="main-wrapper">
            <layout-adminheader></layout-adminheader>
			<layout-adminsidebar></layout-adminsidebar>
			
			<!-- Page Wrapper -->
            <div class="page-wrapper">
                <div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row align-items-center">
							<div class="col">
								<h3 class="page-title">Verify Identity Details</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><router-link to="/admin/index">Home</router-link></li>
									<li class="breadcrumb-item active">Verify Identity Details</li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /Page Header -->


					<div class="row">
						<div class="col-lg-12">
							<div class="card bg-white">
								<div class="card-body pt-0">
									<div class="card-header mb-4">
										<ul role="tablist" class="nav nav-pills card-header-pills nav-justified">
											<li class="nav-item">
												<a href="#employer" data-bs-toggle="tab" class="nav-link active me-1">Employers</a>
											</li>
											<li class="nav-item">
												<a href="#freelancer" data-bs-toggle="tab" class="nav-link">Freelancers</a>
											</li>
										</ul>
									</div>
									<div class="tab-content pt-0">
										<div role="tabpanel" id="employer" class="tab-pane fade show active">
											<div class="card">
												<div class="card-body">
													<div class="table-responsive">
														<table class="table table-center table-hover mb-0 datatable" id="verifyidentity">
															<thead>
																<tr>
																	<th>No</th>
																	<th>Name</th>
																	<th>Contact Number</th>	
																	<th>CNIC / Passport / NIN / SSN</th>	
																	<th>Document</th>	
																	<th>Address</th>
																	<th>Action</th>
																</tr>
															</thead>
															<tbody>
																<tr>
																	<td>1</td>
																	<td>Emily Smith</td>
																	<td>601-316-9060</td>
																	<td>518-43-5504</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-01.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>148  Tanglewood Road, Fulton</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>	
																<tr>
																	<td>2</td>
																	<td>Angeline S Cutshaw</td>
																	<td>601-283-5402</td>
																	<td>158-07-8510</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-03.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>North Carolina, USAi</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>		
																<tr>
																	<td>3</td>
																	<td>Robert J Sullivan</td>
																	<td>601-316-5657</td>
																	<td>221-04-8830</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-02.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>Kentucky, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>		
																<tr>
																	<td>4</td>
																	<td>Crystal Kemper</td>
																	<td>601-321-8956</td>
																	<td>221-04-5659</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-04.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>64 Florida, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>			
																<tr>
																	<td>5</td>
																	<td>Andrew Glover</td>
																	<td>601-213-4545</td>
																	<td>221-04-7245</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-05.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>New Jersey, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>			
																<tr>
																	<td>6</td>
																	<td>Jacqueline Daye</td>
																	<td>601-456-2468</td>
																	<td>221-04-8830</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-06.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td> Indiana, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>			
																<tr>
																	<td>7</td>
																	<td>Tony Ingle</td>
																	<td>601-345-7834</td>
																	<td>221-04-8830</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-07.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>644  Ferrell Street, Wadena</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>				
																<tr>
																	<td>8</td>
																	<td>Albert Boone</td>
																	<td>601-316-7765</td>
																	<td>321-04-3434</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-08.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>644  Ferrell Street, Wadena</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>				
																<tr>
																	<td>9</td>
																	<td>Kathleen Kaiser</td>
																	<td>601-545-2323</td>
																	<td>121-04-2323</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-09.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>644  Alabama, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>				
																<tr>
																	<td>10</td>
																	<td>Mickey Bernier</td>
																	<td>601-343-5656</td>
																	<td>221-34-4545</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-10.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td> North Carolina, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>																		
															</tbody>
														</table>
													</div>
												</div>
											</div>
										</div>
										<div role="tabpanel" id="freelancer" class="tab-pane fade">
											<div class="card">
												<div class="card-body">
													<div class="table-responsive"> 
														<table class="table table-center table-bordered table-hover datatable" id="verifyidentity1">
															<thead class="thead-light">
																<tr>
																	<th>No</th>
																	<th>Name</th>
																	<th>Contact Number</th>	
																	<th>CNIC / Passport / NIN / SSN</th>	
																	<th>Document</th>	
																	<th>Address</th>
																	<th>Action</th>
																</tr>
															</thead>
															<tbody>
																<tr>
																	<td>1</td>
																	<td>Crystal Kemper</td>
																	<td>601-316-9060</td>
																	<td>518-43-5504</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-11.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>Tanglewood Road, Fulton</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>	
																<tr>
																	<td>2</td>
																	<td>Cutshaw Emiley</td>
																	<td>601-283-5402</td>
																	<td>158-07-8510</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-12.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>2764 Brownton Road, Belzoni</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>		
																<tr>
																	<td>3</td>
																	<td>Nick John</td>
																	<td>601-316-9060</td>
																	<td>221-04-8830</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-13.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td> Maine, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>			
																<tr>
																	<td>4</td>
																	<td>Floyd Lewis</td>
																	<td>601-316-9060</td>
																	<td>221-04-8830</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-14.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>Alabama, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>		
																<tr>
																	<td>5</td>
																	<td>Santra Leodhapher</td>
																	<td>601-345-2325</td>
																	<td>221-04-8830</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-15.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>North Carolina, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>			
																<tr>
																	<td>6</td>
																	<td>James Douglas</td>
																	<td>601-788-9087</td>
																	<td>231-65-5656</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-16.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>Indiana, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>			
																<tr>
																	<td>7</td>
																	<td>John Smith</td>
																	<td>601-232-3422</td>
																	<td>221-05-3445</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-01.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>New Jersey, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>			
																<tr>
																	<td>8</td>
																	<td>Robert Leodhapher</td>
																	<td>601-454-8666</td>
																	<td>231-45-3434</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-02.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>Kentucky, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>				
																<tr>
																	<td>9</td>
																	<td>Will Smith</td>
																	<td>601-316-9060</td>
																	<td>221-04-8830</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-08.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td>Colorado, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>				
																<tr>
																	<td>10</td>
																	<td>Reboah Daniel</td>
																	<td>601-316-9060</td>
																	<td>221-04-8830</td>
																	<td>
																		<h2 class="table-avatar">
																			<router-link to="/admin/profile"><img class="me-2 rounded-circle" src="../../../../assets/admin-img/profiles/avatar-06.jpg" alt="User Image"></router-link>
																		</h2>
																	</td>
																	<td> California, USA</td>
																	<td>
																		<a href="javascript:void(0);" class="btn btn-success btn-disable me-1">Approve</a>
																		<a href="javascript:void(0);" class="btn btn-disable">Reject</a>
																	</td>
																</tr>																	
															</tbody>
														</table>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>		
						</div>			
					</div>
				</div>
			</div>
			<!-- /Page Wrapper -->
		
        </div>
		<!-- /Main Wrapper -->

    </div>
</template>
<script>
    import util from '../../../../assets/utils/util'
	export default {
		 mounted() {
            util.datatable('#verifyidentity')
			util.datatable('#verifyidentity1')
		},
		methods:{
		},
		data() {
			return {
			}
		}
	}
	</script>
