// template-react/src/frontend/components/foremployers/editproject/index.jsx
import React , {useEffect} from "react";
import { Link } from "react-router-dom";
import { Document_Img } from "../../imagepath";
import ReactSummernote from 'react-summernote';
import 'react-summernote/dist/react-summernote.css'; 
    
const EditProject = (props) => {   
    useEffect(() => {
      document.body.className = 'dashboard-page';
      return () => { document.body.className = ''; }
    });  
        
  return (
    <>
    {/* Breadcrumb */}
    <div className="breadcrumb-bar">
      <div className="container">
        <div className="row align-items-center inner-banner">
          <div className="col-md-12 col-12 text-center">
            <h2 className="breadcrumb-title">Edit Projects</h2>
            <nav aria-label="breadcrumb" className="page-breadcrumb">
              <ol className="breadcrumb">
                <li className="breadcrumb-item">
                  <Link to="/">Home</Link>
                </li>
                <li className="breadcrumb-item active" aria-current="page">
                  {" "}
                  Edit Projects
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </div>
    {/* /Breadcrumb */}
    {/* Page Content */}
    <div className="content">
      <div className="container">
        <div className="row">
          <div className="col-md-12">
            <div className="text-end mb-4">
              <Link
                to="/manage-projects"
                className="btn btn-primary back-btn br-0"
              >
                <i className="fas fa-long-arrow-alt-left" /> Back to Project{" "}
              </Link>
            </div>
            <div className="select-project mb-4">
              <form >
                <div className="title-box widget-box">
                  {/* Project Title */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Project Name</h3>
                      <div className="form-group mb-0">
                        <input
                          type="text"
                          className="form-control"
                          defaultValue="Edit Project"
                        />
                      </div>
                    </div>
                  </div>
                  {/* /Project Title */}
                  {/* Category Content */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Category Type</h3>
                      <div className="form-group mb-0">
                        <select className="form-control select">
                          <option value={0}>Select</option>
                          <option value={1} >
                            Apps Development
                          </option>
                          <option value={2}>UI Development</option>
                          <option value={3}>Jaa</option>
                        </select>
                      </div>
                    </div>
                  </div>
                  {/* /Category Content */}
                  {/* Price Content */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Pricing Type</h3>
                      <div className="form-group price-cont mb-0" id="price_type">
                        <select name="price" className="form-control select">
                          <option value={0}>Select</option>
                          <option value={1} >
                            Fixed Budget Price
                          </option>
                          <option value={2}>Hourly Pricing</option>
                          <option value={3}>Biding Price</option>
                        </select>
                      </div>
                      <div className="form-group mt-3" id="price_id">
                        <div className="input-group">
                          <button
                            type="button"
                            className="btn btn-white dropdown-toggle"
                            data-bs-toggle="dropdown"
                          >
                            $
                          </button>
                          <div className="dropdown-menu">
                            <a className="dropdown-item" href="#">
                              Dollars
                            </a>
                            <a className="dropdown-item" href="#">
                              Euro
                            </a>
                            <a className="dropdown-item" href="#">
                              Bitcoin
                            </a>
                          </div>
                          <input
                            type="text"
                            className="form-control"
                            placeholder={20.0}
                          />
                        </div>
                      </div>
                      <div
                        className="form-group mt-3"
                        id="hour_id"
                        style={{ display: "none" }}
                      >
                        <div className="row">
                          <div className="col-md-6 mb-2">
                            <div className="input-group form-inline">
                              <button
                                type="button"
                                className="btn btn-white dropdown-toggle"
                                data-bs-toggle="dropdown"
                              >
                                $
                              </button>
                              <div className="dropdown-menu">
                                <a className="dropdown-item" href="#">
                                  Dollars
                                </a>
                                <a className="dropdown-item" href="#">
                                  Euro
                                </a>
                                <a className="dropdown-item" href="#">
                                  Bitcoin
                                </a>
                              </div>
                              <input
                                type="text"
                                className="form-control me-2"
                                placeholder={20.0}
                              />{" "}
                              <label> / hr</label>
                            </div>
                          </div>
                          <div className="col-md-6">
                            <div className="input-group form-inline">
                              <label>For </label>{" "}
                              <input
                                type="text"
                                className="form-control ms-2"
                                placeholder=" ( eg: 2 Weeks)"
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Price Content */}
                  {/* Skills Content */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Desired areas of expertise </h3>
                      <div className="form-group mb-0">
                        <input
                          type="text"
                          data-role="tagsinput"
                          className="input-tags form-control"
                          name="services"
                          defaultValue="Web Design, Node JS"
                          id="services"
                          placeholder="UX, UI, App Design, Wireframing, Branding"
                        />
                        <p className="text-muted mb-0">
                          Enter skills for needed for project
                        </p>
                      </div>
                    </div>
                  </div>
                  {/* /Skills Content */}
                  {/* Project Period Content */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Period of Project</h3>
                      <div className="form-group mb-0" id="pro_period">
                        <div className="radio">
                          <label className="custom_radio">
                            <input
                              type="radio"
                              defaultValue="period"
                              name="period"
                            />
                            <span className="checkmark" /> Start immediately after
                            the candidate is selected
                          </label>
                        </div>
                        <div className="radio">
                          <label className="custom_radio">
                            <input
                              type="radio"
                              defaultValue="job"
                              name="period"
                              defaultChecked
                            />
                            <span className="checkmark" /> Job will Start On
                          </label>
                        </div>
                      </div>
                      <div className="row">
                        <div className="col-md-4">
                          <div className="filter-widget mb-0" id="period_date">
                            <div className="cal-icon">
                              <input
                                type="text"
                                className="form-control datetimepicker"
                                placeholder="Select Date"
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Project Period Content */}
                  {/* /Add Document */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Add Documents</h3>
                      <div className="custom-file">
                        <input type="file" className="custom-file-input" />
                        <label className="custom-file-label" />
                      </div>
                      <p>Size of the Document should be Below 2MB</p>
                      <div className="upload-wrap">
                        <div className="upload-document">
                          <img src={Document_Img} alt="Image" />
                          <a
                            href=""
                            className="btn btn-icon btn-danger btn-sm"
                          >
                            <i className="material-icons">delete_sweep</i>
                          </a>
                        </div>
                        <div className="upload-document">
                          <img src={Document_Img} alt="Image" />
                          <a
                            href=""
                            className="btn btn-icon btn-danger btn-sm"
                          >
                            <i className="material-icons">delete_sweep</i>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Add Document */}
                  {/* Add Links */}
                  <div className="title-content">
                    <div className="title-detail">
                      <h3>Add Links</h3>
                      <div className="links-info">
                        <div className="row form-row links-cont">
                          <div className="col-12 col-md-11">
                            <div className="form-group">
                              <input type="text" className="form-control" />
                            </div>
                          </div>
                          <div className="col-12 col-md-1">
                            <a
                              href=""
                              className="btn btn-danger trash"
                            >
                              <i className="far fa-trash-alt" />
                            </a>
                          </div>
                        </div>
                        <div className="row form-row links-cont">
                          <div className="col-12 col-md-11">
                            <div className="form-group">
                              <input type="text" className="form-control" />
                            </div>
                          </div>
                          <div className="col-12 col-md-1">
                            <a
                              href=""
                              className="btn btn-danger trash"
                            >
                              <i className="far fa-trash-alt" />
                            </a>
                          </div>
                          <div className="col-md-6">
                            <p className="mb-0">Add Reference links if any</p>
                          </div>
                          <div className="col-md-5 text-end">
                            <a
                              href=""
                              className="add-links more-link"
                            >
                              <i className="fas fa-plus-circle orange-text" /> Add
                              more
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Add Links */}
                  {/* Project Title */}
                  <div className="title-content pb-0">
                    <div className="title-detail">
                      <h3>Write Description of Projects </h3>
                      <div className="form-group mb-0">                        
                        <ReactSummernote
                          value="Default value"
                          options={{
                            lang: 'ru-RU',
                            height: 350,
                            dialogsInBody: true,
                            toolbar: [
                              ['style', ['style']],
                              ['font', ['bold', 'underline', 'clear']],
                              ['fontname', ['fontname']],
                              ['para', ['ul', 'ol', 'paragraph']],
                              ['table', ['table']],
                              ['insert', ['link', 'picture', 'video']],
                              ['view', ['fullscreen', 'codeview']]
                            ]
                          }}
                        />
                      </div>
                    </div>
                  </div>
                  {/* /Project Title */}
                  <div className="text-end">
                    <div className="btn-item">
                      <button
                        className="btn btn-primary black-btn click-btn b-0"
                        type="submit"
                      >
                        CANCEL
                      </button>&nbsp;
                      <button
                        className="btn btn-primary click-btn b-0"
                        type="submit"
                      >
                        SUBMIT
                      </button>
                    </div>
                  </div>
                </div>
                {/* Project Title */}
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* /Page Content */}
  </>
      )
  
}
export default EditProject;

// template-angular/src/app/features-modules/employer/projects/edit-project/edit-project.component.ts
import { Component, OnDestroy, OnInit, ViewEncapsulation } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { Validators, Editor, Toolbar } from 'ngx-editor';
import jsonDoc from './docs'

@Component({
  selector: 'app-edit-project',
  templateUrl: './edit-project.component.html',
  styleUrls: ['./edit-project.component.scss']
})
export class EditProjectComponent implements OnInit {
  editordoc = jsonDoc;
  editor: Editor | any;
  ishidden: boolean = false;
  public educationalArray: any = [1];
  toolbar: Toolbar = [
    ['bold', 'italic'],
    ['underline', 'strike'],
    ['code', 'blockquote'],
    ['ordered_list', 'bullet_list'],
    [{ heading: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] }],
    ['link', 'image'],
    ['text_color', 'background_color'],
    ['align_left', 'align_center', 'align_right', 'align_justify'],
  ];

  form = new FormGroup({
    editorContent: new FormControl(
      { value: jsonDoc, disabled: false },
      Validators.required()
    ),
  });

  constructor() { }

  ngOnInit(): void {
    this.editor = new Editor();
  }
  
  ngOnDestroy(): void {
    this.editor.destroy();
  }
  public addEducation():void {
    this.educationalArray.push(1)
  }
  public deleteEducation(index:any):void {
    this.educationalArray.splice(index, 1)
  }
  tag = ['Valve profit'];
  pricingOption(event:any) {
    let pricetype = event.target['value'] 
    if (pricetype == 'price_free') {
      this.ishidden = false
    }
    else (
      this.ishidden = true
    )
  }
}

			<!-- Breadcrumb -->
			<div class="breadcrumb-bar">
				<div class="container">
					<div class="row align-items-center inner-banner">
						<div class="col-md-12 col-12 text-center">
							<h2 class="breadcrumb-title">Edit Projects</h2>
							<nav aria-label="breadcrumb" class="page-breadcrumb">
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a [routerLink]="'/home'">Home</a></li>
									<li class="breadcrumb-item active" aria-current="page"> Edit Projects</li>
								</ol>
							</nav>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
						
			<!-- Page Content -->
			<div class="content content-page">	
				<div class="container">
					<div class="row">		
						<div class="col-md-12">	
							<div class="text-end mb-4">	
								<a [routerLink]="'/employer/manage-projects/all-projects'" class="btn btn-primary back-btn br-0"><i class="fas fa-long-arrow-alt-left"></i> Back to Project </a>
							</div>
							<div class="select-project mb-4">		
							<form action="dashboard.html">	
								<div class="title-box widget-box">
								
									<!-- Project Title -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Project Name</h3>
											<div class="form-group mb-0">
												<input type="text" class="form-control" value="Edit Project">
											</div>
										</div>					
									</div>
									<!-- /Project Title -->
									
									<!-- Category Content -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Category Type</h3>
											<div class="form-group mb-0">
												<select  class="form-control select form-select">
													<option value="0">Select</option>
													<option value="1" selected>Apps Development</option>
													<option value="2">UI Development</option>
													<option value="3">Jaa</option>
												</select>
											</div>
										</div>					
									</div>	
									<!-- /Category Content -->
									
									<!-- Price Content -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Pricing Type</h3>
											<div class="form-group price-cont mb-0" id="price_type">
												<select name="price" class="form-control select form-select">
													<option value="0">Select</option>
													<option value="1" selected>Fixed Budget Price</option>
													<option value="2">Hourly Pricing</option>
													<option value="3">Biding Price</option>
												</select>
											</div>
											<div class="form-group mt-3" id="price_id">
												<div class="input-group">
													<button type="button" class="btn btn-white dropdown-toggle" data-bs-toggle="dropdown">$</button>
													<div class="dropdown-menu">
														<a class="dropdown-item" href="#">Dollars</a>
														<a class="dropdown-item" href="#">Euro</a>
														<a class="dropdown-item" href="#">Bitcoin</a>
													</div>
													<input type="text" class="form-control" placeholder="20.00">
												</div>
											</div>
											<div class="form-group mt-3" id="hour_id" style="display: none;">
												<div class="row">
													<div class="col-md-6 mb-2">
														<div class="input-group form-inline">
															<button type="button" class="btn btn-white dropdown-toggle" data-bs-toggle="dropdown">$</button>
															<div class="dropdown-menu">
																<a class="dropdown-item" href="#">Dollars</a>
																<a class="dropdown-item" href="#">Euro</a>
																<a class="dropdown-item" href="#">Bitcoin</a>
															</div>
															<input type="text" class="form-control me-2" placeholder="20.00"> <label> / hr</label>
														</div>
													</div>
													<div class="col-md-6">
														<div class="input-group form-inline">
															<label>For </label> <input type="text" class="form-control ms-2" placeholder=" ( eg: 2 Weeks)"> 
														</div>
													</div>
												</div>
											</div>
										</div>					
									</div>		
									<!-- /Price Content -->
									
									<!-- Skills Content -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Desired areas of expertise </h3>
											<div class="form-group mb-0">
												<tag-input [(ngModel)]='tag' class="form-control tags-service" placeholder="Web Design, Node JS" [ngModelOptions]="{standalone: true}"></tag-input>
												<p class="text-muted mb-0">Enter skills for needed for project</p>
											</div>
										</div>					
									</div>
									<!-- /Skills Content -->
									
									<!-- Project Period Content -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Period of Project</h3>
											<div class="form-group mb-0" id="pro_period">
												<div class="radio">
													<label class="custom_radio">
														<input type="radio" id="price_free" name="period" value="price_free" checked (change)="pricingOption($event);">
														<span class="checkmark" for="price_free"></span>  Start  immediately  after the  candidate is selected
													</label>
												</div>
												<div class="radio">
													<label class="custom_radio">
														<input type="radio" id="price_custom"  name="period" value="custom_price"  (change)="pricingOption($event);">
														<span class="checkmark" for="price_custom"></span>  Job will Start On 
													</label>
												</div>
											</div>
											<div class="row" id="custom_price_cont" *ngIf="ishidden">
												<div class="col-md-4">
													<div class="filter-widget mb-0" id="period_date">
														<div class="cal-icon">
															<input type="date"id="custom_rating_input" name="custom_rating_count" class="form-control datetimepicker" placeholder="Select Date">
														</div>			
													</div>								
												</div>								
											</div>								
										</div>					
									</div>
									<!-- /Project Period Content -->
									
									<!-- /Add Document -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Add Documents</h3>
											<div class="custom-file">
												<input type="file" class="custom-file-input">
												<label class="custom-file-label"></label>
											</div>
											<p>Size of the Document should be Below 2MB</p>
											<div class="upload-wrap">
												<div class="upload-document">
													<img src="assets/img/document.jpg" alt="Image">
													<a href="javascript:void(0);" class="btn btn-icon btn-danger btn-sm"><i class="material-icons">delete_sweep</i></a>
												</div>
												<div class="upload-document">
													<img src="assets/img/document.jpg" alt="Image">
													<a href="javascript:void(0);" class="btn btn-icon btn-danger btn-sm"><i class="material-icons">delete_sweep</i></a>
												</div>
											</div>
										</div>					
									</div>	
									<!-- /Add Document -->
									
									<!-- Add Links -->
									<div class="title-content">
										<div class="title-detail">
											<h3>Add Links</h3>
											<div class="links-info">
												<div class="row form-row links-cont"  *ngFor="let education of educationalArray; let i = index">
													<div class="col-12 col-md-11">
														<div class="form-group">
															<input type="text" class="form-control">
														</div> 
													</div>
													<div class="col-12 col-md-1" *ngIf="i != 0">
														<a href="javascript:void(0);"(click)="deleteEducation(i)" class="btn btn-danger trash"><i class="far fa-trash-alt"></i></a>
													</div>			
												</div>
												<div class="row">
												<div class="col-md-6">
													<p class="mb-0">Add Reference links if any</p>
												</div> 
												<div class="col-md-5 text-end">
													<a href="javascript:void(0);"  (click)="addEducation()" class="add-links more-link"><i class="fas fa-plus-circle orange-text"></i> Add more</a>
												</div>
											</div>
											</div>										
										</div>					
									</div>
									<!-- /Add Links -->	

									<!-- Project Title -->
									<div class="title-content pb-0">
										<div class="title-detail">
											<h3>Write Description of Projects </h3>
											<form [formGroup]="form">
												<div class="editor">
													<ngx-editor-menu [editor]="editor" [toolbar]="toolbar">
													</ngx-editor-menu>
													<ngx-editor [editor]="editor" formControlName="editorContent">
													</ngx-editor>
												</div>
											</form>
										</div>					
									</div>
									<!-- /Project Title -->
									
									<div class="text-end">
										<div class="btn-item">
											<button class="btn btn-primary black-btn click-btn b-0 me-2" type="submit">CANCEL</button>
											<button class="btn btn-primary click-btn b-0" type="submit">SUBMIT</button>
										</div>
									</div>
									
								</div>
								<!-- Project Title -->								

							</form>					
							</div>					
						</div>					
					</div>					
				</div>					
			</div>					
			<!-- /Page Content -->
