// template-vuejs/src/views/frontend/employer/sidebar.vue
<template>
<div class="col-xl-3 col-md-4 theiaStickySidebar">
    <div class="stickyside">
							<div class="settings-widget">
								<div class="settings-header d-sm-flex flex-row flex-wrap text-center text-sm-start align-items-center">
									<router-link to="/user-account-details"><img alt="profile image" src="../../../assets/img/img-04.jpg" class="avatar-lg rounded-circle"></router-link>
									<div class="ms-sm-3 ms-md-0 ms-lg-3 mt-2 mt-sm-0 mt-md-2 mt-lg-0">
										<p class="mb-2">Welcome,</p>
										<router-link to="/user-account-details"><h3 class="mb-0">John Danie S.</h3></router-link>
										<p class="mb-0">@johndaniee</p>
									</div>
								</div>
								
								<div class="settings-menu">
									<ul>
										<li class="nav-item">
											<router-link to="/dashboard" class="nav-link">
												<i class="material-icons">verified_user</i> Dashboard
                                            </router-link>
										</li>
										<li class="nav-item" :class="{'active': currentPath === '/tasks' || currentPath === '/files' || currentPath === '/cancelled-projects' || currentPath === '/completed-projects' || currentPath === '/freelancer-files'}">
											<router-link to="/manage-projects" class="nav-link" :class="currentPath === '/tasks' || currentPath === '/files' || currentPath == 'cancelled-projects' || currentPath === '/completed-projects' || currentPath === '/freelancer-files' ? 'active' : 'notactive'">
												<i class="material-icons">business_center</i> Projects
                                            </router-link>
										</li>
										<li class="nav-item" :class="{'active': currentPath === '/favourites-list' || currentPath === '/invited-favourites'}">
											<router-link to="/favourites" class="nav-link" :class="currentPath == 'favourites-list'  || currentPath === '/invited-favourites' ? 'active' : 'notactive'">
												<i class="material-icons">local_play</i> Favourites
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/review" class="nav-link">
												<i class="material-icons">record_voice_over</i> Reviews
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/chats" class="nav-link">
												<i class="material-icons">chat</i> Messages
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/membership-plans" class="nav-link">
												<i class="material-icons">person_add</i> Membership
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/milestones" class="nav-link">
												<i class="material-icons">pie_chart</i> Milestones
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/verify-identity" class="nav-link">
												<i class="material-icons">person_pin</i> Verify Identity
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/deposit-funds" class="nav-link">
												<i class="material-icons">wifi_tethering</i> Payments
                                            </router-link>
										</li>
										
										<li class="nav-item" :class="{'active': currentPath === '/change-password' || currentPath === '/delete-account'}">
											<router-link to="/profile-settings" class="nav-link" :class="currentPath == 'change-password' || currentPath == 'delete-account' ? 'active' : 'notactive'">
												<i class="material-icons">settings</i> Settings
                                            </router-link>
										</li>
										<li class="nav-item">
											<router-link to="/" class="nav-link">
												<i class="material-icons">power_settings_new</i> Logout
                                            </router-link>
										</li>
									</ul>
								</div>
							</div>	
                            </div>				
						</div>
</template>
<script>
    export default {
        computed: {
            currentPath() {
                return this.$route.name;
            }
    
        },  
    mounted() {
      },
    data() {
        return {
          activeClass: 'active',
        };
                //  isactive : true
      },
    }
    </script>

// template-react/src/frontend/components/foremployers/sidebar/index.jsx
import React from "react";
import { Link } from "react-router-dom";
import { Img_04 } from "../../imagepath"

const Sidebar = (props) => { 

    const pathname = window.location.pathname.split("/")[1];
   
        return (
            <>
               <div className="settings-widget">
                    <div className="settings-header d-sm-flex flex-row flex-wrap text-center text-sm-start align-items-center">
                        <Link to="/user-account-details">
                        <img
                            alt="profile image"
                            src={Img_04}
                            className="avatar-lg rounded-circle"
                        />
                        </Link>
                        <div className="ms-sm-3 ms-md-0 ms-lg-3 mt-2 mt-sm-0 mt-md-2 mt-lg-0">
                            <p className="mb-2">Welcome,</p>
                            <Link to="user-account-details">
                                <h3 className="mb-0">John Danie S.</h3>
                            </Link>
                            <p className="mb-0">@johndaniee</p>
                        </div>
                    </div>
                <div className="settings-menu">
                    <ul>
                        <li className="nav-item">
                            <Link to="/dashboard" className={`nav-link ${pathname === "dashboard" ? "active" : ""}`}>
                            <i className="material-icons">verified_user</i> Dashboard
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/manage-projects" className={`nav-link ${pathname === "-projects" ? "active" : ""}`}>
                            <i className="material-icons">business_center</i> Projects
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/favourites" className={`nav-link ${pathname === "favourites" || 
                             pathname === "invited-freelancer" ? "active" : ""}`}>
                            <i className="material-icons">local_play</i> Favourites
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/review" className={`nav-link ${pathname === "review" ? "active" : ""}`}>
                            <i className="material-icons">record_voice_over</i> Reviews
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/chats" className={`nav-link ${pathname === "chats" ? "active" : ""}`}>
                            <i className="material-icons">chat</i> Messages
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/membership-plans" className={`nav-link ${pathname === "membership-plans" ? "active" : ""}`}>
                            <i className="material-icons">person_add</i> Membership
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/milestones" className={`nav-link ${pathname === "milestones" ? "active" : ""}`}>
                            <i className="material-icons">pie_chart</i> Milestones
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/verify-identity" className={`nav-link ${pathname === "verify-identity" ? "active" : ""}`}>
                            <i className="material-icons">person_pin</i> Verify Identity
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/deposit-funds" className={`nav-link ${pathname === "deposit-funds" ||
                            pathname === "withdraw-money" || pathname === "transaction-history" ? "active" : ""}`}>
                            <i className="material-icons">wifi_tethering</i> Payments
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/profile-settings" className={`nav-link ${pathname === "profile-settings" || 
                            pathname === "change-password" || pathname === "delete-account" ? "active" : ""}`}>
                            <i className="material-icons">settings</i> Settings
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/" className="nav-link">
                            <i className="material-icons">power_settings_new</i> Logout
                            </Link>
                        </li>
                    </ul>
                </div>
            </div>
            </>
         )
          
}
export { Sidebar };
