// template-angular/src/app/features-modules/employer/dashboard/dashboard.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import {
  ChartComponent,
  ApexAxisChartSeries,
  ApexChart,
  ApexXAxis,
  ApexDataLabels,
  ApexTitleSubtitle,
  ApexStroke,
  ApexGrid,
  ApexNonAxisChartSeries,
  ApexPlotOptions,
} from "ng-apexcharts";

export type ChartOptions = {
  series: ApexAxisChartSeries| any;
  chart: ApexChart| any;
  xaxis: ApexXAxis| any;
  dataLabels: ApexDataLabels| any;
  grid: ApexGrid| any;
  stroke: ApexStroke| any;
  title: ApexTitleSubtitle| any;
};
export type radialChartOptions = {
  series: ApexNonAxisChartSeries | any;
  chart: ApexChart | any;
  labels: string[] | any;
  plotOptions: ApexPlotOptions | any;
};

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent {

  @ViewChild("chart") chart: ChartComponent | any;
  public chartOptions: Partial<ChartOptions>;
  public radialchartOptions: Partial<ChartOptions> | any;
  
  constructor() {
    this.chartOptions = {
      series: [
        {
          name: "Desktops",
          data: [10, 41, 35, 51, 49, 62, 69, 91, 148]
        }
      ],
      chart: {
        height: 350,
        type: "line",
        zoom: {
          enabled: false
        }
      },
      dataLabels: {
        enabled: false
      },
      stroke: {
        curve: "straight"
      },
      title: {
        text: "Product Trends by Month",
        align: "left"
      },
      grid: {
        row: {
          colors: ["#f3f3f3", "transparent"], // takes an array which will be repeated on columns
          opacity: 0.5
        }
      },
      xaxis: {
        categories: [
          "Jan",
          "Feb",
          "Mar",
          "Apr",
          "May",
          "Jun",
          "Jul",
          "Aug",
          "Sep"
        ]
      }
    };


    this.radialchartOptions = {
      series: [44, 55, 67, 83],
      chart: {
        height: 350,
        type: "radialBar"
      },
      plotOptions: {
        radialBar: {
          dataLabels: {
            name: {
              fontSize: "22px"
            },
            value: {
              fontSize: "16px"
            },
            total: {
              show: true,
              label: "Total",
              formatter: function() {
                return "249";
              }
            }
          }
        }
      },
      labels: ["Apples", "Oranges", "Bananas", "Berries"]
    };
  }
 
  ngOnInit() {
  }

}

<div class="dashboard-sec">
    <div class="row">
        <div class="col-md-6 col-lg-4">
            <div class="dash-widget">
                <div class="dash-info">
                    <div class="dash-widget-info">Projects Posted</div>
                    <div class="dash-widget-count">30</div>
                </div>
                <div class="dash-widget-more">
                    <a [routerLink] = "'/employer/manage-projects/all-projects'" class="d-flex">View Details <i class="fas fa-arrow-right ms-auto"></i></a>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4">
            <div class="dash-widget">
                <div class="dash-info">
                    <div class="dash-widget-info">Ongoing Projects</div>
                    <div class="dash-widget-count">5</div>
                </div>
                <div class="dash-widget-more">
                    <a [routerLink] = "'/employer/manage-projects/ongoing-projects'" class="d-flex">View Details <i class="fas fa-arrow-right ms-auto"></i></a>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4">
            <div class="dash-widget">
                <div class="dash-info">
                    <div class="dash-widget-info">Completed Projects</div>
                    <div class="dash-widget-count">25</div>
                </div>
                <div class="dash-widget-more">
                    <a [routerLink] = "'/employer/manage-projects/completed-projects'"  class="d-flex">View Details <i class="fas fa-arrow-right ms-auto"></i></a>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Chart Content -->
    <div class="row">
        <div class="col-xl-8 d-flex">
            <div class="card flex-fill">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="card-title">Profile Views</h5>
                        <div class="dropdown">
                            <button class="btn btn-white btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Monthly
                            </button>
                            <div class="dropdown-menu dropdown-menu-start">
                                <a href="javascript:void(0);" class="dropdown-item">Weekly</a>
                                <a href="javascript:void(0);" class="dropdown-item">Monthly</a>
                                <a href="javascript:void(0);" class="dropdown-item">Yearly</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">									
                    <div id="chartprofile">
                        <apx-chart
                        [series]="chartOptions.series"
                        [chart]="chartOptions.chart"
                        [xaxis]="chartOptions.xaxis"
                        [dataLabels]="chartOptions.dataLabels"
                        [grid]="chartOptions.grid"
                        [stroke]="chartOptions.stroke"
                        [title]="chartOptions.title"
                      ></apx-chart>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-4 d-flex">
            <div class="card flex-fill">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="card-title">Static Analytics</h5>
                        <div class="dropdown">
                            <button class="btn btn-white btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Monthly
                            </button>
                            <div class="dropdown-menu dropdown-menu-start">
                                <a href="javascript:void(0);" class="dropdown-item">Weekly</a>
                                <a href="javascript:void(0);" class="dropdown-item">Monthly</a>
                                <a href="javascript:void(0);" class="dropdown-item">Yearly</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">									
                    <div id="chartradial">
                        <apx-chart
                        [series]="radialchartOptions.series"
                        [chart]="radialchartOptions.chart"
                        [plotOptions]="radialchartOptions.plotOptions"
                        [labels]="radialchartOptions.labels"
                      ></apx-chart>
                    </div>
                    <ul class="static-list">
                        <li><span><i class="fas fa-circle text-violet me-1"></i> Applied Jobs</span> <span class="sta-count">30</span></li>
                        <li><span><i class="fas fa-circle text-pink me-1"></i> Active Proposals</span> <span class="sta-count">30</span></li>
                        <li><span><i class="fas fa-circle text-yellow me-1"></i> Applied Proposals</span> <span class="sta-count">30</span></li>
                        <li><span><i class="fas fa-circle text-blue me-1"></i> Bookmarked Projects</span> <span class="sta-count">30</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /Chart Content -->
    
    <!-- Past Earnings -->
    <div class="row">
        <div class="col-md-12">
            <div class="card card-table">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h4 class="card-title">Recently Posted Jobs</h4>
                        </div>
                        <div class="col-auto">
                            <a [routerLink] = "'/employer/manage-projects/all-projects'" class="btn-right btn btn-sm fund-btn">
                                View All 
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive table-job">	
                        <table class="table table-hover table-center mb-0">
                            <thead class="thead-pink">
                                <tr>
                                    <th>Details</th>
                                    <th>Job Type</th>
                                    <th>Budget</th>
                                    <th>Created on</th>
                                    <th>Proposals</th>
                                    <th class="text-end">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <span class="detail-text">I want some customization and installation on wordpress</span>
                                        <span class="d-block text-expiry">Expiring on : February 3, 2019</span>
                                    </td>
                                    <td>Full-Time</td>
                                    <td><span class="table-budget">BUDGET</span> <span class="d-block text-danger">$600 - $1500</span></td>
                                    <td>12 July, 2021</td>
                                    <td>47</td>
                                    <td class="text-end"><a [routerLink] = "'/employer/milestones/overviews'" class="text-success">View</a></td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="detail-text">I want some customization and installation on wordpress</span>
                                        <span class="d-block text-expiry">Expiring on : February 3, 2019</span>
                                    </td>
                                    <td>Full-Time</td>
                                    <td><span class="table-budget">BUDGET</span> <span class="d-block text-danger">$600 - $1500</span></td>
                                    <td>12 July, 2021</td>
                                    <td>47</td>
                                    <td class="text-end"><a [routerLink] = "'/employer/milestones/overviews'" class="text-success">View</a></td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="detail-text">I want some customization and installation on wordpress</span>
                                        <span class="d-block text-expiry">Expiring on : February 3, 2019</span>
                                    </td>
                                    <td>Full-Time</td>
                                    <td><span class="table-budget">BUDGET</span> <span class="d-block text-danger">$600 - $1500</span></td>
                                    <td>12 July, 2021</td>
                                    <td>47</td>
                                    <td class="text-end"><a [routerLink] = "'/employer/milestones/overviews'" class="text-success">View</a></td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="detail-text">I want some customization and installation on wordpress</span>
                                        <span class="d-block text-expiry">Expiring on : February 3, 2019</span>
                                    </td>
                                    <td>Full-Time</td>
                                    <td><span class="table-budget">BUDGET</span> <span class="d-block text-danger">$600 - $1500</span></td>
                                    <td>12 July, 2021</td>
                                    <td>47</td>
                                    <td class="text-end"><a [routerLink] = "'/employer/milestones/overviews'" class="text-success">View</a></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Past Earnings -->
    
    <div class="row">
        <!-- Plan  Details-->
        <div class="col-xl-6 d-flex">					
            <div class="card flex-fill">
                <div class="card-header">
                    <div class="row justify-content-between align-items-center">
                        <div class="col">
                            <h5 class="card-title">Membership Plan Details</h5>
                        </div>
                        <div class="col-auto">
                            <a href="javascript:void(0);" class="btn-right btn btn-sm fund-btn">
                                View 
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="plan-details">
                                <h4>The Ultima</h4>
                                <div class="yr-amt">Anually Price</div>
                                <h4>$1200</h4>
                                <div class="yr-duration">Duration: One Year</div>
                                <div class="expiry">Expiry: 24 JAN 2022</div>
                                <a [routerLink] = "'/employer/membership-plans'" class="btn btn-primary btn-plan">Change Plan</a>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="plan-feature">
                                <ul>
                                    <li>12 Project Credits</li>
                                    <li>10 Allowed Services</li>
                                    <li>20 Days visibility</li>
                                    <li>5 Featured Services</li>
                                    <li>20 Days visibility</li>
                                    <li>30 Days Package Expiry</li>
                                    <li>Profile Featured</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Plan  Details -->
        
        <!-- Notifications -->
        <div class="col-xl-6 d-flex">					
            <div class="card flex-fill">
                <div class="card-header">
                    <div class="row justify-content-between align-items-center">
                        <div class="col">
                            <h5 class="card-title">Notifications</h5>
                        </div>
                        <div class="col-auto">
                            <a [routerLink] = "'/freelancer/freelancer-projects/ongoing-projects'" class="btn-right btn btn-sm fund-btn">
                                View All 
                            </a>
                        </div>
                    </div>
                </div>
                <div class="pro-body p-0">
                    <div class="news-feature">
                        <img class="avatar-sm rounded-circle" src="assets/img/img-02.jpg" alt="User Image">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. At diam sit erat et eros. </p>
                    </div>
                    <div class="news-feature">
                        <img class="avatar-sm rounded-circle" src="assets/img/img-03.jpg" alt="User Image">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. At diam sit erat et eros. </p>
                    </div>
                    <div class="news-feature">
                        <img class="avatar-sm rounded-circle" src="assets/img/img-04.jpg" alt="User Image">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. At diam sit erat et eros. </p>
                    </div>
                    <div class="news-feature">
                        <img class="avatar-sm rounded-circle" src="assets/img/img-05.jpg" alt="User Image">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. At diam sit erat et eros. </p>
                    </div>
                    <div class="news-feature">
                        <img class="avatar-sm rounded-circle" src="assets/img/img-01.png" alt="User Image">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. At diam sit erat et eros. </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Notifications -->
    </div>
    
</div>

// template-react/src/frontend/components/foremployers/dashboard/index.jsx
import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import StickyBox from "react-sticky-box";
import ApexCharts from 'apexcharts';
import { home_icon, Img_01, Img_02, Img_03, Img_04, Img_05 } from "../../imagepath";
import { Sidebar } from '../sidebar';

const Dashboard = (props) => {

  var chartprofileoptions = {
    series: [{
      name: "profile view",
      data: [100, 150, 200, 250, 200, 250, 200, 200, 200, 200, 300, 350]
    }],
    chart: {
      height: 360,
      type: 'line',
      toolbar: {
        show: false
      },
      zoom: {
        enabled: false
      }
    },
    dataLabels: {
      enabled: false
    },
    colors: ["#FF5B37"],
    stroke: {
      curve: 'straight',
      width: [1]
    },
    markers: {
      size: 4,
      colors: ["#FF5B37"],
      strokeColors: "#FF5B37",
      strokeWidth: 1,
      hover: {
        size: 7,
      }
    },
    grid: {
      position: 'front',
      borderColor: '#ddd',
      strokeDashArray: 7,
      xaxis: {
        lines: {
          show: true
        }
      }
    },
    xaxis: {
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      lines: {
        show: false,
      }
    },
    yaxis: {
      lines: {
        show: true,
      }
    }
  };

  var chartradialOptions = {
    series: [85, 75, 60, 40],
    chart: {
      toolbar: {
        show: false
      },
      height: 250,
      type: 'radialBar',
    },
    plotOptions: {
      radialBar: {
        offsetY: 0,
        startAngle: 0,
        endAngle: 270,
        hollow: {
          margin: 5,
          size: '50%',
          background: 'transparent',
          image: undefined,
        },
        dataLabels: {
          name: {
            show: false,
          },
          value: {
            show: false,
          }
        }
      }
    },
    colors: ['#7B46BE', '#FA6CA4', '#FACD3A', '#24C0DC'],
    labels: ['Applied Jobs', 'Messenger', 'Facebook', 'LinkedIn'],
    legend: {
      show: false,
      floating: true,
      fontSize: '16px',
      position: 'bottom',
      offsetX: 160,
      offsetY: 15,
      labels: {
        useSeriesColors: true,
      },
      markers: {
        size: 0
      },
      formatter: function (seriesName, opts) {
        return seriesName + ":  " + opts.w.globals.series[opts.seriesIndex]
      },
      itemMargin: {
        vertical: 3
      }
    },
    responsive: [{
      breakpoint: 480,
      options: {
        legend: {
          show: false
        }
      }
    }]
  };
  useEffect(() => {
    let chartprofileoptionsColumn = document.getElementById("chartprofile");
    let chartprofileoptionsChart = new ApexCharts(chartprofileoptionsColumn, chartprofileoptions);
    chartprofileoptionsChart.render();

    let invoiceColumn = document.getElementById("chartradial");
    let invoiceChart = new ApexCharts(invoiceColumn, chartradialOptions);
    invoiceChart.render();
    document.body.className = 'dashboard-page';
    return () => { document.body.className = ''; }
  });
  return (
    <>
      {/* Breadcrumb */}
      <div className="bread-crumb-bar">
        <div className="container">
          <div className="row align-items-center inner-banner">
            <div className="col-md-12 col-12 text-center">
              <div className="breadcrumb-list">
                <nav aria-label="breadcrumb" className="page-breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item"><Link to="#"><img src={home_icon} alt="Post Author" /> Home</Link></li>
                    <li className="breadcrumb-item" aria-current="page">Employee</li>
                    <li className="breadcrumb-item" aria-current="page">Dashboard</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Breadcrumb */}
      {/* Page Content */}
      <div className="content content-page">
        <div className="container-fluid">
          <div className="row">
            {/* sidebar */}
            <div className="col-xl-3 col-md-4 theiaStickySidebar">
              <StickyBox offsetTop={20} offsetBottom={20}>
                <Sidebar />
              </StickyBox>
            </div>
            {/* /sidebar */}
            <div className="col-xl-9 col-md-8">
              <div className="dashboard-sec">
                <div className="row">
                  <div className="col-md-6 col-lg-4">
                    <div className="dash-widget">
                      <div className="dash-info">
                        <div className="dash-widget-info">Projects Posted</div>
                        <div className="dash-widget-count">30</div>
                      </div>
                      <div className="dash-widget-more">
                        <Link to="/manage-projects" className="d-flex">
                          View Details <i className="fas fa-arrow-right ms-auto" />
                        </Link>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-6 col-lg-4">
                    <div className="dash-widget">
                      <div className="dash-info">
                        <div className="dash-widget-info">Ongoing Projects</div>
                        <div className="dash-widget-count">5</div>
                      </div>
                      <div className="dash-widget-more">
                        <Link to="/ongoing-projects" className="d-flex">
                          View Details <i className="fas fa-arrow-right ms-auto" />
                        </Link>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-6 col-lg-4">
                    <div className="dash-widget">
                      <div className="dash-info">
                        <div className="dash-widget-info">Completed Projects</div>
                        <div className="dash-widget-count">25</div>
                      </div>
                      <div className="dash-widget-more">
                        <Link to="/completed-projects" className="d-flex">
                          View Details <i className="fas fa-arrow-right ms-auto" />
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
                {/* Chart Content */}
                <div className="row">
                  <div className="col-xl-8 d-flex">
                    <div className="card flex-fill">
                      <div className="card-header">
                        <div className="d-flex justify-content-between align-items-center">
                          <h5 className="card-title">Profile Views</h5>
                          <div className="dropdown">
                            <button
                              className="btn btn-white btn-sm dropdown-toggle"
                              type="button"
                              data-bs-toggle="dropdown"
                              aria-haspopup="true"
                              aria-expanded="false"
                            >
                              Monthly
                            </button>
                            <div className="dropdown-menu dropdown-menu-start">
                              <a
                                href=""
                                className="dropdown-item"
                              >
                                Weekly
                              </a>
                              <a
                                href=""
                                className="dropdown-item"
                              >
                                Monthly
                              </a>
                              <a
                                href=""
                                className="dropdown-item"
                              >
                                Yearly
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="card-body">
                        <div id="chartprofile" />
                      </div>
                    </div>
                  </div>
                  <div className="col-xl-4 d-flex">
                    <div className="card flex-fill">
                      <div className="card-header">
                        <div className="d-flex justify-content-between align-items-center">
                          <h5 className="card-title">Static Analytics</h5>
                          <div className="dropdown">
                            <button
                              className="btn btn-white btn-sm dropdown-toggle"
                              type="button"
                              data-bs-toggle="dropdown"
                              aria-haspopup="true"
                              aria-expanded="false"
                            >
                              Monthly
                            </button>
                            <div className="dropdown-menu dropdown-menu-start">
                              <a
                                href=""
                                className="dropdown-item"
                              >
                                Weekly
                              </a>
                              <a
                                href=""
                                className="dropdown-item"
                              >
                                Monthly
                              </a>
                              <a
                                href=""
                                className="dropdown-item"
                              >
                                Yearly
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="card-body">
                        <div id="chartradial" />
                        <ul className="static-list">
                          <li>
                            <span>
                              <i className="fas fa-circle text-violet me-1" />{" "}
                              Applied Jobs
                            </span>{" "}
                            <span className="sta-count">30</span>
                          </li>
                          <li>
                            <span>
                              <i className="fas fa-circle text-pink me-1" /> Active
                              Proposals
                            </span>{" "}
                            <span className="sta-count">30</span>
                          </li>
                          <li>
                            <span>
                              <i className="fas fa-circle text-yellow me-1" />{" "}
                              Applied Proposals
                            </span>{" "}
                            <span className="sta-count">30</span>
                          </li>
                          <li>
                            <span>
                              <i className="fas fa-circle text-blue me-1" />{" "}
                              Bookmarked Projects
                            </span>{" "}
                            <span className="sta-count">30</span>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                {/* /Chart Content */}
                {/* Past Earnings */}
                <div className="row">
                  <div className="col-md-12">
                    <div className="card card-table">
                      <div className="card-header">
                        <div className="row">
                          <div className="col">
                            <h4 className="card-title">Recently Posted Jobs</h4>
                          </div>
                          <div className="col-auto">
                            <Link
                              to="/manage-projects"
                              className="btn-right btn btn-sm fund-btn"
                            >
                              View All
                            </Link>
                          </div>
                        </div>
                      </div>
                      <div className="card-body">
                        <div className="table-responsive table-job">
                          <table className="table table-hover table-center mb-0">
                            <thead className="thead-pink">
                              <tr>
                                <th>Details</th>
                                <th>Job Type</th>
                                <th>Budget</th>
                                <th>Created on</th>
                                <th>Proposals</th>
                                <th className="text-end">Action</th>
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <td>
                                  <span className="detail-text">
                                    I want some customization and installation on
                                    wordpress
                                  </span>
                                  <span className="d-block text-expiry">
                                    Expiring on : February 3, 2019
                                  </span>
                                </td>
                                <td>Full-Time</td>
                                <td>
                                  <span className="table-budget">BUDGET</span>{" "}
                                  <span className="d-block text-danger">
                                    $600 - $1500
                                  </span>
                                </td>
                                <td>12 July, 2021</td>
                                <td>47</td>
                                <td className="text-end">
                                  <Link
                                    to="/view-project-detail"
                                    className="text-success"
                                  >
                                    View
                                  </Link>
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  <span className="detail-text">
                                    I want some customization and installation on
                                    wordpress
                                  </span>
                                  <span className="d-block text-expiry">
                                    Expiring on : February 3, 2019
                                  </span>
                                </td>
                                <td>Full-Time</td>
                                <td>
                                  <span className="table-budget">BUDGET</span>{" "}
                                  <span className="d-block text-danger">
                                    $600 - $1500
                                  </span>
                                </td>
                                <td>12 July, 2021</td>
                                <td>47</td>
                                <td className="text-end">
                                  <Link
                                    to="/view-project-detail"
                                    className="text-success"
                                  >
                                    View
                                  </Link>
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  <span className="detail-text">
                                    I want some customization and installation on
                                    wordpress
                                  </span>
                                  <span className="d-block text-expiry">
                                    Expiring on : February 3, 2019
                                  </span>
                                </td>
                                <td>Full-Time</td>
                                <td>
                                  <span className="table-budget">BUDGET</span>{" "}
                                  <span className="d-block text-danger">
                                    $600 - $1500
                                  </span>
                                </td>
                                <td>12 July, 2021</td>
                                <td>47</td>
                                <td className="text-end">
                                  <Link
                                    to="/view-project-detail"
                                    className="text-success"
                                  >
                                    View
                                  </Link>
                                </td>
                              </tr>
                              <tr>
                                <td>
                                  <span className="detail-text">
                                    I want some customization and installation on
                                    wordpress
                                  </span>
                                  <span className="d-block text-expiry">
                                    Expiring on : February 3, 2019
                                  </span>
                                </td>
                                <td>Full-Time</td>
                                <td>
                                  <span className="table-budget">BUDGET</span>{" "}
                                  <span className="d-block text-danger">
                                    $600 - $1500
                                  </span>
                                </td>
                                <td>12 July, 2021</td>
                                <td>47</td>
                                <td className="text-end">
                                  <Link
                                    to="/view-project-detail"
                                    className="text-success"
                                  >
                                    View
                                  </Link>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {/* /Past Earnings */}
                <div className="row">
                  {/* Plan  Details*/}
                  <div className="col-xl-6 d-flex">
                    <div className="card flex-fill">
                      <div className="card-header">
                        <div className="row justify-content-between align-items-center">
                          <div className="col">
                            <h5 className="card-title">Membership Plan Details</h5>
                          </div>
                          <div className="col-auto">
                            <a
                              href=""
                              className="btn-right btn btn-sm fund-btn"
                            >
                              View
                            </a>
                          </div>
                        </div>
                      </div>
                      <div className="card-body">
                        <div className="row">
                          <div className="col-md-6 col-sm-6">
                            <div className="plan-details">
                              <h4>The Ultima</h4>
                              <div className="yr-amt">Anually Price</div>
                              <h4>$1200</h4>
                              <div className="yr-duration">Duration: One Year</div>
                              <div className="expiry">Expiry: 24 JAN 2022</div>
                              <Link
                                to="/membership-plans"
                                className="btn btn-primary btn-plan"
                              >
                                Change Plan
                              </Link>
                            </div>
                          </div>
                          <div className="col-md-6 col-sm-6">
                            <div className="plan-feature">
                              <ul>
                                <li>12 Project Credits</li>
                                <li>10 Allowed Services</li>
                                <li>20 Days visibility</li>
                                <li>5 Featured Services</li>
                                <li>20 Days visibility</li>
                                <li>30 Days Package Expiry</li>
                                <li>Profile Featured</li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Plan  Details */}
                  {/* Notifications */}
                  <div className="col-xl-6 d-flex">
                    <div className="card flex-fill">
                      <div className="card-header">
                        <div className="row justify-content-between align-items-center">
                          <div className="col">
                            <h5 className="card-title">Notifications</h5>
                          </div>
                          <div className="col-auto">
                            <Link
                              to="/freelancer-ongoing-projects"
                              className="btn-right btn btn-sm fund-btn"
                            >
                              View All
                            </Link>
                          </div>
                        </div>
                      </div>
                      <div className="pro-body p-0">
                        <div className="news-feature">
                          <img
                            className="avatar-sm rounded-circle"
                            src={Img_02}
                            alt="User Image"
                          />
                          <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            At diam sit erat et eros.{" "}
                          </p>
                        </div>
                        <div className="news-feature">
                          <img
                            className="avatar-sm rounded-circle"
                            src={Img_03}
                            alt="User Image"
                          />
                          <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            At diam sit erat et eros.{" "}
                          </p>
                        </div>
                        <div className="news-feature">
                          <img
                            className="avatar-sm rounded-circle"
                            src={Img_04}
                            alt="User Image"
                          />
                          <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            At diam sit erat et eros.{" "}
                          </p>
                        </div>
                        <div className="news-feature">
                          <img
                            className="avatar-sm rounded-circle"
                            src={Img_05}
                            alt="User Image"
                          />
                          <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            At diam sit erat et eros.{" "}
                          </p>
                        </div>
                        <div className="news-feature">
                          <img
                            className="avatar-sm rounded-circle"
                            src={Img_01}
                            alt="User Image"
                          />
                          <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            At diam sit erat et eros.{" "}
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* /Notifications */}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Page Content */}
    </>
  )

}
export default Dashboard;
