// template-vuejs/src/views/frontend/freelancer/sidebar.vue
<template>
   <div class="col-xl-3 col-md-4 theiaStickySidebar">
                            <div class="stickyside">
                            <div class="settings-widget">
                                <div class="settings-header d-sm-flex flex-row flex-wrap text-center text-sm-start align-items-center">
                                    <router-link to="/freelancer-profile"><img alt="profile image" src="../../../assets/img/user/avatar-1.jpg" class="avatar-lg rounded-circle"></router-link>
                                    <div class="ms-sm-3 ms-md-0 ms-lg-3 mt-2 mt-sm-0 mt-md-2 mt-lg-0">
                                        <p class="mb-2">Welcome,</p>
                                        <h3 class="mb-0"><router-link to="/freelancer-profile">George Wells</router-link></h3>
                                        <p class="mb-0">@georgewell</p>
                                    </div>
                                </div>
                                <div class="settings-menu">
                                    <ul>
                                        <li class="nav-item">
                                            <router-link to="/freelancer-dashboard" class="nav-link">
                                                <i class="material-icons">verified_user</i> Dashboard
                                            </router-link>
                                        </li>
                                        <li class="nav-item" :class="{'active': currentPath === '/freelancer-completed-projects'}">
                                            <router-link to="/freelancer-project-proposals" class="nav-link" :class="currentPath == 'freelancer-completed-projects' ? 'active' : 'notactive'">
                                                <i class="material-icons">business_center</i> Projects
                                            </router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link to="/freelancer-favourites" class="nav-link">
                                                <i class="material-icons">local_play</i> Favourites
                                            </router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link to="/freelancer-review" class="nav-link">
                                                <i class="material-icons">record_voice_over</i> Reviews
                                            </router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link to="/freelancer-portfolio" class="nav-link">
                                                <i class="material-icons">pie_chart</i> Portfolio
                                            </router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link to="/freelancer-chats" class="nav-link">
                                                <i class="material-icons">chat</i> Messages
                                            </router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link to="/freelancer-membership" class="nav-link">
                                                <i class="material-icons">person_add</i> Membership
                                            </router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link to="/freelancer-verify-identity" class="nav-link">
                                                <i class="material-icons">person_pin</i> Verify Identity
                                            </router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link to="/freelancer-withdraw-money" class="nav-link">
                                                <i class="material-icons">wifi_tethering</i> Payments
                                            </router-link>
                                        </li>
                                        <li class="nav-item" :class="{'active': currentPath === '/freelancer-change-password' || currentPath === '/freelancer-delete-account'}">
                                            <router-link to="/freelancer-profile-settings" class="nav-link" :class="currentPath == 'freelancer-change-password' || currentPath === '/freelancer-delete-account' ? 'active' : 'notactive'">
                                                <i class="material-icons">settings</i>  Settings
                                            </router-link>
                                        </li>
                                        <li class="nav-item">
                                            <router-link to="/" class="nav-link">
                                                <i class="material-icons">power_settings_new</i> Logout
                                            </router-link>
                                        </li>
                                    </ul>
                                </div>
                            </div>	
                            </div>				
                        </div>
</template>
<script>
    export default {
        computed: {
            currentPath() {
                return this.$route.name;
            }
    
        },  
    mounted() {
      },
    data() {
        return {
          activeClass: 'active',
        };
                //  isactive : true
      },
    }
    </script>

// template-react/src/frontend/components/forfreelancer/sidebar/index.jsx
import React from "react";
import { Link } from "react-router-dom";
import { Img_04 } from "../../imagepath"

const Sidebar = (props) => { 

        const pathname = window.location.pathname.split("/")[1];
        return (
            <>
                <div className="settings-widget">
                    <div className="settings-header d-sm-flex flex-row flex-wrap text-center text-sm-start align-items-center">
                        <Link to="freelancer-profile">
                            <img
                            alt="profile image"
                            src={Img_04}
                            className="avatar-lg rounded-circle"
                            />
                        </Link>
                        <div className="ms-sm-3 ms-md-0 ms-lg-3 mt-2 mt-sm-0 mt-md-2 mt-lg-0">
                            <p className="mb-2">Welcome,</p>
                            <h3 className="mb-0">
                            <Link to="/freelancer-profile">John Danie S.</Link>
                            </h3>
                            <p className="mb-0">@johndaniee</p>
                        </div>
                    </div>
                    <div className="settings-menu">
                        <ul>
                            <li className="nav-item">
                            <Link to="/freelancer-dashboard" className={`nav-link ${pathname === "freelancer-dashboard" ? "active" : ""}`}>
                                <i className="material-icons">verified_user</i> Dashboard
                            </Link>
                            </li>
                            <li className="nav-item">
                            <Link to="/freelancer-project-proposals"
                                className={`nav-link ${pathname === "freelancer-project-proposals" ? "active" : ""}`}
                            >
                                <i className="material-icons">business_center</i> Projects
                            </Link>
                            </li>
                            <li className="nav-item">
                            <Link to="/freelancer-favourites" className={`nav-link ${pathname === "freelancer-favourites" ? "active" : ""}`}>
                                <i className="material-icons">local_play</i> Favourites
                            </Link>
                            </li>
                            <li className="nav-item">
                            <Link to="/freelancer-review" className={`nav-link ${pathname === "freelancer-review" ? "active" : ""}`}>
                                <i className="material-icons">record_voice_over</i> Reviews
                            </Link>
                            </li>
                            <li className="nav-item">
                            <Link to="/freelancer-portfolio" className={`nav-link ${pathname === "freelancer-portfolio" ? "active" : ""}`}>
                                <i className="material-icons">pie_chart</i> Portfolio
                            </Link>
                            </li>
                            <li className="nav-item">
                            <Link to="/freelancer-chats" className={`nav-link ${pathname === "freelancer-chats" ? "active" : ""}`}>
                                <i className="material-icons">chat</i> Messages
                            </Link>
                            </li>
                            <li className="nav-item">
                            <Link to="/freelancer-membership" className={`nav-link ${pathname === "freelancer-membership" ? "active" : ""}`}>
                                <i className="material-icons">person_add</i> Membership
                            </Link>
                            </li>
                            <li className="nav-item">
                            <Link to="/freelancer-verify-identity"
                                className={`nav-link ${pathname === "freelancer-verify-identity" ? "active" : ""}`}
                            >
                                <i className="material-icons">person_pin</i> Verify Identity
                            </Link>
                            </li>
                            <li className="nav-item">
                            <Link to="/freelancer-withdraw-money"
                                className={`nav-link ${pathname === "freelancer-withdraw-money" ? "active" : ""}`}
                            >
                                <i className="material-icons">wifi_tethering</i> Payments
                            </Link>
                            </li>
                            <li className="nav-item">
                            <Link to="/freelancer-profile-settings"
                                className={`nav-link ${pathname === "freelancer-profile-settings" ? "active" : ""}`}
                            >
                                <i className="material-icons">settings</i> Settings
                            </Link>
                            </li>
                            <li className="nav-item">
                                <Link to="/" className="nav-link">
                                    <i className="material-icons">power_settings_new</i> Logout
                                </Link>
                            </li>
                        </ul>
                    </div>
                </div>
            </>
         )
        
}
export { Sidebar };
