// template-react/src/frontend/components/foremployers/settings/index.jsx
import React , {useEffect} from "react";
import { Link } from "react-router-dom";
import StickyBox from "react-sticky-box";
import { home_icon, Img_02 } from "../../imagepath";
import { Sidebar } from '../sidebar';
    
const Settings = (props) => {   
  useEffect(() => {
    document.body.className = 'dashboard-page';
    return () => { document.body.className = ''; }
  });  
        
  return (
    <>
    {/* Breadcrumb */}
    <div className="bread-crumb-bar">
        <div className="container">
          <div className="row align-items-center inner-banner">
            <div className="col-md-12 col-12 text-center">
              <div className="breadcrumb-list">
                <nav aria-label="breadcrumb" className="page-breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item"><Link to="#"><img src={home_icon} alt="Post Author" /> Home</Link></li>
                    <li className="breadcrumb-item" aria-current="page">Employee</li>
                    <li className="breadcrumb-item" aria-current="page">Settings</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Breadcrumb */}
    {/* Page Content */}
    <div className="content content-page">
      <div className="container-fluid">
        <div className="row">
          {/* sidebar */}
          <div className="col-xl-3 col-md-4 theiaStickySidebar">
              <StickyBox offsetTop={20} offsetBottom={20}>
                <Sidebar/>
              </StickyBox>
          </div>
          {/* /sidebar */}
          <div className="col-xl-9 col-md-8">
            <div className="pro-pos">
              <nav className="user-tabs mb-4">
                <ul className="nav nav-tabs nav-tabs-bottom nav-justified">
                  <li className="nav-item">
                    <Link className="nav-link active" to="/profile-settings">
                      Basic Settings
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/change-password">
                      Change Password
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/delete-account">
                      Delete Account
                    </Link>
                  </li>
                </ul>
              </nav>
              <div className="setting-content">
                <div className="card">
                  <div className="pro-head">
                    <h3 className="pro-title without-border mb-0">
                      Profile Basics{" "}
                    </h3>
                  </div>
                  <form >
                    <div className="pro-body p-0">
                      <div className="form-row pro-pad">
                        <div className="form-group col-md-6">
                          <label>Username</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="form-group col-md-6">
                          <label>Email Address</label>
                          <input type="email" className="form-control" />
                        </div>
                        <div className="form-group col-md-6">
                          <label>Dispaly Name</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="form-group col-md-6">
                          <label>Tagline</label>
                          <input type="email" className="form-control" />
                        </div>
                        <div className="form-group col-md-6">
                          <label>Contact Number</label>
                          <input type="email" className="form-control" />
                        </div>
                        <div className="form-group col-md-6">
                          <label>Category</label>
                          <select className="form-control select">
                            <option value={0}>Male</option>
                            <option value={1}>Female</option>
                          </select>
                        </div>
                        <div className="form-group col-md-6">
                          <label>Gender</label>
                          <select className="form-control select">
                            <option value={0}>Male</option>
                            <option value={1}>Female</option>
                          </select>
                        </div>
                        <div className="form-group col-md-6">
                          <label>Language </label>
                          <input type="text" className="form-control" />
                        </div>
                      </div>
                      <div className="form-row pro-pad pt-0">
                        <div className="form-group col-md-6 pro-pic">
                          <label>Profile Picture</label>
                          <div className="d-flex align-items-center">
                            <div className="upload-images">
                              <img src={Img_02} alt="Image" />
                              <a
                                href=""
                                className="btn btn-icon btn-danger btn-sm"
                              >
                                <i className="far fa-trash-alt" />
                              </a>
                            </div>
                            <label className="file-upload image-upbtn ms-3">
                              Change Image <input type="file" />
                            </label>
                          </div>
                          <p>Image size 300*300</p>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
                <div className="card">
                  <div className="pro-head">
                    <h3 className="pro-title without-border mb-0">Location</h3>
                  </div>
                  <div className="pro-body">
                    <div className="row">
                      <div className="form-group col-md-12">
                        <label>Address</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>State</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Zipcode</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Country</label>
                        <select className="form-control select">
                          <option value={0}>India</option>
                          <option value={1}>China</option>
                          <option value={2}>Japan</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card">
                  <div className="pro-head">
                    <h3 className="pro-title without-border mb-0">Overview</h3>
                  </div>
                  <div className="pro-body">
                    <div className="row">
                      <div className="form-group col-md-12">
                        <textarea
                          className="form-control"
                          rows={5}
                          defaultValue={""}
                        />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card">
                  <div className="pro-head">
                    <h3 className="pro-title without-border mb-0">
                      Social Links
                    </h3>
                  </div>
                  <div className="pro-body">
                    <div className="row">
                      <div className="form-group col-md-6">
                        <label>Facebook</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Dribble</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Twitter</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>LinkedIn</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Behance</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group col-md-6">
                        <label>Behance</label>
                        <input type="text" className="form-control" />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card">
                  <div className="text-end">
                    <div className="pro-body">
                      <button
                        className="btn btn-secondary click-btn btn-plan"
                        type="submit"
                      >
                        Cancel
                      </button>&nbsp;
                      <button
                        className="btn btn-primary click-btn btn-plan"
                        type="submit"
                      >
                        Update
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {/* /Page Content */}
  </>
      )
  
}
export default Settings;

// template-angular/src/app/features-modules/freelancer/freelancer-settings/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss']
})
export class SettingsComponent implements OnInit {
  public skillsArray: any = [1,2,3,4,5,6];
  public awardsArray: any = [1,2,3];
  public langArray: any = [1,2,3];
  public expArray: any = [1];
  public eduArray: any = [1];
  gender = 'male';
  type = 'select';
  country = 'india';
  degree = 'select';
  constructor() { }

  ngOnInit(): void {
  }
  public addSkills():void {
    this.skillsArray.push(1)
  }
  public deleteSkills(index:any):void {
    this.skillsArray.splice(index, 1)
  }
  public addAward():void {
    this.awardsArray.push(1)
  }
  public deleteAward(index:any):void {
    this.awardsArray.splice(index, 1)
  }
  public addLang():void {
    this.langArray.push(1)
  }
  public deleteLang(index:any):void {
    this.langArray.splice(index, 1)
  }
  public addExp():void {
    this.expArray.push(1)
  }
  public deleteExp(index:any):void {
    this.expArray.splice(index, 1)
  }
  public addEdu():void {
    this.eduArray.push(1)
  }
  public deleteEdu(index:any):void {
    this.eduArray.splice(index, 1)
  }


}

<div class="pro-pos">
    <nav class="user-tabs mb-4">
        <ul class="nav nav-tabs nav-tabs-bottom nav-justified">
            <li class="nav-item">
                <a class="nav-link active" [routerLink] = "'/freelancer/freelancer-settings/profiles-settings'">Profile Settings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" [routerLink] = "'/freelancer/freelancer-settings/change-passwords'">Change Password</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " [routerLink] = "'/freelancer/freelancer-settings/delete-account'">Delete Account</a>
            </li>
        </ul>
    </nav>
    <div class="setting-content">																		
        <form>
            <div class="card">
                <div class="pro-head">
                    <h3 class="pro-title without-border mb-0">Profile Basics </h3>
                </div>	
                <div class="pro-body">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>Username</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Email Address</label>
                            <input type="email" class="form-control">

                        </div>
                        <div class="form-group col-md-6">
                            <label>Dispaly Name</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Designation</label>
                            <input type="email" class="form-control">

                        </div>
                        <div class="form-group col-md-6">
                            <label>Hourly Rate</label>
                            <input type="text" class="form-control">
                            <p class="light-pink-text mb-0">Provide your hourly rate without currency symbol</p>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Contact Number</label>
                            <input type="email" class="form-control">

                        </div>
                        <div class="form-group col-md-6">
                            <label>Gender</label>
                            <mat-select class="form-control"  [(value)]="gender">
                                <mat-option value="male">Male</mat-option>
                                <mat-option value="female">Female</mat-option>
                              </mat-select>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Type</label>
                            <mat-select class="form-control"  [(value)]="type">
                                <mat-option value="select">Select Freelancer Type</mat-option>
                                <mat-option value="freelancer">Freelancer</mat-option>
                              </mat-select>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Language </label>
                            <input type="text" class="form-control">
                        </div>
                    </div>												
                    <div class="form-row pro-pad pt-0">
                        <div class="form-group col-md-6 pro-pic">
                            <label>Profile Picture</label>
                            <div class="d-flex align-items-center">														
                                <div class="upload-images">
                                    <img src="assets/img/img-02.jpg" alt="Image">
                                    <a href="javascript:void(0);" class="btn btn-icon btn-danger btn-sm"><i class="far fa-trash-alt"></i></a>
                                </div>
                                <label class="file-upload image-upbtn ms-3">
                                    Change Image <input type="file">
                                </label>
                            </div>
                            <p>Image size 300*300</p>
                        </div>
                        <div class="form-group col-md-6 pro-pic">
                            <label>Banner Image</label>
                            <div class="d-flex align-items-center">														
                                <div class="upload-images">
                                    <img src="assets/img/img-02.jpg" alt="Image">
                                    <a href="javascript:void(0);" class="btn btn-icon btn-danger btn-sm"><i class="far fa-trash-alt"></i></a>
                                </div>
                                <label class="file-upload image-upbtn ms-3">
                                    Change Image <input type="file">
                                </label>
                            </div>
                            <p>Image size 1024*100</p>
                        </div>
                    </div>
                </div>
            </div>
        
            <div class="card">
                <div class="pro-head">
                    <h3 class="pro-title without-border mb-0">Location</h3>
                </div>
                <div class="pro-body">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label>Address</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>State</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Zipcode</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Country</label>
                            <mat-select class="form-control"  [(value)]="country">
                                <mat-option value="india">India</mat-option>
                                <mat-option value="china">China</mat-option>
                                <mat-option value="japan">Japan</mat-option>
                              </mat-select>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card">
                <div class="pro-head">
                    <h3 class="pro-title without-border mb-0">Overview</h3>
                </div>
                <div class="pro-body">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <textarea class="form-control" rows="5"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="form-row" >
                <div class="col-md-12 col-xl-4 d-flex">
                    <div class="pro-card flex-fill mb-3" >
                        <div class="pro-head">
                            <h3 class="pro-title without-border mb-0">Skills</h3>
                            <a href="javascript:void(0);" class="btn fund-btn skill-add" (click)="addSkills()">Add More</a>
                        </div>
                        <div class="pro-body skill-info" >
                            <div class="form-row align-items-center skill-cont" *ngFor="let skills of skillsArray; let i = index">
                                <div class="form-group col-md-10">
                                    <input type="text" class="form-control" placeholder="Front End Developer">
                                </div>
                                <div class="form-group col-md-2" *ngIf="i != 10">
                                    <a href="javascript:void(0);" class="btn trash-icon" (click)="deleteSkills(i)"><i class="far fa-trash-alt"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-12 col-xl-8">
                    <div class="card">
                        <div class="pro-head">
                            <h3 class="pro-title without-border mb-0">Awards / Certificates</h3>
                            <a href="javascript:void(0);" class="btn fund-btn add-award" (click)="addAward()">Add More</a>
                        </div>
                        <div class="pro-body  award-info">
                            <div class="form-row align-items-center award-cont" *ngFor="let awards of awardsArray; let i = index">
                                <div class="form-group col-md-2">
                                    <img alt="profile image" src="assets/img/img.jpg" class="avatar-medium">
                                </div>
                                <div class="form-group col-md-5">
                                    <input type="text" class="form-control" value="Best Game Designer">
                                </div>
                                <div class="form-group col-md-3">
                                    <input type="text" class="form-control " value="05/10/2020">
                                </div>
                                <div class="form-group col-md-2" *ngIf="i != 10">
                                    <a href="javascript:void(0);" class="btn trash-icon" (click)="deleteAward(i)"><i class="far fa-trash-alt"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="card">
                        <div class="pro-head">
                            <h3 class="pro-title without-border mb-0">Languages</h3>
                            <a href="javascript:void(0);" class="btn fund-btn add-lang" (click)="addLang()">Add More</a>
                        </div>
                        <div class="pro-body  lang-info">
                            <div class="form-row align-items-center lang-cont" *ngFor="let lang of langArray; let i = index">
                                <div class="form-group col-md-7">
                                    <input type="text" class="form-control" value="English">
                                </div>
                                <div class="form-group col-md-3">
                                    <input type="text" class="form-control" value="100">
                                </div>
                                <div class="form-group col-md-2">
                                    <a href="javascript:void(0);" class="btn trash-icon" (click)="deleteLang(i)"><i class="far fa-trash-alt"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>											
                </div>										
            </div>
            
            <div class="card">
                <div class="pro-head">
                    <h3 class="pro-title without-border mb-0">Experience</h3>
                    <a href="javascript:void(0);" class="btn fund-btn add-exp" (click)="addExp()">Add More</a>
                </div>
                <div class="pro-body">
                    <div class="exp-info"  *ngFor="let Exp of expArray; let i = index">
                        <div class="row exp-cont">
                            <div class="form-group col-md-6">
                                <label>Title</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label>Company name</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group position-relative col-md-6">
                                <label>Start date</label>
                                <input class="form-control" matInput [matDatepicker]="picker" placeholder="Select Date">
                                <mat-datepicker-toggle matIconSuffix [for]="picker"></mat-datepicker-toggle>
                                <mat-datepicker #picker></mat-datepicker>
                            </div>
                            <div class="form-group position-relative col-md-6">
                                <label>End Date</label>
                                <input class="form-control" matInput [matDatepicker]="picker2" placeholder="Select Date">
                                <mat-datepicker-toggle matIconSuffix [for]="picker2"></mat-datepicker-toggle>
                                <mat-datepicker #picker2></mat-datepicker>
                            </div>
                            <div class="form-group col-md-12">
                                <label class="custom_check">
                                    <input type="checkbox" name="rem_password">
                                    <span class="checkmark"></span> I'm currently working here
                                </label>
                            </div>
                            <div class="form-group col-md-12">
                                <label>Summary</label>
                                <textarea class="form-control" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="form-group col-md-2">
                            <a href="javascript:void(0);" class="btn trash-icon" (click)="deleteExp(i)"><i class="far fa-trash-alt"></i></a>
                        </div>
                    </div>
                    
                </div>
            </div>
            
            <div class="card">
                <div class="pro-head">
                    <h3 class="pro-title without-border mb-0">Educational Details</h3>
                    <a href="javascript:void(0);" class="btn fund-btn" (click)="addEdu()">Add More Skills</a>
                </div>
                <div class="pro-body" *ngFor="let edu of eduArray; let i = index">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label>Degree Title</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>University/College</label>
                            <mat-select class="form-control"  [(value)]="degree">
                                <mat-option value="select">Select University/College</mat-option>
                                <mat-option value="university">University</mat-option>
                                <mat-option value="college">College</mat-option>
                              </mat-select>
                        </div>
                        <div class="form-group position-relative col-md-6">
                            <label>Start year</label>
                            <input class="form-control" matInput [matDatepicker]="picker3" placeholder="Select Date">
                            <mat-datepicker-toggle matIconSuffix [for]="picker3"></mat-datepicker-toggle>
                            <mat-datepicker #picker3></mat-datepicker>
                        </div>
                        <div class="form-group position-relative col-md-6">
                            <label>End year</label>
                            <input class="form-control" matInput [matDatepicker]="picker4" placeholder="Select Date">
                            <mat-datepicker-toggle matIconSuffix [for]="picker4"></mat-datepicker-toggle>
                            <mat-datepicker #picker4></mat-datepicker>
                        </div>
                        <div class="form-group col-md-12">
                            <label>Summary</label>
                            <textarea class="form-control" rows="5"></textarea>
                        </div>
                    </div>
                    <div class="form-group col-md-2">
                        <a href="javascript:void(0);" class="btn trash-icon" (click)="deleteEdu(i)"><i class="far fa-trash-alt"></i></a>
                    </div>
                </div>
            </div>
            
            <div class="card">
                <div class="pro-head">
                    <h3 class="pro-title without-border mb-0">Social Links</h3>
                </div>
                <div class="pro-body">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>Facebook</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Dribble</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Twitter</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>LinkedIn</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Behance</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Behance</label>
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="card text-end">
                <div class="pro-body">
                    <button class="btn btn-secondary click-btn btn-plan">Cancel</button>
                    <button class="btn btn-primary click-btn btn-plan ms-1" type="submit">Update</button>
                </div>
            </div>
        </form>
    </div>
</div>
