// template-angular/src/app/features-modules/freelancer/portfolio/portfolio.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-portfolio',
  templateUrl: './portfolio.component.html',
  styleUrls: ['./portfolio.component.scss']
})
export class PortfolioComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  images = [
    {
      path : 'assets/img/project-1.jpg',
      port: 'Razor Website Design'
    },
    {
      path : 'assets/img/project-2.jpg',
      port: 'Transport Website'
    },
    {
      path : 'assets/img/project-3.jpg',
      port: 'Wordpress Website'
    },
    {
      path : 'assets/img/project-4.jpg',
      port: 'Mobile App'
    },
    {
      path : 'assets/img/project-5.jpg',
      port: 'Healthcare Website'
    },
    {
      path : 'assets/img/project-6.jpg',
      port: 'Injury Website'
    },
    {
      path : 'assets/img/project-7.jpg',
      port: 'Website Design'
    },
  ]

}

<div class="portfolio-item">
	<div class="pro-head p-0 pb-4">
		<h3 class="mb-0">Portfolio</h3>
		<a class="btn btn-primary back-btn br-0" data-bs-toggle="modal" href="#portfolio">+ Add Portfolio</a>
	</div>
	<div class="pro-content pt-4 pb-4">
		<div class="row">
			<div class="col-sm-6 col-lg-4" *ngFor = "let image of images">
				<div class="project-widget">
					<div class="portfolio-img">
						<img class="img-fluid" alt="User Image" [src]="image.path">
						<div class="portfolio-live">
						<div class="portfolio-content">
							<a data-bs-toggle="modal" href="#portfolio-edit" class="port-icon me-1"><i class="fas fa-pen"></i></a>
							<a href="#" class="port-icon"><i class="fas fa-trash-alt"></i></a>
						</div>
						</div>
					</div>
					<div class="portfolio-detail">
						<h3 class="pro-name">{{image.port}}</h3>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-12">
			<ul class="paginations">
				<li><a href="#"> <i class="fas fa-angle-left"></i> Previous</a></li>
				<li><a href="#">1</a></li>
				<li><a href="#" class="active">2</a></li>
				<li><a href="#">3</a></li>
				<li><a href="#">4</a></li>
				<li><a href="#">Next <i class="fas fa-angle-right"></i></a></li>
			</ul>
		</div>
	</div>
</div>

            		<!-- The Modal -->
		<div class="modal fade" id="portfolio">
			<div class="modal-dialog modal-dialog-centered modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<h4>Add Portfolio</h4>
						<span class="modal-close"><a href="#" data-bs-dismiss="modal" aria-label="Close"><i class="far fa-times-circle orange-text"></i></a></span>
					</div>
					<div class="modal-body">
						<div class="port-title">
							<h3>Simple & Best Way To Showcase Your Work</h3>
						</div>						
						<form action="freelancer-portfolio.html">
							<div class="modal-info">
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label>Title</label>
											<input type="text" class="form-control">
										</div>
										<div class="form-group">
											<label>Link</label>
											<input type="text" class="form-control">
										</div>
										<label class="br-0 file-upload image-upbtn">
											upload Files <input type="file">
										</label>
									</div>
								</div>
							</div>
							<div class="submit-section text-right">
								<a data-bs-dismiss="modal" class="btn btn-primary black-btn submit-btn">Cancel</a>
								<button type="submit" class="btn btn-primary submit-btn">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		
		<!-- The Modal -->
		<div class="modal fade" id="portfolio-edit">
			<div class="modal-dialog modal-dialog-centered modal-lg">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title">Add Portfolio</h4>
						<span class="modal-close"><a href="#" data-bs-dismiss="modal" aria-label="Close"><i class="far fa-times-circle orange-text"></i></a></span>
					</div>
					<div class="modal-body">
						<div class="port-title">
							<h3>Simple & Best Way To Showcase Your Work</h3>
						</div>						
						<form action="freelancer-portfolio.html">
							<div class="modal-info">
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label>Title</label>
											<input type="text" class="form-control" value="Portfolio Name">
										</div>
										<div class="form-group">
											<label>Link</label>
											<input type="text" class="form-control" value="Http://www.example.com//john...">
										</div>
										<label class="br-0 file-upload image-upbtn">
											upload Files <input type="file">
										</label>
									</div>
								</div>
							</div>
							<div class="submit-section text-right">
								<a data-bs-dismiss="modal" class="btn btn-primary black-btn submit-btn">Cancel</a>
								<a data-bs-dismiss="modal" class="btn btn-primary submit-btn">Submit</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

// template-react/src/frontend/components/forfreelancer/portfolio/index.jsx
import React, { useEffect } from "react";
import { Link } from "react-router-dom";
import StickyBox from "react-sticky-box";
import { Sidebar } from '../sidebar';
import { home_icon, Project_1, Project_2, Project_3, Project_4, Project_5, Project_6 } from "../../imagepath";

const FreelancerPortfolio = (props) => {
  useEffect(() => {
    document.body.className = 'dashboard-page';
    return () => { document.body.className = ''; }
  });

  return (
    <>
      {/* Breadcrumb */}
      <div className="bread-crumb-bar">
        <div className="container">
          <div className="row align-items-center inner-banner">
            <div className="col-md-12 col-12 text-center">
              <div className="breadcrumb-list">
                <nav aria-label="breadcrumb" className="page-breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item"><Link to="#"><img src={home_icon} alt="Post Author" /> Home</Link></li>
                    <li className="breadcrumb-item" aria-current="page">Employee</li>
                    <li className="breadcrumb-item" aria-current="page">PORTFOLIO</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Breadcrumb */}
      {/* Page Content */}
      <div className="content content-page">
        <div className="container-fluid">
          <div className="row">
            <div className="col-xl-3 col-md-4 theiaStickySidebar">
              <StickyBox offsetTop={20} offsetBottom={20}>
                <Sidebar />
              </StickyBox>
            </div>
            <div className="col-xl-9 col-md-8">
              <div className="portfolio-item">
                <div className="pro-head p-0 pb-4">
                  <h3 className="mb-0">Portfolio</h3>
                  <a
                    className="btn btn-primary back-btn br-0"
                    data-bs-toggle="modal"
                    href="#portfolio"
                  >
                    + Add Portfolio
                  </a>
                </div>
                <div className="pro-content pt-4 pb-4">
                  <div className="row">
                    <div className="col-sm-6 col-lg-4">
                      <div className="project-widget">
                        <div className="portfolio-img">
                          <img
                            className="img-fluid"
                            alt="User Image"
                            src={Project_1}
                          />
                          <div className="portfolio-live">
                            <div className="portfolio-content">
                              <a
                                data-bs-toggle="modal"
                                href="#portfolio-edit"
                                className="port-icon"
                              >
                                <i className="fas fa-pen" />
                              </a>
                              <a href="#" className="port-icon">
                                <i className="fas fa-trash-alt" />
                              </a>
                            </div>
                          </div>
                        </div>
                        <div className="portfolio-detail">
                          <h3 className="pro-name">Razor Website Design</h3>
                        </div>
                      </div>
                    </div>
                    <div className="col-sm-6 col-lg-4">
                      <div className="project-widget">
                        <div className="portfolio-img">
                          <img
                            className="img-fluid"
                            alt="User Image"
                            src={Project_2}
                          />
                          <div className="portfolio-live">
                            <div className="portfolio-content">
                              <a
                                data-bs-toggle="modal"
                                href="#portfolio-edit"
                                className="port-icon"
                              >
                                <i className="fas fa-pen" />
                              </a>
                              <a href="#" className="port-icon">
                                <i className="fas fa-trash-alt" />
                              </a>
                            </div>
                          </div>
                        </div>
                        <div className="portfolio-detail">
                          <h3 className="pro-name">Transport Website</h3>
                        </div>
                      </div>
                    </div>
                    <div className="col-sm-6 col-lg-4">
                      <div className="project-widget">
                        <div className="portfolio-img">
                          <img
                            className="img-fluid"
                            alt="User Image"
                            src={Project_3}
                          />
                          <div className="portfolio-live">
                            <div className="portfolio-content">
                              <a
                                data-bs-toggle="modal"
                                href="#portfolio-edit"
                                className="port-icon"
                              >
                                <i className="fas fa-pen" />
                              </a>
                              <a href="#" className="port-icon">
                                <i className="fas fa-trash-alt" />
                              </a>
                            </div>
                          </div>
                        </div>
                        <div className="portfolio-detail">
                          <h3 className="pro-name">Wordpress Website</h3>
                        </div>
                      </div>
                    </div>
                    <div className="col-sm-6 col-lg-4">
                      <div className="project-widget">
                        <div className="portfolio-img">
                          <img
                            className="img-fluid"
                            alt="User Image"
                            src={Project_4}
                          />
                          <div className="portfolio-live">
                            <div className="portfolio-content">
                              <a
                                data-bs-toggle="modal"
                                href="#portfolio-edit"
                                className="port-icon"
                              >
                                <i className="fas fa-pen" />
                              </a>
                              <a href="#" className="port-icon">
                                <i className="fas fa-trash-alt" />
                              </a>
                            </div>
                          </div>
                        </div>
                        <div className="portfolio-detail">
                          <h3 className="pro-name">Mobile App</h3>
                        </div>
                      </div>
                    </div>
                    <div className="col-sm-6 col-lg-4">
                      <div className="project-widget">
                        <div className="portfolio-img">
                          <img
                            className="img-fluid"
                            alt="User Image"
                            src={Project_5}
                          />
                          <div className="portfolio-live">
                            <div className="portfolio-content">
                              <a
                                data-bs-toggle="modal"
                                href="#portfolio-edit"
                                className="port-icon"
                              >
                                <i className="fas fa-pen" />
                              </a>
                              <a href="#" className="port-icon">
                                <i className="fas fa-trash-alt" />
                              </a>
                            </div>
                          </div>
                        </div>
                        <div className="portfolio-detail">
                          <h3 className="pro-name">Healthcare Website</h3>
                        </div>
                      </div>
                    </div>
                    <div className="col-sm-6 col-lg-4">
                      <div className="project-widget">
                        <div className="portfolio-img">
                          <img
                            className="img-fluid"
                            alt="User Image"
                            src={Project_6}
                          />
                          <div className="portfolio-live">
                            <div className="portfolio-content">
                              <a
                                data-bs-toggle="modal"
                                href="#portfolio-edit"
                                className="port-icon"
                              >
                                <i className="fas fa-pen" />
                              </a>
                              <a href="#" className="port-icon">
                                <i className="fas fa-trash-alt" />
                              </a>
                            </div>
                          </div>
                        </div>
                        <div className="portfolio-detail">
                          <h3 className="pro-name">Injury Website</h3>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-12">
                    <ul className="paginations">
                      <li>
                        <a href="#">
                          {" "}
                          <i className="fas fa-angle-left" /> Previous
                        </a>
                      </li>
                      <li>
                        <a href="#">1</a>
                      </li>
                      <li>
                        <a href="#" className="active">
                          2
                        </a>
                      </li>
                      <li>
                        <a href="#">3</a>
                      </li>
                      <li>
                        <a href="#">4</a>
                      </li>
                      <li>
                        <a href="#">
                          Next <i className="fas fa-angle-right" />
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /Page Content */}
      {/* The Modal */}
      <div className="modal fade" id="portfolio">
        <div className="modal-dialog modal-dialog-centered modal-lg">
          <div className="modal-content">
            <div className="modal-header">
              <h4>Add Portfolio</h4>
              <span className="modal-close">
                <a href="#" data-bs-dismiss="modal" aria-label="Close">
                  <i className="far fa-times-circle orange-text" />
                </a>
              </span>
            </div>
            <div className="modal-body">
              <div className="port-title">
                <h3>Simple &amp; Best Way To Showcase Your Work</h3>
              </div>
              <form >
                <div className="modal-info">
                  <div className="row">
                    <div className="col-md-12">
                      <div className="form-group">
                        <label>Title</label>
                        <input type="text" className="form-control" />
                      </div>
                      <div className="form-group">
                        <label>Link</label>
                        <input type="text" className="form-control" />
                      </div>
                      <label className="br-0 file-upload image-upbtn">
                        upload Files <input type="file" />
                      </label>
                    </div>
                  </div>
                </div>
                <div className="submit-section text-right">
                  <a
                    data-bs-dismiss="modal"
                    className="btn btn-primary black-btn submit-btn"
                  >
                    Cancel
                  </a>
                  <button type="submit" className="btn btn-primary submit-btn">
                    Submit
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      {/* The Modal */}
      <div className="modal fade" id="portfolio-edit">
        <div className="modal-dialog modal-dialog-centered modal-lg">
          <div className="modal-content">
            <div className="modal-header">
              <h4 className="modal-title">Add Portfolio</h4>
              <span className="modal-close">
                <a href="#" data-bs-dismiss="modal" aria-label="Close">
                  <i className="far fa-times-circle orange-text" />
                </a>
              </span>
            </div>
            <div className="modal-body">
              <div className="port-title">
                <h3>Simple &amp; Best Way To Showcase Your Work</h3>
              </div>
              <form >
                <div className="modal-info">
                  <div className="row">
                    <div className="col-md-12">
                      <div className="form-group">
                        <label>Title</label>
                        <input
                          type="text"
                          className="form-control"
                          defaultValue="Portfolio Name"
                        />
                      </div>
                      <div className="form-group">
                        <label>Link</label>
                        <input
                          type="text"
                          className="form-control"
                          defaultValue="Http://www.example.com//john..."
                        />
                      </div>
                      <label className="br-0 file-upload image-upbtn">
                        upload Files <input type="file" />
                      </label>
                    </div>
                  </div>
                </div>
                <div className="submit-section text-right">
                  <a
                    data-bs-dismiss="modal"
                    className="btn btn-primary black-btn submit-btn"
                  >
                    Cancel
                  </a>
                  <Link
                    to="/freelancer-portfolio"
                    className="btn btn-primary submit-btn"
                  >
                    Submit
                  </Link>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  )

}
export default FreelancerPortfolio;
